declare namespace Cloudflare {
  interface Env {
    MODERATION_FRAMEWORK_ENABLED?: string;
    MODERATION_AI_ENABLED?: string;
    MODERATION_EXTERNAL_AI_ENABLED?: string;
    MODERATION_AI_MODEL?: string;
    MODERATION_AI_SHADOW_MODE?: string;
    MODERATION_AI_ENABLED_SINCE?: string;
    MODERATION_PERCEPTUAL_HASH_ENABLED?: string;
    OPENAI_API_KEY?: string;
    MODERATION_AI_PROVIDER?: string;
    MODERATION_OCR_PROVIDER?: string;
    MODERATION_EXTERNAL_PROCESSING_BASIS?: string;
    MODERATION_SMS_ENABLED?: string;
    MODERATION_SMS_PROVIDER?: string;
    NEXT_PUBLIC_SUPABASE_URL?: string;
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY?: string;
    NEXT_PUBLIC_SUPABASE_ANON_KEY?: string;
    SUPABASE_SECRET_KEY?: string;
    SUPABASE_SERVICE_ROLE_KEY?: string;
    MARKETO_MEDIA?: R2Bucket;
    MARKETO_IMAGES?: ImagesBinding;
  }
}
