import test from 'node:test';import assert from 'node:assert/strict';import {automaticDatabase} from './helpers/automatic-db.mjs';import {randomUUID} from 'node:crypto';
test('canonical status: current revision, publication, filters/counts, owner, manual receipts, security and lifecycle',async t=>{
 const d=await automaticDatabase(),{db,as,users,make,submit,hash}=d;
 const state=async id=>(await db.query('select * from private.moderation_effective where id=$1',[id])).rows[0];
 const queue=async filter=>(await as(users.owner,'select public.moderation_dashboard($1,1,50) q',[filter])).rows[0].q;
 const done=async({technical=false,risk=false}={})=>{const id=await make();await submit(id);await db.query("update private.moderation_runs set status='completed',decision='HUMAN_REVIEW',decision_basis=$2,error_code=$3,completed_at=now(),automatic_trace=$4 where listing_id=$1",[id,technical?'technical_hold':'uncertain',technical?'required_stage_unavailable':null,{canonical_families:risk?['ocr_partial_risk']:[]}]);return id;};
 try{
 await t.test('published legacy Toyota has no pending state, including owner and detail',async()=>{const id=await make({title:'Тойота Камри 2020 года',category:'car'});await db.query("update public.listings set status='active',published_at=now() where id=$1",[id]);assert.equal((await state(id)).effective_state,'published');assert.equal((await state(id)).current_revision,(await state(id)).published_revision);const q=await queue('pending');assert.ok(!q.items.some(x=>x.id===id));const owner=(await as(users.seller,'select public.my_moderation_statuses($1) s',[[id]])).rows[0].s;assert.equal(owner[id].label_code,'published');const detail=(await as(users.owner,'select public.moderation_case($1) c',[id])).rows[0].c;assert.equal(detail.summary.label_code,'published');});
 await t.test('published previous revision and actual current queued revision have explicit dual state',async()=>{const id=await make();await submit(id);await db.query("update public.listings set status='active',published_at=now() where id=$1",[id]);await db.query("update private.listing_moderation_state set published_revision_hash=repeat('f',64) where listing_id=$1",[id]);assert.equal((await state(id)).label_code,'published_changes_pending');assert.ok((await queue('pending')).items.some(x=>x.id===id&&x.label_code==='published_changes_pending'));});
 let manual;
 await t.test('semantic/technical/queued/archived predicates are the same for rows and aggregate counts',async()=>{await done();await done({technical:true});const queued=await make();await submit(queued);const archived=await make();await submit(archived);await db.query("update public.listings set status='archived' where id=$1",[archived]);const all=await queue('all');for(const filter of ['all','approved','rejected','needs_fix','uncertain','technical','overrides','reports','appeals','pending']){const q=await queue(filter);assert.equal(q.total,q.items.length);assert.equal(all.counts[filter],q.total);for(const item of q.items)assert.ok((await state(item.id)).filters.includes(filter));}for(const item of all.items)assert.equal(item.label_code,(await state(item.id)).label_code);assert.ok(!(await queue('pending')).items.some(x=>x.id===archived));});
 await t.test('manual approve removes uncertainty everywhere and preserves automatic history/dates',async()=>{manual=await done();const before=(await db.query('select decision from private.moderation_runs where listing_id=$1',[manual])).rows[0];const receipt=(await as(users.owner,"select public.moderate_listing_checked($1,'approve',$2,$3) r",[manual,await hash(manual),randomUUID()])).rows[0].r;assert.equal(receipt.summary.label_code,'manual_approved');assert.equal((await state(manual)).label_code,'manual_approved');assert.ok(!(await queue('uncertain')).items.some(x=>x.id===manual));assert.ok((await queue('overrides')).items.some(x=>x.id===manual));assert.deepEqual((await db.query('select decision from private.moderation_runs where listing_id=$1',[manual])).rows[0],before);const owner=(await as(users.seller,'select public.get_listing_moderation($1) s',[manual])).rows[0].s;assert.equal(owner.label_code,'manual_approved');assert.deepEqual(owner.reasons,[]);});
 await t.test('promotion leaves revisions/dates/runs unchanged',async()=>{const before=await state(manual),n=(await db.query('select count(*)::int n from private.moderation_runs where listing_id=$1',[manual])).rows[0].n;await as(users.seller,"select public.set_listing_promotion_choice($1,'maximum')",[manual]);const after=await state(manual);for(const k of ['current_revision','published_revision','published_at','expires_at','label_code'])assert.deepEqual(after[k],before[k]);assert.equal((await db.query('select count(*)::int n from private.moderation_runs where listing_id=$1',[manual])).rows[0].n,n);});
 await t.test('changed content updates pointer and does not inherit old manual approval',async()=>{const before=await state(manual);await as(users.seller,"select public.owner_listing_transition($1,'edit')",[manual]);await as(users.seller,"update public.listings set title='Другая текущая версия' where id=$1",[manual]);await submit(manual);const after=await state(manual);assert.notEqual(after.current_revision,before.current_revision);assert.equal(after.published_revision,before.published_revision);assert.equal(after.manual_decision,null);assert.equal(after.effective_state,'pending');});
 await t.test('partial-risk retry same revision creates a run, definitive compatible result is idempotent',async()=>{const id=await done({risk:true});const old=(await state(id)).run_id;const next=(await db.query('select private.enqueue_moderation($1) id',[id])).rows[0].id;assert.notEqual(next,old);assert.equal((await db.query('select private.enqueue_moderation($1) id',[id])).rows[0].id,next);await db.query("update private.moderation_runs set status='completed',decision='APPROVED',decision_basis='ai_assisted',error_code=null where id=$1",[next]);assert.equal((await db.query('select private.enqueue_moderation($1) id',[id])).rows[0].id,next);assert.equal((await state(id)).is_public,true);});
 await t.test('history from another revision cannot put a listing in a current unresolved filter',async()=>{const id=await done({technical:true});await as(users.seller,"select public.owner_listing_transition($1,'edit')",[id]);await as(users.seller,"update public.listings set description='Новая версия без старой ошибки' where id=$1",[id]);assert.equal((await state(id)).effective_state,'draft');assert.ok(!(await queue('technical')).items.some(x=>x.id===id));});
 await t.test('batch owner statuses, no staff evidence/other-owner leakage or client writes',async()=>{const id=await done();const s=(await as(users.stranger,'select public.my_moderation_statuses($1) s',[[id]])).rows[0].s;assert.deepEqual(s,{});for(const sql of ['select * from private.moderation_effective','update private.listing_moderation_state set current_revision_hash=repeat(\'0\',64)','select public.moderation_staff_audit($1)'])await assert.rejects(as(users.seller,sql,sql.includes('$1')?[id]:[]),/permission|staff/);const own=(await as(users.seller,'select public.my_moderation_statuses($1) s',[[id]])).rows[0].s;assert.doesNotMatch(JSON.stringify(own),/ai_calls|provider_status|automatic_trace|claim_token/);});
 }finally{await db.close();}
});
