import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {Miniflare,createFetchMock} from 'miniflare';import {readFile} from 'node:fs/promises';
import {cleanObservation,responseBody} from './helpers/moderation-ai-fixtures.mjs';
test('workerd: validated Responses -> mandatory stages -> automatic decision; provider failure holds',async()=>{
 const jpeg=await readFile('tests/moderation/benchmark/v1/images/phone.jpg');
 const entry=`import {OpenAIModerationProvider} from './lib/moderation/openai-provider.ts';import {moderate} from './lib/moderation/engine.ts';import {UnavailableAIProvider,UnavailableOCRProvider} from './lib/moderation/providers.ts';import {executeShadow} from './lib/moderation/ai-execution.ts';import {evaluateAutomatic} from './lib/moderation/automatic.ts';
 export default {async fetch(request,env){const bytes=Uint8Array.from(atob(env.JPEG),c=>c.charCodeAt(0)),snapshot={title:'Телефон',description:'Обычный телефон в хорошем состоянии.',category_path:[{slug:'phone',ru:'Телефон',kk:'Телефон'}],attributes:[],images:[{storage_key:'fixture.jpg'}]},base=await moderate({snapshot,rules:[],fraud:{recent_submissions:1,prior_rejections:0,confirmed_reports:0,duplicate_content:0,reused_images:0},ai:new UnavailableAIProvider(),ocr:new UnavailableOCRProvider(),loadImage:async()=>bytes,allowExternal:false});let response,n=0;const shadow=await executeShadow({provider:new OpenAIModerationProvider({key:'synthetic-workerd-key',model:'gpt-5.6-luna'}),data:{title:snapshot.title,description:snapshot.description,category:'Телефон',attributes:'[]',images:[{image_index:0,bytes,mimeType:'image/jpeg'}]},rules:[],base,signal:AbortSignal.timeout(2000),reserve:async()=>++n,record:async()=>{},onValidated:r=>{response=r;},sleep:async()=>{}});const final=await evaluateAutomatic({base,rules:[],response,providerStatus:shadow.status,switches:{enabled:true,approval:true,rejection:true}});return Response.json(final);}}`;
 const bundle=await build({stdin:{contents:entry,loader:'ts',resolveDir:process.cwd()},bundle:true,write:false,format:'esm',platform:'browser',target:'es2022'});
 const network=createFetchMock();network.disableNetConnect();network.get('https://api.openai.com').intercept({path:'/v1/responses',method:'POST'}).reply(200,JSON.stringify(responseBody(cleanObservation())));network.get('https://api.openai.com').intercept({path:'/v1/responses',method:'POST'}).reply(503,'{}').times(2);
 const mf=new Miniflare({host:'127.0.0.1',modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-05-22',compatibilityFlags:['nodejs_compat'],fetchMock:network,bindings:{JPEG:jpeg.toString('base64')}});
 try{const approved=await(await mf.dispatchFetch('https://fixture.test')).json();assert.equal(approved.result.decision,'APPROVED');assert.equal(approved.trace.schema_validated,true);const failed=await(await mf.dispatchFetch('https://fixture.test')).json();assert.equal(failed.result.decision,'HUMAN_REVIEW');assert.equal(failed.trace.basis,'technical_hold');assert.ok(!JSON.stringify(failed).includes('synthetic-workerd-key'));}finally{await mf.dispose();await network.close();}
});
