import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {automaticDatabase} from './helpers/automatic-db.mjs';
import {readFile} from 'node:fs/promises';import {moderate} from '../lib/moderation/engine.ts';import {evaluateAutomatic} from '../lib/moderation/automatic.ts';import {UnavailableAIProvider,UnavailableOCRProvider} from '../lib/moderation/providers.ts';
test('reliability migration: action matrix, receipts, revision retry, compact scoped reads and filters',async t=>{
 const d=await automaticDatabase(),{db,as,make,submit,claim,finish,users,hash}=d;const jpg=await readFile('tests/moderation/benchmark/v1/images/tv.jpg');
 const completed=async(decision='HUMAN_REVIEW')=>{const id=await make();await submit(id);const job=await claim();const base=await moderate({snapshot:job.snapshot,rules:job.rules,fraud:{recent_submissions:0,prior_rejections:0,confirmed_reports:0,duplicate_content:0,reused_images:0},ai:new UnavailableAIProvider(),ocr:new UnavailableOCRProvider(),loadImage:async()=>jpg,allowExternal:false,lexicalAIState:'READY'});const evaluated=await evaluateAutomatic({base,rules:job.rules,providerStatus:'invalid_schema',switches:{enabled:true,approval:true,rejection:true}});await finish(job,{...evaluated.result,automatic:evaluated.trace});
 // Fixture labels for manual-transition matrix; full automatic publication is covered in automatic-db.test.
 if(decision!=='HUMAN_REVIEW'){await db.query('update private.moderation_runs set decision=$2,decision_basis=$3,error_code=null where id=$1',[job.id,decision,decision==='NEEDS_FIX'?'fixable':'ai_assisted']);await db.query("select private.apply_listing_moderation($1,$2,null,null,null)",[id,decision==='APPROVED'?'approve':'reject']);}return {id,job};};
 const act=async(id,action,{reason=action==='approve'?null:'other',note=action==='approve'?null:'Изолированная проверка',request=randomUUID(),revision}={})=>(await as(users.owner,'select public.moderate_listing_checked($1,$2,$3,$4,$5,$6) value',[id,action,revision??await hash(id),request,reason,note])).rows[0].value;
 try{
 for(const [before,after] of [['HUMAN_REVIEW','approve'],['HUMAN_REVIEW','reject'],['HUMAN_REVIEW','needs_fix'],['APPROVED','reject'],['REJECTED','approve'],['NEEDS_FIX','approve']])await t.test(before+' → '+after,async()=>{const {id,job}=await completed(before);const dates=(await db.query('select published_at,expires_at from public.listings where id=$1',[id])).rows[0];const token=randomUUID();const result=await act(id,after,{request:token});assert.equal(result.status,after==='approve'?'active':'rejected');assert.equal(result.decision,after.toUpperCase());assert.deepEqual(await act(id,after,{request:token}),{...result,replayed:true});assert.equal((await db.query('select count(*)::int n from private.moderation_overrides where listing_id=$1',[id])).rows[0].n,1);assert.equal((await db.query('select decision from private.moderation_runs where id=$1',[job.id])).rows[0].decision,before);const audit=(await as(users.owner,'select public.get_listing_moderation($1,true) value',[id])).rows[0].value;assert.equal(audit.overrides[0].new_decision,after.toUpperCase());if(dates.published_at)assert.deepEqual((await db.query('select published_at,expires_at from public.listings where id=$1',[id])).rows[0],dates);});
 await t.test('required repair/reject reason, authorization and stale revision cannot be bypassed',async()=>{const {id}=await completed();for(const action of ['reject','needs_fix']){await assert.rejects(act(id,action,{reason:null}),/reason_code/);await assert.rejects(act(id,action,{note:null}),/reason required/);}await assert.rejects(act(id,'approve',{revision:'0'.repeat(64)}),/stale revision/);await assert.rejects(as(users.seller,'select public.moderate_listing_checked($1,\'approve\',$2,$3)',[id,await hash(id),randomUUID()]),/permission/);for(const sql of ['select public.moderation_case($1)','select public.moderation_dashboard()'])await assert.rejects(as(users.seller,sql,sql.includes('$1')?[id]:[]),/staff/);const ownerView=(await as(users.seller,'select public.get_listing_moderation($1,true) value',[id])).rows[0].value;assert.ok(!ownerView.run&&!JSON.stringify(ownerView).includes('automatic_trace'));});
 await t.test('an old receipt cannot report success after archival',async()=>{const {id}=await completed();const request=randomUUID();await act(id,'approve',{request});await db.query("update public.listings set status='archived' where id=$1",[id]);await assert.rejects(act(id,'approve',{request}),/stale receipt status/);});
 await t.test('same content technical retry creates one generation; pending double submit remains idempotent',async()=>{const {id,job}=await completed(),rev=await hash(id);await as(users.seller,"select public.owner_listing_transition($1,'edit')",[id]);await submit(id);const next=await claim();assert.notEqual(next.id,job.id);assert.equal(next.content_revision_hash,rev);const second=(await db.query('select private.enqueue_moderation($1) id',[id])).rows[0].id;assert.equal(second,next.id);assert.equal((await db.query('select count(*)::int n from private.listing_content_revisions where listing_id=$1',[id])).rows[0].n,1);await db.query("update private.moderation_runs set status='completed',decision='HUMAN_REVIEW',decision_basis='uncertain',error_code=null where id=$1",[next.id]);assert.equal((await db.query('select private.enqueue_moderation($1) id',[id])).rows[0].id,next.id);});
 await t.test('semantic/technical/pending/archived are separate; one core read excludes full history',async()=>{const {id}=await completed();const dashboard=async filter=>(await as(users.owner,'select public.moderation_dashboard($1) q',[filter])).rows[0].q;assert.ok((await dashboard('technical')).items.some(x=>x.id===id));assert.ok(!(await dashboard('uncertain')).items.some(x=>x.id===id));assert.ok(!(await dashboard('pending')).items.some(x=>x.id===id));const core=(await as(users.owner,'select public.moderation_case($1) value',[id])).rows[0].value;assert.equal(core.summary.current_revision,await hash(id));assert.equal(core.summary.owner_controls,true);assert.ok(!JSON.stringify(core).includes('automatic_trace'));assert.ok(!JSON.stringify((await dashboard('all')).items).includes('ai_calls'));await db.query("update public.listings set status='archived' where id=$1",[id]);assert.ok(!(await dashboard('technical')).items.some(x=>x.id===id));assert.ok(!(await dashboard('pending')).items.some(x=>x.id===id));});
 await t.test('exhausted system error can retry unchanged content; provider diagnostics persist only allowed codes',async()=>{
  const id=await make();await submit(id);const job=await claim();await db.query('update private.moderation_runs set attempts=3 where id=$1',[job.id]);await d.service('select public.fail_moderation_job($1,$2)',[job.id,job.claim_token]);const rev=await hash(id);
  await as(users.seller,"select public.owner_listing_transition($1,'edit')",[id]);await submit(id);const retried=await claim();assert.notEqual(retried.id,job.id);assert.equal(retried.content_revision_hash,rev);
  await d.record(retried,{provider:'openai',model:'gpt-5.6-luna',status:'ocr_incomplete',latency_ms:1,image_count:1,input_tokens:1,output_tokens:1,request_id:'req_fixture',validation_issue:'ocr_incomplete',raw_ocr:'TEST 4242 4242 4242 4242'});
  const calls=(await db.query('select ai_calls from private.moderation_runs where id=$1',[retried.id])).rows[0].ai_calls;assert.equal(calls[0].validation_issue,'ocr_incomplete');assert.ok(!JSON.stringify(calls).includes('4242'));
 });
 }finally{await db.close();}
});
