// Isolated compiled-Worker UI verification, never attaches to a real account.
import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';import {testBrowser,delay} from './helpers/browser.mjs';
const phase=process.env.PHASE??'after',base='http://127.0.0.1:4188',b=await testBrowser({output:'artifacts/moderation-reliability'});const timings={},errors=[],responsive=[],feedbackFrames=[],heaps=[];let documents=0;
b.on('Network.requestWillBeSent',e=>{if(e.type==='Document')documents++;});b.on('Runtime.exceptionThrown',e=>errors.push(e.exceptionDetails.text));
async function click(selector,ready){const start=performance.now();await b.evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);if(phase==='after'&&selector.includes('nav[')){const ms=await b.evaluate(`new Promise(resolve=>{const start=performance.now();requestAnimationFrame(()=>resolve({ms:performance.now()-start,visible:document.querySelector('.moderation-load-status')?.textContent.includes('Загружаем')}));})`);if(ms.visible){feedbackFrames.push(ms.ms);assert.ok(ms.ms<100);}}await b.until(ready);return Math.round(performance.now()-start);}
async function renderedText(){return b.evaluate(`(()=>{const copy=document.querySelector('main').cloneNode(true);copy.querySelectorAll('details:not([open])').forEach(d=>{const s=d.querySelector('summary')?.textContent;d.textContent=s||'';});return copy.innerText||copy.textContent;})()`);}
try{
 await b.send('Fetch.enable',{patterns:[{urlPattern:'https://*.supabase.co/*'}]});b.on('Fetch.requestPaused',async x=>{const r=await fetch(base+'/__fixture/upstream?url='+encodeURIComponent(x.request.url));await b.send('Fetch.fulfillRequest',{requestId:x.requestId,responseCode:r.status,responseHeaders:[{name:'Content-Type',value:'application/json'},{name:'Access-Control-Allow-Origin',value:'*'}],body:Buffer.from(await r.arrayBuffer()).toString('base64')});});
 await b.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});const start=performance.now();await b.send('Page.navigate',{url:base+'/admin'});await b.until('!!document.querySelector(".moderation-row")');await delay(300);timings.first_render_ms=Math.round(performance.now()-start)-300;
 timings.filter_ms=await click('nav[aria-label="Фильтры модерации"] a[href="/admin?filter=technical"]','location.search.includes("technical") && !!document.querySelector(".moderation-row")');await delay(200);
 timings.other_filter_ms=await click('nav[aria-label="Фильтры модерации"] a[href="/admin?filter=all"]','location.search.includes("all") && !!document.querySelector(".moderation-row")');await delay(150);
 timings.cached_filter_ms=await click('nav[aria-label="Фильтры модерации"] a[href="/admin?filter=technical"]','location.search.includes("technical") && !!document.querySelector(".moderation-row")');await delay(150);
 timings.detail_ms=await click('.moderation-actions a','!!document.querySelector(".moderation-case")');await delay(200);
 if(phase==='after'){
  const info=await(await fetch(base+'/__fixture/info')).json();assert.equal(info.calls.filter(x=>x.endsWith('/get_listing_moderation')).length,0,'history is not prefetched with rows/core');
  timings.trace_ms=await click('.moderation-audit > summary','!!document.querySelector(".moderation-audit ol")');
  const text=await renderedText();assert.doesNotMatch(text,/\b(PENDING|AUTO_UNCERTAIN|AUTO_APPROVED|AUTO_REJECTED|AUTOMATIC|technical_hold|FINAL DECISION|Content revision|Ruleset|Lexical|NO_TEXT_RISK|SUBMITTED|LOCAL_RULES|IMAGE_VALIDATION|AI_ANALYSIS|VISION|OCR|RULE_EVALUATION|FINAL_DECISION|PASS|FAILED|FINDING|SKIPPED|UNCERTAIN|invalid_schema)\b/);
  for(const [name,width,height] of [['iphone-portrait',390,844],['iphone-landscape',844,390],['android',412,915]]){
   await b.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:true});
   const sizes=await b.evaluate(`(()=>{const buttons=[...document.querySelectorAll('.moderation-decision-actions button')].map(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height}));return {width:innerWidth,scroll:document.documentElement.scrollWidth,buttons,padding:parseFloat(getComputedStyle(document.querySelector('.moderation-workspace')).paddingBottom)}})()`);
   assert.ok(sizes.scroll<=sizes.width+1,JSON.stringify(sizes));assert.equal(new Set(sizes.buttons.map(x=>x.width)).size,1);assert.equal(new Set(sizes.buttons.map(x=>x.height)).size,1);assert.ok(sizes.buttons.every(x=>x.height>=44));assert.ok(sizes.padding>=90);responsive.push({name,...sizes});
  }
  await b.evaluate("document.querySelector('.moderator-action-approve').click()");await b.until('!!document.querySelector(".moderation-action-form")');assert.equal(await b.evaluate('document.querySelector(".moderation-action-form select")===null'),true);assert.equal(await b.evaluate('document.querySelector(".moderation-action-form textarea").required'),false);
  await fetch(base+'/__fixture/fail?on=true');await b.evaluate("document.querySelector('.moderation-action-form button[type=submit]').click()");await b.until('document.querySelector(".moderation-decision [role=status]")?.textContent.match(/Обновите|другой модератор/)');assert.notEqual(await b.evaluate('document.querySelector(".moderation-current-status").textContent'),'Опубликовано');await fetch(base+'/__fixture/fail?on=false');
  await fetch(base+'/__fixture/reset');await b.evaluate("document.querySelector('.moderation-action-form button[type=submit]').click();document.querySelector('.moderation-action-form button[type=submit]').click()");await b.until('document.querySelector(".moderation-current-status")?.textContent==="Опубликовано"');const actions=(await(await fetch(base+'/__fixture/info')).json()).calls.filter(p=>p.endsWith('/moderate_listing_checked'));assert.equal(actions.length,1);assert.match(await b.evaluate('document.querySelector(".moderation-final-status").textContent'),/модератором/);
  for(const action of ['reject','needs_fix']){await b.evaluate(`document.querySelector('.moderation-decision-actions .moderator-action-${action}').click()`);assert.equal(await b.evaluate('document.querySelector(".moderation-action-form select").required'),true);assert.equal(await b.evaluate('document.querySelector(".moderation-action-form textarea").required'),true);assert.ok(await b.evaluate('parseFloat(getComputedStyle(document.querySelector("textarea")).fontSize)>=16'));await b.evaluate("document.querySelector('.moderation-action-form .text-button').click()");}
  await b.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await b.evaluate('window.scrollTo(0,document.documentElement.scrollHeight)');await writeFile('artifacts/moderation-reliability/mobile.png',Buffer.from((await b.send('Page.captureScreenshot',{format:'png'})).data,'base64'));
  // Back/forward keeps the same document and bounded in-memory view cache.
  const origin=await b.evaluate('performance.timeOrigin');for(let i=0;i<12;i++){await b.evaluate('history.back()');await b.until('!!document.querySelector(".moderation-row")');await click('.moderation-actions a','!!document.querySelector(".moderation-case")');if([3,7,11].includes(i)){await b.send('HeapProfiler.collectGarbage');heaps.push((await b.send('Runtime.getHeapUsage')).usedSize);}}
  assert.equal(await b.evaluate('performance.timeOrigin'),origin);await b.send('HeapProfiler.collectGarbage');timings.final_heap_bytes=(await b.send('Runtime.getHeapUsage')).usedSize;assert.equal(documents,1);assert.ok(heaps.at(-1)<=heaps[0]+4*1024*1024,JSON.stringify(heaps));
 }
 assert.deepEqual(errors,[]);await writeFile(`artifacts/moderation-reliability/browser-${phase}.json`,JSON.stringify({phase,environment:'compiled Worker; synthetic authenticated owner; 120ms per upstream request; Chromium responsive emulation (not physical Safari)',timings,responsive,feedbackFrames,heaps,documents,errors},null,2));console.log(JSON.stringify({phase,timings,documents,errors}));
}catch(e){console.log(JSON.stringify({phase,timings,feedback:await b.evaluate('document.querySelector(".moderation-decision [role=status]")?.textContent'),failure:e.message}));throw e;}finally{await b.close();}
