import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {OpenAIModerationProvider} from '../lib/moderation/openai-provider.ts';import {AIProviderError,validateObservations} from '../lib/moderation/ai-contract.ts';
import {moderate} from '../lib/moderation/engine.ts';import {evaluateAutomatic} from '../lib/moderation/automatic.ts';import {executeShadow} from '../lib/moderation/ai-execution.ts';
import {UnavailableAIProvider,UnavailableOCRProvider} from '../lib/moderation/providers.ts';import {loadRules} from '../scripts/moderation-benchmark.mjs';import {lexicalConfigs} from '../lib/moderation/rulesets/lexical-v2.ts';
import {cleanObservation,observation,responseBody} from './helpers/moderation-ai-fixtures.mjs';
const rules=(await loadRules()).map(r=>({...r,ruleset_version:'kz-policy-2026-09-26.3',scope:['text','image','ocr'],config:{...r.config,lexical:lexicalConfigs[r.code]}}));
const jpg=await readFile('tests/moderation/benchmark/v1/images/phone.jpg');const metadata={provider:'openai',model:'fixture',schema_version:'moderation-ai-observation-v2',status:'success',image_count:1,latency_ms:1};
const switches={enabled:true,approval:true,rejection:true};
const run=async(o,title='Обычный планшет',description='Обычный товар в хорошем состоянии.')=>{const base=await moderate({snapshot:{title,description,category_path:[{slug:'other',ru:'Техника',kk:'Техника'}],attributes:[],images:[{storage_key:'fixture.jpg'}]},rules,fraud:{recent_submissions:0,prior_rejections:0,confirmed_reports:0,duplicate_content:0,reused_images:0},ai:new UnavailableAIProvider(),ocr:new UnavailableOCRProvider(),loadImage:async()=>jpg,allowExternal:false,lexicalAIState:'READY'});return evaluateAutomatic({base,rules,response:{observations:o,metadata},providerStatus:'success',switches});};
for(const title of ['Планшет: задняя сторона без надписей','Телевизор с видео телефона на экране','Планшет с обычным интерфейсом','Телефон с обычным интерфейсом','Ноутбук с рабочим столом','Обычный автомобиль'])test('clean object and no OCR text: '+title,async()=>{const o=cleanObservation();o.image_subjects[0].object_type=title.includes('автомобиль')?'vehicle':'other';const r=await run(o,title);assert.equal(r.result.decision,'APPROVED');assert.equal(r.trace.ocr[0].ocr_status,'NO_TEXT_DETECTED');assert.equal(r.result.stages.every(s=>s.status==='PASS'),true);});
test('partial harmless brand/packaging/UI is sufficient; no blanket missing-text uncertainty',async()=>{const o=cleanObservation();o.visible_text[0]={image_index:0,text:'Brand',ocr_status:'PARTIAL_TEXT',moderation_relevance:'none'};const r=await run(o);assert.equal(r.result.decision,'APPROVED');assert.equal(r.trace.ocr[0].ocr_status,'PARTIAL_TEXT');assert.ok(!JSON.stringify(r).includes('Brand'));});
test('partial suspicious writing goes to review, never auto approval',async()=>{const o=cleanObservation();o.visible_text[0]={image_index:0,text:'',ocr_status:'PARTIAL_TEXT',moderation_relevance:'possible_risk'};const r=await run(o);assert.equal(r.result.decision,'HUMAN_REVIEW');assert.equal(r.trace.basis,'uncertain');assert.ok(r.result.findings.some(f=>f.finding_code==='ocr_partial_risk'));});
test('readable synthetic card text on screen still needs repair and is not persisted',async()=>{const o=cleanObservation();o.visible_text[0]={image_index:0,text:'TEST CARD 4242 4242 4242 4242',ocr_status:'TEXT_READ',moderation_relevance:'possible_risk'};const r=await run(o);assert.equal(r.result.decision,'NEEDS_FIX');assert.ok(r.result.findings.some(f=>f.source_type==='ocr'&&f.finding_code==='payment_card'));assert.doesNotMatch(JSON.stringify(r),/4242/);});
test('document on a screen is not exempt from privacy analysis',async()=>{const o=cleanObservation();o.image_observations=[observation('possible_identity_document','image',0,'background')];assert.equal((await run(o)).result.decision,'NEEDS_FIX');});
test('meaningful prohibited offer on a screen is still evaluated by rules',async()=>{const o=cleanObservation();o.image_observations=[observation('possible_vape','image',0,'offered_item')];o.visible_text[0]={image_index:0,text:'Продам вейп',ocr_status:'TEXT_READ',moderation_relevance:'possible_risk'};assert.equal((await run(o)).result.decision,'REJECTED');});
test('unsafe observation remains effective even if OCR says no writing',async()=>{const o=cleanObservation();o.image_observations=[observation('possible_payment_card')];assert.equal((await run(o)).result.decision,'NEEDS_FIX');});
test('provider and local contract agree: empty text succeeds, invalid state/coverage/provenance fails',async()=>{let schema;const p=new OpenAIModerationProvider({key:'mock-only',model:'fixture',fetch:async(_u,init)=>{schema=JSON.parse(init.body).text.format.schema;return Response.json(responseBody(cleanObservation()));}});await p.analyzeListing({title:'Tablet',description:'Synthetic',category:'Devices',attributes:'[]',images:[{image_index:0,bytes:jpg,mimeType:'image/jpeg'}]},new AbortController().signal);assert.deepEqual(schema.properties.visible_text.items.required,['image_index','text','ocr_status','moderation_relevance']);for(const patch of [{text:'secret'}, {ocr_status:'UNKNOWN'}, {ocr_status:'TEXT_READ'}, {image_index:1}]){const o=cleanObservation();Object.assign(o.visible_text[0],patch);assert.throws(()=>validateObservations(o,[0]),e=>e.code==='invalid_schema');}});
test('OCR technical error retries at most twice and stays technical hold',async()=>{let calls=0,reservations=0;const base=(await run(cleanObservation())).result;const p=new OpenAIModerationProvider({key:'mock-only',model:'fixture',fetch:async()=>{calls++;const o=cleanObservation();o.visible_text[0].ocr_status='TECHNICAL_FAILURE';return Response.json(responseBody(o));}});const shadow=await executeShadow({provider:p,data:{title:'Tablet',description:'Synthetic',category:'Devices',attributes:'[]',images:[{image_index:0,bytes:jpg,mimeType:'image/jpeg'}]},base,rules,signal:new AbortController().signal,reserve:async()=>++reservations,record:async()=>{},sleep:async()=>{}});assert.equal(calls,2);assert.equal(shadow.status,'ocr_failure');const r=await evaluateAutomatic({base,rules,providerStatus:shadow.status,switches});assert.equal(r.result.decision,'HUMAN_REVIEW');assert.equal(r.trace.basis,'technical_hold');});
test('malformed/technical OCR never silently becomes NO_TEXT',async()=>{for(const status of ['invalid_schema','ocr_failure','timeout']){const r=await evaluateAutomatic({base:(await run(cleanObservation())).result,rules,providerStatus:status,switches});assert.equal(r.result.decision,'HUMAN_REVIEW');assert.equal(r.trace.basis,'technical_hold');}assert.throws(()=>validateObservations({...cleanObservation(),visible_text:[]},[0]),AIProviderError);});

test('ordinary screen labels are not local identifiers, while a card embedded in the same UI remains actionable',async()=>{
 const normal=cleanObservation();normal.visible_text[0]={image_index:0,text:'GamePlayer42 https://example.invalid 28°C Friday 11 Notes',ocr_status:'PARTIAL_TEXT',moderation_relevance:'none'};
 assert.equal((await run(normal)).result.decision,'APPROVED');
 const risky=structuredClone(normal);risky.visible_text[0].text+=' TEST CARD 4242 4242 4242 4242';risky.visible_text[0].moderation_relevance='possible_risk';
 const result=await run(risky);assert.notEqual(result.result.decision,'APPROVED');assert.ok(result.result.findings.some(f=>f.finding_code==='payment_card'));assert.doesNotMatch(JSON.stringify(result),/4242/);
 const flagged=structuredClone(normal);flagged.image_observations=[{...observation('possible_personal_identifier','image',0,'background'),confidence:.78}];
 const unconfirmed=await run(flagged);assert.equal(unconfirmed.result.decision,'APPROVED');assert.equal(unconfirmed.trace.observations[0].code,'possible_personal_identifier','Unconfirmed hypothesis remains auditable');
 flagged.visible_text[0].moderation_relevance='possible_risk';assert.equal((await run(flagged)).result.decision,'HUMAN_REVIEW','Risky unreadable context must not be ignored');
});

test('identifier confirmation is content-independent and preserves document, payment and local privacy evidence',async()=>{
 for(const ocrStatus of ['NO_TEXT_DETECTED','TEXT_READ','PARTIAL_TEXT']){
  const safe=cleanObservation();safe.image_observations=[observation('possible_personal_identifier','image',0,'background')];safe.visible_text[0]={image_index:0,text:ocrStatus==='NO_TEXT_DETECTED'?'':'ordinary letters',ocr_status:ocrStatus,moderation_relevance:'none'};
  const result=await run(safe,'Обычный товар');assert.equal(result.result.decision,'APPROVED');assert.equal(result.trace.observations.length,1);
  for(const code of ['document_visible','possible_identity_document','possible_payment_card']){const unsafe=structuredClone(safe);unsafe.image_observations.push(observation(code,'image',0,'background'));assert.notEqual((await run(unsafe)).result.decision,'APPROVED');}
  const local=structuredClone(safe);local.visible_text[0]={image_index:0,text:'TEST CARD 4242 4242 4242 4242',ocr_status:'TEXT_READ',moderation_relevance:'none'};const blocked=await run(local);assert.equal(blocked.result.decision,'NEEDS_FIX');assert.doesNotMatch(JSON.stringify(blocked),/4242/);
  const document=structuredClone(safe);document.image_subjects[0].object_type='document';assert.notEqual((await run(document)).result.decision,'APPROVED');
 }
});
