import {AppLink as Link} from '@/components/app-link';
import {DashboardShell} from '@/components/dashboard-shell';import {ModerationAdminAction,ModerationRuleEditor} from '@/components/moderation-admin-tools';import {requireModerationPageAccess} from '@/lib/auth/moderation-access';import {createSupabaseServerClient} from '@/lib/supabase/server';import {getServerI18n} from '@/lib/i18n/server';
import type {Json} from '@/lib/supabase/database.types';
type Queue={appeals:{id:string;listing_id:string;message:string}[];reports:{id:string;listing_id:string;reason_code:string;details:string|null}[];metrics:Json};
export const metadata={title:'JEVU — модерация',robots:{index:false,follow:false}};
export default async function Page(){const context=await requireModerationPageAccess('/admin/moderation'),{locale}=await getServerI18n(),client=await createSupabaseServerClient();const queue=await client.rpc('moderation_admin',{operation:'queue'}),rules=await client.rpc('moderation_admin',{operation:'view'});const q=queue.data as unknown as Queue|null;
 return <DashboardShell title={locale==='kk'?'Шағымдар және модерация ережелері':'Жалобы и правила модерации'} description={locale==='kk'?'Қолмен тексеру және ережелерді басқару':'Ручная проверка и управление правилами'} active="/admin" authContext={context} fallback="/admin"><Link href="/admin">{locale==='kk'?'Тексеру кезегі':'Очередь проверки'}</Link>
 {queue.error?<p>{locale==='kk'?'Кезек қолжетімсіз':'Очередь недоступна'}</p>:<><h2>{locale==='kk'?'Апелляциялар':'Апелляции'}</h2>{q?.appeals.map(a=><section className="dashboard-card" key={a.id}><Link href={`/admin/${a.listing_id}`}>{a.listing_id}</Link><p>{a.message}</p><ModerationAdminAction action="resolve_appeal" id={a.id} label={locale==='kk'?'Өтінішті қарау':'Рассмотреть обращение'}/></section>)}<h2>{locale==='kk'?'Шағымдар':'Жалобы'}</h2>{q?.reports.map(r=><section className="dashboard-card" key={r.id}><Link href={`/admin/${r.listing_id}`}>{r.reason_code}</Link><p>{r.details}</p><ModerationAdminAction action="resolve_report" id={r.id} label={locale==='kk'?'Шағымды қарау':'Рассмотреть жалобу'}/></section>)}<details><summary>{locale==='kk'?'Көрсеткіштер':'Метрики'}</summary><pre>{JSON.stringify(q?.metrics,null,2)}</pre></details></>}
 {!rules.error?<><ModerationRuleEditor/><details><summary>{locale==='kk'?'Ережелер, құқықтық негіздер және өзгерістер':'Правила, правовые основания и история изменений'}</summary><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(rules.data,null,2)}</pre></details></>:null}</DashboardShell>;
}
