import { passengerVehicleBrands } from "./vehicle-brands.ts";
import {
  motorcycleBrands,
  motorcycleModels,
  passengerVehicleModels,
  smartphoneBrands,
  smartphoneModels,
  type DependentReferenceOption,
} from "./dependent-options.ts";
import { ereaderBrands, ereaderModels, tabletBrands, tabletModels } from "./device-options.ts";
import { masterCatalogProfileAssignments } from "./master-catalog/index.ts";
import { passengerVehicleModelsByBody } from "./vehicle-body-models.ts";

export type SeedLocalizedText = { ru: string; kk: string };
export type SeedFilterMode = "exact" | "range" | "search";
export type SeedOptionsLoadMode = "eager" | "deferred";
export type SeedAttributeOption = {
  value: string;
  label: SeedLocalizedText;
  parentValue?: string;
};
export type SeedAttributeDefinition = {
  key: string;
  label: SeedLocalizedText;
  dataType: "text" | "number" | "boolean" | "select" | "multiselect" | "range" | "date";
  unit?: SeedLocalizedText;
  required?: boolean;
  filterable?: boolean;
  searchable?: boolean;
  filterMode?: SeedFilterMode;
  optionsLoadMode?: SeedOptionsLoadMode;
  dependsOnKey?: string;
  validation?: Record<string, unknown>;
  options?: SeedAttributeOption[];
};

const tx = (ru: string, kk: string): SeedLocalizedText => ({ ru, kk });
const op = (value: string, ru: string, kk: string = ru): SeedAttributeOption => ({ value, label: tx(ru, kk) });
const select = (
  key: string,
  ru: string,
  kk: string,
  options: SeedAttributeOption[],
  config: Partial<SeedAttributeDefinition> = {},
): SeedAttributeDefinition => ({ key, label: tx(ru, kk), dataType: "select", filterable: true, filterMode: "exact", options, ...config });
const text = (key: string, ru: string, kk: string, config: Partial<SeedAttributeDefinition> = {}): SeedAttributeDefinition =>
  ({ key, label: tx(ru, kk), dataType: "text", ...config });
const number = (key: string, ru: string, kk: string, unitRu?: string, unitKk?: string, config: Partial<SeedAttributeDefinition> = {}): SeedAttributeDefinition =>
  ({ key, label: tx(ru, kk), dataType: "number", unit: unitRu && unitKk ? tx(unitRu, unitKk) : undefined, filterable: true, filterMode: "range", ...config });
const bool = (key: string, ru: string, kk: string, config: Partial<SeedAttributeDefinition> = {}): SeedAttributeDefinition =>
  ({ key, label: tx(ru, kk), dataType: "boolean", filterable: true, filterMode: "exact", ...config });
const date = (key: string, ru: string, kk: string, config: Partial<SeedAttributeDefinition> = {}): SeedAttributeDefinition =>
  ({ key, label: tx(ru, kk), dataType: "date", filterable: true, filterMode: "range", ...config });

const CONDITION = select("condition", "Состояние", "Күйі", [
  op("new", "Новое", "Жаңа"), op("like-new", "Как новое", "Жаңа сияқты"),
  op("used", "Б/у", "Қолданылған"), op("repair", "Требует ремонта", "Жөндеуді қажет етеді"),
], { required: true });
const BRAND_TEXT = text("brand", "Бренд", "Бренд", { filterable: true, searchable: true, filterMode: "search", validation: { maxLength: 80 } });
const MODEL_TEXT = text("model", "Модель", "Модель", { filterable: true, searchable: true, filterMode: "search", validation: { maxLength: 100 } });
const YEAR = number("year", "Год выпуска", "Шығарылған жылы", "год", "жыл", { validation: { min: 1900, max: 2100 } });
const WARRANTY = select("warranty", "Гарантия", "Кепілдік", [op("none", "Нет", "Жоқ"), op("seller", "От продавца", "Сатушыдан"), op("manufacturer", "От производителя", "Өндірушіден")]);
const DELIVERY = bool("delivery", "Есть доставка", "Жеткізу бар");

const PASSENGER_BRANDS: SeedAttributeOption[] = passengerVehicleBrands;
const MOTORCYCLE_BRANDS: SeedAttributeOption[] = motorcycleBrands;
const SMARTPHONE_BRANDS: SeedAttributeOption[] = smartphoneBrands;
const dependentSelect = (
  key: string,
  ru: string,
  kk: string,
  dependsOnKey: string,
  options: DependentReferenceOption[],
  required = true,
): SeedAttributeDefinition => select(key, ru, kk, options, {
  required,
  dependsOnKey,
  optionsLoadMode: "deferred",
  validation: { fallbackOption: "other-model" },
});
const OTHER_MODEL = text("model_other", "Другая модель", "Басқа модель", {
  searchable: true,
  validation: { maxLength: 100, visibleWhen: { key: "model", values: ["other-model"] } },
});
const OTHER_COMPATIBLE_MODEL = text("compatible_model_other", "Другая совместимая модель", "Басқа үйлесімді модель", {
  searchable: true,
  validation: { maxLength: 100, visibleWhen: { key: "compatible_model", values: ["other-model"] } },
});

const passengerCarProfile = (
  models: DependentReferenceOption[] = passengerVehicleModels,
): SeedAttributeDefinition[] => [
  select("brand", "Марка", "Маркасы", PASSENGER_BRANDS, { required: true }),
  dependentSelect("model", "Модель", "Моделі", "brand", models), OTHER_MODEL,
  YEAR,
  number("mileage", "Пробег", "Жүрісі", "км", "км", { validation: { min: 0, max: 5_000_000 } }),
  select("transmission", "Коробка передач", "Беріліс қорабы", [op("automatic", "Автомат", "Автомат"), op("manual", "Механика", "Механика"), op("robot", "Робот", "Робот"), op("cvt", "Вариатор", "Вариатор")]),
  select("fuel", "Топливо", "Отын", [op("petrol", "Бензин", "Бензин"), op("diesel", "Дизель", "Дизель"), op("gas", "Газ", "Газ"), op("petrol-gas", "Бензин / газ", "Бензин / газ"), op("hybrid", "Гибрид", "Гибрид"), op("plugin-hybrid", "Plug-in hybrid", "Қуатталатын гибрид"), op("electric", "Электро", "Электр")]),
  select("drive", "Привод", "Жетек", [op("front", "Передний", "Алдыңғы"), op("rear", "Задний", "Артқы"), op("all", "Полный", "Толық")]),
  number("engine_volume", "Объём двигателя", "Қозғалтқыш көлемі", "л", "л", { validation: { min: 0.1, max: 20, step: 0.1 } }),
  select("steering", "Руль", "Руль", [op("left", "Слева", "Сол жақта"), op("right", "Справа", "Оң жақта")]),
  select("color", "Цвет", "Түсі", [op("black", "Чёрный", "Қара"), op("white", "Белый", "Ақ"), op("silver", "Серебристый", "Күміс"), op("gray", "Серый", "Сұр"), op("blue", "Синий", "Көк"), op("red", "Красный", "Қызыл"), op("green", "Зелёный", "Жасыл"), op("beige", "Бежевый", "Сарғыш"), op("brown", "Коричневый", "Қоңыр"), op("other", "Другой", "Басқа")]),
  select("condition", "Состояние автомобиля", "Автомобиль күйі", [op("new", "Новое", "Жаңа"), op("used", "С пробегом", "Жүрілген"), op("repair", "Требует ремонта", "Жөндеуді қажет етеді")], { required: true }),
];

const profiles = {
  goods: [CONDITION],
  goodsBrand: [BRAND_TEXT, MODEL_TEXT, CONDITION, WARRANTY],
  passengerCar: passengerCarProfile(),
  passengerCarSedan: passengerCarProfile(passengerVehicleModelsByBody.sedan),
  passengerCarSuv: passengerCarProfile(passengerVehicleModelsByBody.suv),
  passengerCarHatchback: passengerCarProfile(passengerVehicleModelsByBody.hatchback),
  passengerCarLiftback: passengerCarProfile(passengerVehicleModelsByBody.liftback),
  passengerCarWagon: passengerCarProfile(passengerVehicleModelsByBody.wagon),
  passengerCarMinivan: passengerCarProfile(passengerVehicleModelsByBody.minivan),
  passengerCarCoupe: passengerCarProfile(passengerVehicleModelsByBody.coupe),
  passengerCarCabriolet: passengerCarProfile(passengerVehicleModelsByBody.cabriolet),
  passengerCarPickup: passengerCarProfile(passengerVehicleModelsByBody.pickup),
  passengerCarOther: passengerCarProfile(passengerVehicleModelsByBody.other),
  motorcycle: [
    select("brand", "Марка", "Маркасы", MOTORCYCLE_BRANDS, { required: true }),
    dependentSelect("model", "Модель", "Моделі", "brand", motorcycleModels), OTHER_MODEL, YEAR,
    number("mileage", "Пробег", "Жүрісі", "км", "км", { validation: { min: 0 } }),
    number("engine_volume", "Объём двигателя", "Қозғалтқыш көлемі", "см³", "см³", { validation: { min: 25, max: 3000 } }),
    select("motorcycle_class", "Класс", "Сыныбы", [op("road", "Дорожный", "Жолдық"), op("sport", "Спортивный", "Спорттық"), op("touring", "Туристический", "Туристік"), op("cruiser", "Круизер", "Круизер"), op("enduro", "Эндуро", "Эндуро"), op("cross", "Кроссовый", "Кросс"), op("scooter", "Скутер", "Скутер"), op("atv", "Квадроцикл", "Квадроцикл"), op("snowmobile", "Снегоход", "Қар көлігі")]),
    select("condition", "Состояние", "Күйі", [op("new", "Новое", "Жаңа"), op("used", "С пробегом", "Жүрілген"), op("repair", "Требует ремонта", "Жөндеуді қажет етеді")], { required: true }),
    bool("documents", "Есть документы", "Құжаттары бар"),
  ],
  commercialVehicle: [BRAND_TEXT, MODEL_TEXT, YEAR, number("mileage", "Пробег", "Жүрісі", "км", "км"), select("fuel", "Топливо", "Отын", [op("diesel", "Дизель", "Дизель"), op("petrol", "Бензин", "Бензин"), op("gas", "Газ", "Газ"), op("electric", "Электро", "Электр")]), select("transmission", "Коробка передач", "Беріліс қорабы", [op("manual", "Механика", "Механика"), op("automatic", "Автомат", "Автомат"), op("robot", "Робот", "Робот")]), number("payload", "Грузоподъёмность", "Жүк көтерімділігі", "кг", "кг"), CONDITION],
  passengerCommercial: [number("seats", "Количество мест", "Орын саны", "мест", "орын", { validation: { min: 2, max: 100 } })],
  trailer: [select("trailer_type", "Тип прицепа", "Тіркеме түрі", [op("flatbed", "Бортовой", "Бортты"), op("curtain", "Тентованный", "Тентті"), op("refrigerator", "Рефрижератор", "Рефрижератор"), op("tipper", "Самосвальный", "Өзі түсіретін"), op("tank", "Цистерна", "Цистерна"), op("car", "Легковой", "Жеңіл көлікке"), op("other", "Другой", "Басқа")], { required: true }), YEAR, number("payload", "Грузоподъёмность", "Жүк көтерімділігі", "кг", "кг"), number("axles", "Количество осей", "Ось саны"), CONDITION],
  machinery: [select("machinery_type", "Тип техники", "Техника түрі", [op("excavator", "Экскаватор", "Экскаватор"), op("loader", "Погрузчик", "Тиегіш"), op("crane", "Кран", "Кран"), op("bulldozer", "Бульдозер", "Бульдозер"), op("grader", "Грейдер", "Грейдер"), op("tractor", "Трактор", "Трактор"), op("combine", "Комбайн", "Комбайн"), op("other", "Другая", "Басқа")]), BRAND_TEXT, MODEL_TEXT, YEAR, number("engine_hours", "Моточасы", "Мотосағат", "ч", "сағ"), number("power", "Мощность", "Қуаты", "л.с.", "а.к."), number("operating_weight", "Рабочая масса", "Жұмыс салмағы", "кг", "кг"), CONDITION],
  transportSimple: [BRAND_TEXT, MODEL_TEXT, YEAR, CONDITION],
  watercraft: [BRAND_TEXT, MODEL_TEXT, YEAR, number("length", "Длина", "Ұзындығы", "м", "м"), number("engine_power", "Мощность двигателя", "Қозғалтқыш қуаты", "л.с.", "а.к."), select("hull_material", "Материал корпуса", "Корпус материалы", [op("inflatable", "ПВХ / надувной", "ПВХ / үрлемелі"), op("aluminum", "Алюминий", "Алюминий"), op("fiberglass", "Стеклопластик", "Шыныпластик"), op("steel", "Сталь", "Болат"), op("wood", "Дерево", "Ағаш")]), CONDITION],
  aircraft: [BRAND_TEXT, MODEL_TEXT, YEAR, number("flight_hours", "Налёт", "Ұшу сағаттары", "ч", "сағ"), number("seats", "Количество мест", "Орын саны"), bool("airworthiness", "Есть документы лётной годности", "Ұшуға жарамдылық құжаттары бар"), CONDITION],
  electricPersonalTransport: [BRAND_TEXT, MODEL_TEXT, number("motor_power", "Мощность", "Қуаты", "Вт", "Вт"), number("range", "Запас хода", "Жүріс қоры", "км", "км"), number("max_speed", "Максимальная скорость", "Ең жоғары жылдамдық", "км/ч", "км/сағ"), CONDITION],

  autoPart: [select("part_type", "Тип детали", "Бөлшек түрі", [op("original", "Оригинальная", "Түпнұсқа"), op("analogue", "Аналог", "Баламасы"), op("used-original", "Оригинальная Б/у", "Қолданылған түпнұсқа")], { required: true }), BRAND_TEXT, text("part_number", "OEM / артикул", "OEM / артикул", { searchable: true }), select("compatible_brand", "Совместимая марка", "Үйлесімді марка", PASSENGER_BRANDS), dependentSelect("compatible_model", "Совместимая модель", "Үйлесімді модель", "compatible_brand", passengerVehicleModels, false), OTHER_COMPATIBLE_MODEL, select("position", "Сторона / позиция", "Жағы / орны", [op("front", "Передняя", "Алдыңғы"), op("rear", "Задняя", "Артқы"), op("left", "Левая", "Сол"), op("right", "Правая", "Оң"), op("universal", "Универсальная", "Әмбебап")]), CONDITION],
  tires: [select("product_type", "Тип", "Түрі", [op("tire", "Шины", "Шина"), op("wheel", "Диски", "Диск"), op("set", "Колёса в сборе", "Жинақталған дөңгелек")], { required: true }), select("season", "Сезон", "Маусым", [op("summer", "Летние", "Жазғы"), op("winter", "Зимние", "Қысқы"), op("all-season", "Всесезонные", "Барлық маусымдық")]), number("tire_width", "Ширина", "Ені", "мм", "мм"), number("tire_profile", "Профиль", "Профиль", "%", "%"), number("diameter", "Диаметр", "Диаметрі", "R", "R"), text("load_index", "Индекс нагрузки", "Жүктеме индексі"), number("quantity", "Количество", "Саны", "шт.", "дана"), BRAND_TEXT, CONDITION],
  wheels: [select("wheel_type", "Тип диска", "Диск түрі", [op("alloy", "Литой", "Құйма"), op("steel", "Штампованный", "Штампталған"), op("forged", "Кованый", "Соғылған")], { required: true }), number("diameter", "Диаметр", "Диаметрі", "R", "R"), number("width", "Ширина", "Ені", "J", "J"), text("bolt_pattern", "Разболтовка", "Болт үлгісі", { filterable: true, filterMode: "search" }), number("offset", "Вылет", "Шығуы", "ET", "ET"), BRAND_TEXT, CONDITION],
  fluids: [select("product_type", "Тип продукта", "Өнім түрі", [op("engine-oil", "Моторное масло", "Мотор майы"), op("transmission-oil", "Трансмиссионное масло", "Трансмиссия майы"), op("antifreeze", "Антифриз", "Антифриз"), op("brake-fluid", "Тормозная жидкость", "Тежегіш сұйықтығы"), op("other", "Другое", "Басқа")], { required: true }), BRAND_TEXT, text("viscosity", "Вязкость", "Тұтқырлығы", { filterable: true, filterMode: "search" }), number("volume", "Объём", "Көлемі", "л", "л"), text("approval", "Допуски / назначение", "Рұқсаттары / мақсаты", { searchable: true })],

  flatSale: [select("rooms", "Количество комнат", "Бөлме саны", [op("studio", "Студия", "Студия"), op("1", "1", "1"), op("2", "2", "2"), op("3", "3", "3"), op("4", "4", "4"), op("5+", "5 и больше", "5 және одан көп")], { required: true }), number("total_area", "Общая площадь", "Жалпы ауданы", "м²", "м²", { required: true }), number("living_area", "Жилая площадь", "Тұрғын ауданы", "м²", "м²"), number("kitchen_area", "Площадь кухни", "Асүй ауданы", "м²", "м²"), number("floor", "Этаж", "Қабат", undefined, undefined, { required: true }), number("floors_total", "Этажность дома", "Үй қабаттылығы"), YEAR, select("building_type", "Тип дома", "Үй түрі", [op("brick", "Кирпичный", "Кірпіш"), op("panel", "Панельный", "Панельді"), op("monolith", "Монолитный", "Монолитті"), op("other", "Другой", "Басқа")]), select("renovation", "Ремонт", "Жөндеу", [op("none", "Без ремонта", "Жөндеусіз"), op("cosmetic", "Косметический", "Косметикалық"), op("good", "Хороший", "Жақсы"), op("designer", "Дизайнерский", "Дизайнерлік")]), select("bathroom", "Санузел", "Санитарлық торап", [op("combined", "Совмещённый", "Біріктірілген"), op("separate", "Раздельный", "Бөлек"), op("multiple", "Два и больше", "Екі және одан көп")]), select("balcony", "Балкон / лоджия", "Балкон / лоджия", [op("none", "Нет", "Жоқ"), op("balcony", "Балкон", "Балкон"), op("loggia", "Лоджия", "Лоджия"), op("both", "Балкон и лоджия", "Балкон және лоджия")]), select("market", "Рынок жилья", "Тұрғын үй нарығы", [op("new", "Новостройка", "Жаңа құрылыс"), op("secondary", "Вторичное жильё", "Қайталама тұрғын үй")]), bool("mortgage", "Подходит под ипотеку", "Ипотекаға жарайды")],
  rentTerms: [select("rental_period", "Срок аренды", "Жалдау мерзімі", [op("monthly", "Помесячно", "Ай сайын"), op("long", "Долгосрочно", "Ұзақ мерзімге")]), number("deposit", "Залог", "Кепілақы", "₸", "₸"), select("utilities", "Коммунальные услуги", "Коммуналдық төлемдер", [op("included", "Включены", "Кірістірілген"), op("separate", "Оплачиваются отдельно", "Бөлек төленеді"), op("partial", "Частично включены", "Ішінара кірістірілген")]), bool("furnished", "С мебелью", "Жиһазбен"), bool("appliances", "С бытовой техникой", "Тұрмыстық техникамен"), bool("children_allowed", "Можно с детьми", "Балалармен болады"), bool("pets_allowed", "Можно с животными", "Жануарлармен болады")],
  dailyTerms: [number("guests", "Количество гостей", "Қонақ саны"), select("sleeping_places", "Спальных мест", "Жатын орын", [op("1", "1", "1"), op("2", "2", "2"), op("3", "3", "3"), op("4", "4", "4"), op("5+", "5 и больше", "5 және одан көп")]), bool("instant_booking", "Мгновенное бронирование", "Жедел брондау"), bool("documents", "Отчётные документы", "Есептік құжаттар")],
  house: [number("house_area", "Площадь дома", "Үй ауданы", "м²", "м²", { required: true }), number("land_area", "Площадь участка", "Жер телімінің ауданы", "сот.", "сот."), number("floors_total", "Этажность", "Қабат саны"), select("wall_material", "Материал стен", "Қабырға материалы", [op("brick", "Кирпич", "Кірпіш"), op("block", "Газоблок / пеноблок", "Газоблок / пеноблок"), op("wood", "Дерево", "Ағаш"), op("panel", "Панель", "Панель"), op("other", "Другой", "Басқа")]), YEAR, select("renovation", "Состояние / ремонт", "Күйі / жөндеуі", [op("rough", "Черновая отделка", "Қара сылақ"), op("repair", "Требует ремонта", "Жөндеуді қажет етеді"), op("good", "Хорошее", "Жақсы"), op("excellent", "Отличное", "Өте жақсы")]), select("heating", "Отопление", "Жылыту", [op("central", "Центральное", "Орталық"), op("gas", "Газовое", "Газбен"), op("solid", "Твёрдое топливо", "Қатты отын"), op("electric", "Электрическое", "Электрлік")]), bool("water", "Вода", "Су бар"), bool("sewerage", "Канализация", "Кәріз бар"), bool("gas", "Газ", "Газ бар"), bool("garage", "Гараж", "Гараж бар")],
  room: [number("room_area", "Площадь комнаты", "Бөлме ауданы", "м²", "м²", { required: true }), number("rooms_total", "Комнат в квартире / доме", "Пәтердегі / үйдегі бөлме саны"), number("floor", "Этаж", "Қабат"), bool("furnished", "С мебелью", "Жиһазбен"), select("renovation", "Состояние", "Күйі", [op("repair", "Требует ремонта", "Жөндеуді қажет етеді"), op("good", "Хорошее", "Жақсы"), op("excellent", "Отличное", "Өте жақсы")])],
  land: [number("land_area", "Площадь участка", "Жер телімінің ауданы", "сот.", "сот.", { required: true }), select("land_purpose", "Назначение", "Мақсаты", [op("housing", "ИЖС", "Жеке тұрғын үй"), op("farm", "Крестьянское хозяйство", "Шаруа қожалығы"), op("garden", "Садоводство", "Бағбандық"), op("commercial", "Коммерческое", "Коммерциялық"), op("other", "Другое", "Басқа")], { required: true }), bool("electricity", "Электричество", "Электр бар"), bool("water", "Вода", "Су бар"), bool("gas", "Газ", "Газ бар"), select("access_road", "Подъезд", "Кірме жол", [op("asphalt", "Асфальт", "Асфальт"), op("gravel", "Грунтовая дорога", "Топырақ жол"), op("none", "Нет дороги", "Жол жоқ")])],
  commercialProperty: [select("commercial_type", "Тип объекта", "Нысан түрі", [op("office", "Офис", "Кеңсе"), op("retail", "Магазин", "Дүкен"), op("warehouse", "Склад", "Қойма"), op("production", "Производство", "Өндіріс"), op("catering", "Общепит", "Қоғамдық тамақтану"), op("free", "Свободного назначения", "Еркін мақсаттағы")], { required: true }), number("total_area", "Площадь", "Ауданы", "м²", "м²", { required: true }), number("floor", "Этаж", "Қабат"), bool("separate_entrance", "Отдельный вход", "Жеке кіреберіс"), select("renovation", "Состояние", "Күйі", [op("rough", "Без отделки", "Әрлеусіз"), op("good", "Хорошее", "Жақсы"), op("excellent", "Отличное", "Өте жақсы")]), bool("parking", "Парковка", "Тұрақ бар"), bool("utilities", "Коммуникации", "Коммуникациялар бар")],
  garage: [select("garage_type", "Тип", "Түрі", [op("garage", "Гараж", "Гараж"), op("parking", "Парковочное место", "Тұрақ орны"), op("box", "Бокс", "Бокс")], { required: true }), number("total_area", "Площадь", "Ауданы", "м²", "м²"), select("material", "Материал", "Материалы", [op("brick", "Кирпич", "Кірпіш"), op("metal", "Металл", "Металл"), op("concrete", "Бетон", "Бетон")]), bool("electricity", "Электричество", "Электр бар"), bool("pit", "Смотровая яма", "Қарау шұңқыры бар")],

  job: [number("salary_from", "Зарплата от", "Жалақы, бастап", "₸", "₸"), number("salary_to", "Зарплата до", "Жалақы, дейін", "₸", "₸"), select("pay_period", "Период оплаты", "Төлем кезеңі", [op("month", "В месяц", "Айына"), op("week", "В неделю", "Аптасына"), op("shift", "За смену", "Ауысымға"), op("hour", "За час", "Сағатына")], { required: true }), select("employment", "Тип занятости", "Жұмыс түрі", [op("full", "Полная", "Толық"), op("part", "Частичная", "Ішінара"), op("temporary", "Временная", "Уақытша"), op("internship", "Стажировка", "Тағылымдама")], { required: true }), select("schedule", "График", "Кесте", [op("5-2", "5/2", "5/2"), op("2-2", "2/2", "2/2"), op("shift", "Сменный", "Ауысымды"), op("rotation", "Вахта", "Вахта"), op("flexible", "Гибкий", "Икемді")]), select("experience", "Опыт", "Тәжірибе", [op("none", "Без опыта", "Тәжірибесіз"), op("1", "От 1 года", "1 жылдан"), op("3", "От 3 лет", "3 жылдан"), op("6", "От 6 лет", "6 жылдан")]), select("education", "Образование", "Білімі", [op("none", "Не требуется", "Қажет емес"), op("secondary", "Среднее", "Орта"), op("vocational", "Среднее специальное", "Арнаулы орта"), op("higher", "Высшее", "Жоғары")]), select("work_format", "Формат работы", "Жұмыс форматы", [op("onsite", "На месте", "Орнында"), op("remote", "Удалённо", "Қашықтан"), op("hybrid", "Гибридный", "Аралас")]), bool("accommodation", "Предоставляется проживание", "Тұратын орын беріледі")],

  serviceBase: [select("price_type", "Тип цены", "Баға түрі", [op("fixed", "Фиксированная", "Тұрақты"), op("from", "От указанной суммы", "Көрсетілген сомадан"), op("hour", "За час", "Сағатына"), op("agreement", "Договорная", "Келісімді")], { required: true }), select("service_format", "Формат", "Формат", [op("onsite", "На месте", "Орнында"), op("online", "Онлайн", "Онлайн"), op("both", "Онлайн и на месте", "Онлайн және орнында")]), bool("visit", "Выезд к клиенту", "Клиентке бару"), number("experience_years", "Опыт", "Тәжірибе", "лет", "жыл"), bool("urgent", "Срочный выезд", "Шұғыл бару"), select("service_guarantee", "Гарантия", "Кепілдік", [op("none", "Нет", "Жоқ"), op("up-to-month", "До месяца", "Бір айға дейін"), op("1-6-months", "1–6 месяцев", "1–6 ай"), op("6-12-months", "6–12 месяцев", "6–12 ай"), op("year-plus", "Год и больше", "Бір жыл және одан көп")])],
  repairService: [select("work_type", "Вид работ", "Жұмыс түрі", [op("consultation", "Консультация", "Кеңес"), op("diagnostics", "Диагностика", "Диагностика"), op("installation", "Монтаж", "Монтаж"), op("repair", "Ремонт", "Жөндеу"), op("turnkey", "Под ключ", "Толық аяқтау")]), select("object_type", "Тип объекта", "Нысан түрі", [op("flat", "Квартира", "Пәтер"), op("house", "Дом", "Үй"), op("office", "Офис", "Кеңсе"), op("commercial", "Коммерческое помещение", "Коммерциялық орын")]), bool("measurement", "Бесплатный замер", "Тегін өлшеу"), select("materials", "Материалы", "Материалдар", [op("customer", "Заказчика", "Тапсырыс берушінікі"), op("provider", "Исполнителя", "Орындаушыныкі"), op("both", "Оба варианта", "Екі нұсқа")])],
  transportService: [select("vehicle_type", "Тип транспорта", "Көлік түрі", [op("car", "Легковой", "Жеңіл"), op("van", "Фургон", "Фургон"), op("truck", "Грузовой", "Жүк көлігі"), op("special", "Спецтранспорт", "Арнайы көлік")]), number("payload", "Грузоподъёмность", "Жүк көтерімділігі", "кг", "кг"), number("loaders", "Количество грузчиков", "Жүк тиеушілер саны"), bool("intercity", "Межгород", "Қалааралық"), select("billing", "Расчёт", "Есептеу", [op("hour", "Почасовой", "Сағаттық"), op("fixed", "Фиксированный", "Тұрақты"), op("distance", "За километр", "Километрге")])],
  educationService: [text("subject", "Предмет / направление", "Пән / бағыт", { filterable: true, searchable: true, filterMode: "search", required: true }), select("student_level", "Уровень", "Деңгей", [op("preschool", "Дошкольный", "Мектепке дейінгі"), op("school", "Школьный", "Мектеп"), op("exam", "Экзамены", "Емтихандар"), op("university", "Вуз", "ЖОО"), op("adult", "Взрослые", "Ересектер")]), select("lesson_format", "Занятия", "Сабақ", [op("individual", "Индивидуально", "Жеке"), op("group", "В группе", "Топта")]), select("billing", "Цена", "Баға", [op("hour", "За час", "Сағатына"), op("lesson", "За занятие", "Сабаққа"), op("course", "За курс", "Курсқа")])],
  beautyService: [select("workplace", "Где оказываете", "Қызмет орны", [op("salon", "В салоне", "Салонда"), op("home", "У мастера", "Шеберде"), op("visit", "С выездом", "Барып қызмет көрсету")])],
  professionalService: [select("client_type", "Для кого", "Кімге", [op("individual", "Физлица", "Жеке тұлғалар"), op("business", "Бизнес", "Бизнес"), op("both", "Для всех", "Барлығына")]), select("engagement", "Формат работы", "Жұмыс форматы", [op("consultation", "Консультация", "Кеңес"), op("document", "Подготовка документов", "Құжат дайындау"), op("full", "Полное сопровождение", "Толық сүйемелдеу")])],
  cleaningService: [select("object_type", "Тип объекта", "Нысан түрі", [op("flat", "Квартира", "Пәтер"), op("house", "Дом", "Үй"), op("office", "Офис", "Кеңсе"), op("commercial", "Коммерческое помещение", "Коммерциялық орын")]), number("area", "Площадь", "Ауданы", "м²", "м²")],
  propertyService: [select("object_type", "Тип объекта", "Нысан түрі", [op("flat", "Квартира", "Пәтер"), op("house", "Дом", "Үй"), op("office", "Офис", "Кеңсе"), op("commercial", "Коммерческий объект", "Коммерциялық нысан"), op("industrial", "Промышленный объект", "Өнеркәсіптік нысан")]), number("object_area", "Площадь объекта", "Нысан ауданы", "м²", "м²"), bool("materials_included", "Материалы включены", "Материалдар кіреді")],
  plumbingService: [select("object_type", "Объект", "Нысан", [op("flat", "Квартира", "Пәтер"), op("house", "Дом", "Үй"), op("commercial", "Коммерческий", "Коммерциялық")]), bool("emergency_call", "Аварийный выезд", "Апаттық шақыру"), bool("parts_available", "Запчасти и материалы в наличии", "Қосалқы бөлшектер мен материалдар бар")],
  electricalService: [select("object_type", "Объект", "Нысан", [op("flat", "Квартира", "Пәтер"), op("house", "Дом", "Үй"), op("commercial", "Коммерческий", "Коммерциялық"), op("industrial", "Промышленный", "Өнеркәсіптік")]), select("network_voltage", "Сеть", "Желі", [op("220", "220 В", "220 В"), op("380", "380 В", "380 В"), op("low-voltage", "Слаботочная", "Әлсіз ток")]), bool("licensed", "Есть допуск / лицензия", "Рұқсаты / лицензиясы бар")],
  hvacService: [select("equipment_scope", "Тип оборудования", "Жабдық түрі", [op("domestic", "Бытовое", "Тұрмыстық"), op("commercial", "Коммерческое", "Коммерциялық"), op("industrial", "Промышленное", "Өнеркәсіптік")]), number("equipment_count", "Количество единиц", "Жабдық саны"), bool("refrigerant_available", "Хладагент в наличии", "Салқындатқыш зат бар")],
  householdService: [select("provider_type", "Исполнитель", "Орындаушы", [op("private", "Частный мастер", "Жеке шебер"), op("company", "Компания", "Компания")]), bool("same_day", "Возможно в день заказа", "Тапсырыс күні мүмкін")],
  applianceRepairService: [BRAND_TEXT, MODEL_TEXT, bool("at_customer", "Ремонт у клиента", "Клиентте жөндеу"), bool("parts_available", "Запчасти в наличии", "Қосалқы бөлшектер бар")],
  deviceRepairService: [BRAND_TEXT, MODEL_TEXT, bool("data_recovery", "Сохранение / восстановление данных", "Деректерді сақтау / қалпына келтіру"), bool("parts_available", "Запчасти в наличии", "Қосалқы бөлшектер бар")],
  autoService: [select("vehicle_scope", "Транспорт", "Көлік", [op("passenger", "Легковой", "Жеңіл"), op("commercial", "Коммерческий", "Коммерциялық"), op("motorcycle", "Мототехника", "Мототехника"), op("special", "Спецтехника", "Арнайы техника")]), select("compatible_brand", "Марка авто", "Көлік маркасы", PASSENGER_BRANDS), bool("mobile_service", "Выездной сервис", "Жылжымалы сервис"), bool("parts_available", "Запчасти в наличии", "Қосалқы бөлшектер бар")],
  wellnessService: [select("audience", "Для кого", "Кімге", [op("women", "Женщины", "Әйелдер"), op("men", "Мужчины", "Ерлер"), op("children", "Дети", "Балалар"), op("all", "Все", "Барлығы")]), bool("certified", "Есть профильное образование / сертификат", "Бейінді білімі / сертификаты бар")],
  itService: [select("service_platform", "Платформа", "Платформа", [op("web", "Web", "Web"), op("mobile", "iOS / Android", "iOS / Android"), op("desktop", "Desktop", "Desktop"), op("cloud", "Cloud / DevOps", "Cloud / DevOps"), op("mixed", "Несколько", "Бірнеше")]), bool("remote_available", "Удалённая работа", "Қашықтан жұмыс"), bool("contract_available", "Работа по договору", "Келісімшартпен жұмыс")],
  photoVideoService: [select("production_format", "Формат", "Формат", [op("studio", "В студии", "Студияда"), op("location", "На локации", "Локацияда"), op("both", "Оба", "Екеуі де")]), number("duration_hours", "Минимальная длительность", "Ең аз ұзақтық", "ч", "сағ"), bool("equipment_included", "Оборудование включено", "Жабдық кіреді")],
  legalService: [select("client_type", "Клиент", "Клиент", [op("individual", "Физлицо", "Жеке тұлға"), op("business", "Бизнес", "Бизнес"), op("both", "Все", "Барлығы")]), select("legal_format", "Формат помощи", "Көмек форматы", [op("consultation", "Консультация", "Кеңес"), op("documents", "Документы", "Құжаттар"), op("representation", "Представительство", "Өкілдік"), op("full", "Сопровождение", "Сүйемелдеу")]), bool("licensed", "Есть лицензия / статус", "Лицензиясы / мәртебесі бар")],
  accountingService: [select("client_type", "Клиент", "Клиент", [op("ip", "ИП", "ЖК"), op("too", "ТОО", "ЖШС"), op("ngo", "НКО", "КЕҰ"), op("individual", "Физлицо", "Жеке тұлға")]), select("tax_regime", "Налоговый режим", "Салық режимі", [op("simplified", "Упрощённый", "Жеңілдетілген"), op("general", "Общеустановленный", "Жалпыға белгіленген"), op("retail", "Розничный налог", "Бөлшек салық"), op("unknown", "Не определён", "Анықталмаған")]), bool("licensed", "Есть профессиональная сертификация", "Кәсіби сертификациясы бар")],
  eventService: [number("guest_count", "Количество гостей", "Қонақ саны"), select("venue_type", "Площадка", "Алаң", [op("indoor", "В помещении", "Жабық жерде"), op("outdoor", "На улице", "Далада"), op("both", "Любая", "Кез келген")]), bool("equipment_included", "Оборудование включено", "Жабдық кіреді")],
  securityService: [select("protected_object", "Объект охраны", "Қорғалатын нысан", [op("home", "Жильё", "Тұрғын үй"), op("office", "Офис", "Кеңсе"), op("retail", "Торговый объект", "Сауда нысаны"), op("industrial", "Промышленный", "Өнеркәсіптік"), op("event", "Мероприятие", "Іс-шара")]), bool("licensed", "Есть лицензия", "Лицензиясы бар"), bool("rapid_response", "Группа быстрого реагирования", "Жедел әрекет ету тобы")],
  petService: [select("animal_scope", "Животное", "Жануар", [op("dogs", "Собаки", "Иттер"), op("cats", "Кошки", "Мысықтар"), op("birds", "Птицы", "Құстар"), op("small", "Мелкие животные", "Ұсақ жануарлар"), op("farm", "Сельхозживотные", "Ауыл шаруашылығы жануарлары")]), bool("home_visit", "Выезд на дом", "Үйге бару"), bool("certified", "Есть профильное образование", "Бейінді білімі бар")],
  furnitureService: [select("material_scope", "Материал", "Материал", [op("wood", "Массив", "Тұтас ағаш"), op("panel", "ЛДСП / МДФ", "ЛДСП / МДФ"), op("metal", "Металл", "Металл"), op("upholstery", "Мягкая мебель", "Жұмсақ жиһаз"), op("mixed", "Комбинированный", "Аралас")]), bool("measurement", "Замер", "Өлшеу"), bool("design_project", "Дизайн-проект", "Дизайн-жоба")],
  agroService: [select("customer_type", "Заказчик", "Тапсырыс беруші", [op("household", "Личное хозяйство", "Жеке шаруашылық"), op("farm", "Ферма / КХ", "Ферма / ШҚ"), op("business", "Предприятие", "Кәсіпорын")]), number("area_hectares", "Площадь", "Ауданы", "га", "га"), bool("machinery_included", "Техника исполнителя", "Орындаушы техникасы")],
  businessService: [select("client_type", "Клиент", "Клиент", [op("startup", "Стартап", "Стартап"), op("sme", "Малый и средний бизнес", "Шағын және орта бизнес"), op("enterprise", "Крупная компания", "Ірі компания"), op("individual", "Частное лицо", "Жеке тұлға")]), bool("contract_available", "Работа по договору", "Келісімшартпен жұмыс"), bool("vat", "Работа с НДС", "ҚҚС-пен жұмыс")],
  travelService: [text("destination", "Страна / направление", "Ел / бағыт", { filterable: true, searchable: true, filterMode: "search" }), select("customer_scope", "Клиенты", "Клиенттер", [op("individual", "Один человек", "Бір адам"), op("family", "Семья", "Отбасы"), op("group", "Группа", "Топ"), op("business", "Бизнес", "Бизнес")]), bool("document_support", "Сопровождение документов", "Құжаттарды сүйемелдеу")],

  smartphone: [select("brand", "Бренд", "Бренд", SMARTPHONE_BRANDS, { required: true }), dependentSelect("model", "Модель", "Модель", "brand", smartphoneModels), OTHER_MODEL, select("storage", "Память", "Жад", [op("32", "32 ГБ", "32 ГБ"), op("64", "64 ГБ", "64 ГБ"), op("128", "128 ГБ", "128 ГБ"), op("256", "256 ГБ", "256 ГБ"), op("512", "512 ГБ", "512 ГБ"), op("1024", "1 ТБ", "1 ТБ")]), select("ram", "Оперативная память", "Жедел жад", [op("4", "4 ГБ", "4 ГБ"), op("6", "6 ГБ", "6 ГБ"), op("8", "8 ГБ", "8 ГБ"), op("12", "12 ГБ", "12 ГБ"), op("16", "16 ГБ и больше", "16 ГБ және көп")]), select("sim", "SIM / eSIM", "SIM / eSIM", [op("single", "1 SIM", "1 SIM"), op("dual", "2 SIM", "2 SIM"), op("esim", "eSIM", "eSIM"), op("dual-esim", "SIM + eSIM", "SIM + eSIM")]), select("color", "Цвет", "Түсі", [op("black", "Чёрный", "Қара"), op("white", "Белый", "Ақ"), op("blue", "Синий", "Көк"), op("green", "Зелёный", "Жасыл"), op("gold", "Золотистый", "Алтын"), op("other", "Другой", "Басқа")]), CONDITION, select("package", "Комплект", "Жинақ", [op("phone", "Только устройство", "Тек құрылғы"), op("box", "С коробкой", "Қорабымен"), op("full", "Полный комплект", "Толық жинақ")]), WARRANTY],
  tablet: [select("brand", "Бренд", "Бренд", tabletBrands, { required: true }), dependentSelect("model", "Модель", "Модель", "brand", tabletModels), OTHER_MODEL, select("storage", "Память", "Жад", [op("32", "32 ГБ", "32 ГБ"), op("64", "64 ГБ", "64 ГБ"), op("128", "128 ГБ", "128 ГБ"), op("256", "256 ГБ", "256 ГБ"), op("512", "512 ГБ", "512 ГБ"), op("1024", "1 ТБ", "1 ТБ")]), number("screen_size", "Диагональ", "Диагональ", "дюйм", "дюйм"), select("connectivity", "Связь", "Байланыс", [op("wifi", "Wi-Fi", "Wi-Fi"), op("cellular", "Wi-Fi + Cellular", "Wi-Fi + Cellular")]), bool("stylus_included", "Стилус в комплекте", "Стилус жинақта"), CONDITION, WARRANTY],
  ereader: [select("brand", "Бренд", "Бренд", ereaderBrands, { required: true }), dependentSelect("model", "Модель", "Модель", "brand", ereaderModels), OTHER_MODEL, number("screen_size", "Диагональ", "Диагональ", "дюйм", "дюйм"), bool("color_screen", "Цветной экран", "Түсті экран"), bool("backlight", "Подсветка", "Артқы жарық"), bool("waterproof", "Защита от воды", "Судан қорғау"), CONDITION],
  laptop: [BRAND_TEXT, MODEL_TEXT, text("cpu", "Процессор", "Процессор", { filterable: true, searchable: true, filterMode: "search" }), select("ram", "Оперативная память", "Жедел жад", [op("4", "4 ГБ", "4 ГБ"), op("8", "8 ГБ", "8 ГБ"), op("16", "16 ГБ", "16 ГБ"), op("32", "32 ГБ", "32 ГБ"), op("64+", "64 ГБ и больше", "64 ГБ және көп")]), select("storage_type", "Накопитель", "Жинақтауыш", [op("ssd", "SSD", "SSD"), op("hdd", "HDD", "HDD"), op("both", "SSD + HDD", "SSD + HDD")]), number("storage_capacity", "Объём накопителя", "Жинақтауыш көлемі", "ГБ", "ГБ"), text("gpu", "Видеокарта", "Бейне карта", { filterable: true, searchable: true, filterMode: "search" }), number("screen_size", "Диагональ", "Диагональ", "дюйм", "дюйм"), CONDITION],
  computer: [BRAND_TEXT, MODEL_TEXT, text("cpu", "Процессор", "Процессор", { filterable: true, searchable: true, filterMode: "search" }), select("ram", "Оперативная память", "Жедел жад", [op("8", "8 ГБ", "8 ГБ"), op("16", "16 ГБ", "16 ГБ"), op("32", "32 ГБ", "32 ГБ"), op("64+", "64 ГБ и больше", "64 ГБ және көп")]), text("gpu", "Видеокарта", "Бейне карта", { filterable: true, searchable: true, filterMode: "search" }), number("storage_capacity", "Объём накопителя", "Жинақтауыш көлемі", "ГБ", "ГБ"), CONDITION],
  component: [select("component_type", "Тип комплектующего", "Құрамдас бөлік түрі", [op("cpu", "Процессор", "Процессор"), op("gpu", "Видеокарта", "Бейне карта"), op("ram", "Оперативная память", "Жедел жад"), op("motherboard", "Материнская плата", "Аналық тақша"), op("storage", "Накопитель", "Жинақтауыш"), op("psu", "Блок питания", "Қуат көзі"), op("case", "Корпус", "Корпус"), op("cooling", "Охлаждение", "Салқындату")], { required: true }), BRAND_TEXT, MODEL_TEXT, CONDITION],
  display: [BRAND_TEXT, number("screen_size", "Диагональ", "Диагональ", "дюйм", "дюйм"), select("resolution", "Разрешение", "Ажыратымдылық", [op("hd", "HD", "HD"), op("full-hd", "Full HD", "Full HD"), op("2k", "2K / QHD", "2K / QHD"), op("4k", "4K", "4K"), op("8k", "8K", "8K")]), select("panel", "Тип панели", "Панель түрі", [op("ips", "IPS", "IPS"), op("va", "VA", "VA"), op("oled", "OLED", "OLED"), op("qled", "QLED", "QLED"), op("mini-led", "Mini LED", "Mini LED")]), number("refresh_rate", "Частота", "Жиілігі", "Гц", "Гц"), CONDITION],
  tv: [bool("smart_tv", "Smart TV", "Smart TV")],
  camera: [BRAND_TEXT, MODEL_TEXT, select("camera_type", "Тип камеры", "Камера түрі", [op("dslr", "Зеркальная", "Айналы"), op("mirrorless", "Беззеркальная", "Айнасыз"), op("compact", "Компактная", "Шағын"), op("instant", "Моментальная", "Жедел")]), text("mount", "Байонет", "Байонет", { filterable: true, filterMode: "search" }), CONDITION],
  lens: [BRAND_TEXT, MODEL_TEXT, text("mount", "Байонет", "Байонет", { filterable: true, filterMode: "search", required: true }), number("focal_length", "Фокусное расстояние", "Фокус қашықтығы", "мм", "мм"), CONDITION],
  appliance: [BRAND_TEXT, MODEL_TEXT, CONDITION, WARRANTY],
  audio: [select("audio_type", "Тип", "Түрі", [op("headphones", "Наушники", "Құлаққап"), op("speaker", "Колонка", "Динамик"), op("system", "Акустическая система", "Акустикалық жүйе"), op("amplifier", "Усилитель / ресивер", "Күшейткіш / ресивер")]), BRAND_TEXT, MODEL_TEXT, select("connection", "Подключение", "Қосылу", [op("wired", "Проводное", "Сымды"), op("wireless", "Беспроводное", "Сымсыз"), op("both", "Оба варианта", "Екі нұсқа")]), CONDITION],
  gaming: [select("platform", "Платформа", "Платформа", [op("playstation", "PlayStation", "PlayStation"), op("xbox", "Xbox", "Xbox"), op("nintendo", "Nintendo", "Nintendo"), op("pc", "PC", "PC"), op("other", "Другая", "Басқа")]), BRAND_TEXT, MODEL_TEXT, CONDITION],

  furniture: [select("furniture_type", "Тип мебели", "Жиһаз түрі", [op("sofa", "Диван", "Диван"), op("bed", "Кровать", "Кереует"), op("wardrobe", "Шкаф", "Шкаф"), op("table", "Стол", "Үстел"), op("chair", "Стул / кресло", "Орындық / кресло"), op("kitchen", "Кухонная мебель", "Асүй жиһазы"), op("other", "Другое", "Басқа")]), select("material", "Материал", "Материалы", [op("wood", "Дерево", "Ағаш"), op("mdf", "МДФ / ЛДСП", "МДФ / ЛДСП"), op("metal", "Металл", "Металл"), op("glass", "Стекло", "Шыны"), op("mixed", "Комбинированный", "Аралас")]), text("dimensions", "Размеры", "Өлшемдері"), CONDITION, DELIVERY],
  lighting: [select("lighting_type", "Тип", "Түрі", [op("chandelier", "Люстра", "Аспашам"), op("lamp", "Светильник", "Шам"), op("floor", "Торшер", "Еден шамы"), op("outdoor", "Уличное", "Сыртқы")]), select("light_source", "Источник света", "Жарық көзі", [op("led", "LED", "LED"), op("bulb", "Лампа", "Шам"), op("integrated", "Встроенный LED", "Кіріктірілген LED")]), number("power", "Мощность", "Қуаты", "Вт", "Вт"), CONDITION],
  gardenGoods: [select("product_type", "Тип товара", "Тауар түрі", [op("tool", "Инструмент", "Құрал"), op("equipment", "Техника", "Техника"), op("plant", "Растение / семена", "Өсімдік / тұқым"), op("irrigation", "Полив", "Суару"), op("decor", "Декор", "Әшекей")]), BRAND_TEXT, select("purpose", "Назначение", "Мақсаты", [op("home", "Для дома", "Үйге"), op("garden", "Для сада", "Бақшаға"), op("farm", "Для хозяйства", "Шаруашылыққа")]), CONDITION],
  tool: [select("tool_type", "Тип инструмента", "Құрал түрі", [op("drill", "Дрель / шуруповёрт", "Бұрғы / бұрауыш"), op("saw", "Пила", "Ара"), op("grinder", "Шлифмашина", "Тегістегіш"), op("compressor", "Компрессор", "Компрессор"), op("hand", "Ручной инструмент", "Қол құралы"), op("other", "Другой", "Басқа")]), select("power_source", "Питание", "Қуат көзі", [op("mains", "Сеть", "Желі"), op("battery", "Аккумулятор", "Аккумулятор"), op("petrol", "Бензин", "Бензин"), op("manual", "Ручной", "Қолмен")]), number("power", "Мощность", "Қуаты", "Вт", "Вт"), BRAND_TEXT, CONDITION],

  clothing: [BRAND_TEXT, text("size", "Размер", "Өлшем", { filterable: true, filterMode: "search", required: true }), select("season", "Сезон", "Маусым", [op("summer", "Лето", "Жаз"), op("demi", "Демисезон", "Маусымаралық"), op("winter", "Зима", "Қыс"), op("all", "Всесезон", "Барлық маусым")]), text("material", "Материал", "Материалы", { filterable: true, filterMode: "search" }), CONDITION],
  shoes: [BRAND_TEXT, number("size", "Размер", "Өлшем"), select("season", "Сезон", "Маусым", [op("summer", "Лето", "Жаз"), op("demi", "Демисезон", "Маусымаралық"), op("winter", "Зима", "Қыс")]), CONDITION],
  bags: [BRAND_TEXT, select("bag_type", "Тип", "Түрі", [op("bag", "Сумка", "Сөмке"), op("backpack", "Рюкзак", "Арқа сөмке"), op("briefcase", "Портфель", "Портфель"), op("suitcase", "Чемодан", "Чемодан")]), text("material", "Материал", "Материалы"), CONDITION],
  jewelry: [BRAND_TEXT, select("item_type", "Тип", "Түрі", [op("watch", "Часы", "Сағат"), op("ring", "Кольцо", "Сақина"), op("earrings", "Серьги", "Сырға"), op("chain", "Цепочка", "Шынжыр"), op("bracelet", "Браслет", "Білезік")]), select("material", "Материал", "Материалы", [op("gold", "Золото", "Алтын"), op("silver", "Серебро", "Күміс"), op("steel", "Сталь", "Болат"), op("costume", "Бижутерия", "Бижутерия")]), CONDITION],

  kidsClothing: [select("age_group", "Возраст", "Жас тобы", [op("0-1", "До 1 года", "1 жасқа дейін"), op("1-3", "1–3 года", "1–3 жас"), op("3-6", "3–6 лет", "3–6 жас"), op("7-12", "7–12 лет", "7–12 жас"), op("teen", "Подросткам", "Жасөспірімдерге")]), text("size", "Размер", "Өлшем", { filterable: true, filterMode: "search" }), select("gender", "Пол", "Жынысы", [op("girl", "Для девочки", "Қыз балаға"), op("boy", "Для мальчика", "Ұл балаға"), op("unisex", "Унисекс", "Унисекс")]), select("season", "Сезон", "Маусым", [op("summer", "Лето", "Жаз"), op("demi", "Демисезон", "Маусымаралық"), op("winter", "Зима", "Қыс")]), CONDITION],
  stroller: [BRAND_TEXT, MODEL_TEXT, select("stroller_type", "Тип коляски", "Арба түрі", [op("carrycot", "Люлька", "Бесік арба"), op("stroller", "Прогулочная", "Серуендік"), op("transformer", "Трансформер", "Трансформер"), op("2in1", "2 в 1", "2-де 1"), op("3in1", "3 в 1", "3-те 1"), op("twins", "Для двойни", "Егіздерге")]), select("age_group", "Возраст", "Жас", [op("0-6m", "0–6 месяцев", "0–6 ай"), op("6-36m", "6–36 месяцев", "6–36 ай")]), CONDITION],
  carSeat: [BRAND_TEXT, select("weight_group", "Группа / вес", "Топ / салмақ", [op("0", "0 (до 10 кг)", "0 (10 кг дейін)"), op("0+", "0+ (до 13 кг)", "0+ (13 кг дейін)"), op("1", "1 (9–18 кг)", "1 (9–18 кг)"), op("2-3", "2/3 (15–36 кг)", "2/3 (15–36 кг)"), op("universal", "Универсальная", "Әмбебап")]), bool("isofix", "ISOFIX", "ISOFIX"), CONDITION],
  toy: [select("toy_type", "Тип игрушки", "Ойыншық түрі", [op("educational", "Развивающая", "Дамытушы"), op("doll", "Кукла", "Қуыршақ"), op("construction", "Конструктор", "Құрастырғыш"), op("vehicle", "Машинка / транспорт", "Машина / көлік"), op("soft", "Мягкая", "Жұмсақ"), op("board", "Настольная", "Үстел ойыны")]), select("age_group", "Возраст", "Жас", [op("0-1", "До 1 года", "1 жасқа дейін"), op("1-3", "1–3 года", "1–3 жас"), op("3-6", "3–6 лет", "3–6 жас"), op("7+", "7 лет и старше", "7 жастан жоғары")]), CONDITION],

  bicycle: [BRAND_TEXT, select("bicycle_type", "Тип велосипеда", "Велосипед түрі", [op("mountain", "Горный", "Тау"), op("road", "Шоссейный", "Шоссе"), op("city", "Городской", "Қалалық"), op("bmx", "BMX", "BMX"), op("kids", "Детский", "Балаларға"), op("electric", "Электровелосипед", "Электр велосипед")]), number("wheel_size", "Размер колёс", "Дөңгелек өлшемі", "дюйм", "дюйм"), text("frame_size", "Размер рамы", "Жақтау өлшемі", { filterable: true, filterMode: "search" }), select("frame_material", "Материал рамы", "Жақтау материалы", [op("steel", "Сталь", "Болат"), op("aluminum", "Алюминий", "Алюминий"), op("carbon", "Карбон", "Карбон")]), CONDITION],
  instrument: [select("instrument_type", "Тип инструмента", "Аспап түрі", [op("guitar", "Гитара", "Гитара"), op("keyboard", "Клавишный", "Пернелі"), op("drums", "Ударный", "Ұрмалы"), op("wind", "Духовой", "Үрмелі"), op("strings", "Струнный", "Ішекті"), op("studio", "Студийное оборудование", "Студиялық жабдық")]), BRAND_TEXT, MODEL_TEXT, CONDITION],
  sportsGoods: [text("sport", "Вид спорта", "Спорт түрі", { filterable: true, searchable: true, filterMode: "search" }), text("product_type", "Тип товара", "Тауар түрі", { filterable: true, searchable: true, filterMode: "search" }), BRAND_TEXT, CONDITION],
  ticket: [text("event", "Событие", "Іс-шара", { searchable: true, required: true }), date("event_date", "Дата", "Күні", { required: true }), number("quantity", "Количество", "Саны", "шт.", "дана"), text("seat", "Сектор / место", "Сектор / орын")],

  pet: [text("breed", "Порода", "Тұқымы", { filterable: true, searchable: true, filterMode: "search", required: true }), number("age_months", "Возраст", "Жасы", "мес.", "ай"), select("gender", "Пол", "Жынысы", [op("male", "Самец", "Еркек"), op("female", "Самка", "Ұрғашы")]), bool("documents", "Документы / ветпаспорт", "Құжаттар / ветеринарлық төлқұжат"), bool("vaccinated", "Прививки", "Екпелері бар"), bool("sterilized", "Стерилизован(а)", "Зарарсыздандырылған"), bool("pedigree", "Родословная", "Шежіресі бар")],
  smallAnimal: [text("species", "Вид / порода", "Түрі / тұқымы", { filterable: true, searchable: true, filterMode: "search", required: true }), number("age_months", "Возраст", "Жасы", "мес.", "ай"), select("gender", "Пол", "Жынысы", [op("male", "Самец", "Еркек"), op("female", "Самка", "Ұрғашы"), op("unknown", "Не определён", "Белгісіз")]), bool("documents", "Документы", "Құжаттары бар")],
  farmAnimal: [select("animal_species", "Вид", "Түрі", [op("cattle", "Крупный рогатый скот", "Ірі қара"), op("horse", "Лошади", "Жылқы"), op("sheep-goat", "Овцы / козы", "Қой / ешкі"), op("pig", "Свиньи", "Шошқа"), op("poultry", "Птица", "Құс"), op("other", "Другой", "Басқа")], { required: true }), text("breed", "Порода", "Тұқымы", { filterable: true, searchable: true, filterMode: "search" }), number("age_months", "Возраст", "Жасы", "мес.", "ай"), select("gender", "Пол", "Жынысы", [op("male", "Самец", "Еркек"), op("female", "Самка", "Ұрғашы")]), select("purpose", "Назначение", "Мақсаты", [op("breeding", "Разведение", "Асылдандыру"), op("dairy", "Молочное", "Сүт"), op("meat", "Мясное", "Ет"), op("work", "Рабочее", "Жұмыс")]), bool("documents", "Документы", "Құжаттары бар")],
  lostPet: [select("notice_type", "Объявление", "Хабарландыру", [op("lost", "Потерялось", "Жоғалды"), op("found", "Найдено", "Табылды")], { required: true }), text("animal_species", "Вид животного", "Жануар түрі", { filterable: true, searchable: true, filterMode: "search", required: true }), text("breed", "Порода", "Тұқымы", { searchable: true }), select("gender", "Пол", "Жынысы", [op("male", "Самец", "Еркек"), op("female", "Самка", "Ұрғашы"), op("unknown", "Неизвестно", "Белгісіз")]), date("event_date", "Дата", "Күні"), text("district", "Район", "Аудан", { searchable: true }), text("features", "Особые приметы", "Ерекше белгілері", { searchable: true })],

  buildingMaterial: [text("material", "Материал / состав", "Материал / құрам", { filterable: true, searchable: true, filterMode: "search" }), text("size_spec", "Размер / маркировка", "Өлшем / таңбалау", { filterable: true, searchable: true, filterMode: "search" }), number("quantity", "Количество", "Саны"), select("sale_unit", "Единица продажи", "Сату бірлігі", [op("piece", "Штука", "Дана"), op("meter", "Метр", "Метр"), op("square-meter", "М²", "М²"), op("cubic-meter", "М³", "М³"), op("kilogram", "Кг", "Кг"), op("ton", "Тонна", "Тонна"), op("package", "Упаковка", "Қаптама")]), CONDITION, DELIVERY],
  rentalGoods: [select("billing_period", "Тариф", "Тариф", [op("hour", "За час", "Сағатына"), op("day", "За сутки", "Тәулігіне"), op("week", "За неделю", "Аптасына"), op("month", "За месяц", "Айына"), op("agreement", "Договорной", "Келісімді")], { required: true }), number("minimum_term", "Минимальный срок", "Ең аз мерзім"), number("deposit", "Залог", "Кепіл", "₸", "₸"), bool("documents_required", "Нужны документы", "Құжаттар қажет"), bool("delivery", "Доставка", "Жеткізу"), bool("operator_included", "Оператор / водитель включён", "Оператор / жүргізуші кіреді"), CONDITION],
  equipment: [BRAND_TEXT, MODEL_TEXT, YEAR, CONDITION, number("power", "Мощность", "Қуаты", "кВт", "кВт"), text("capacity", "Производительность / характеристики", "Өнімділігі / сипаттамалары", { searchable: true })],
  readyBusiness: [text("industry", "Отрасль", "Сала", { filterable: true, searchable: true, filterMode: "search", required: true }), select("premises", "Помещение", "Үй-жай", [op("owned", "В собственности", "Меншікте"), op("rented", "В аренде", "Жалдауда"), op("none", "Не требуется", "Қажет емес")]), bool("equipment_included", "Оборудование включено", "Жабдық кіреді"), number("business_age", "Срок работы", "Жұмыс мерзімі", "лет", "жыл")],
  free: [select("condition", "Состояние", "Күйі", [op("good", "Можно использовать", "Қолдануға болады"), op("repair", "Требует ремонта", "Жөндеуді қажет етеді")])],
  exchange: [text("wanted", "На что хотите обменять", "Не нәрсеге айырбастайсыз", { required: true, searchable: true, validation: { maxLength: 240 } })],
} satisfies Record<string, SeedAttributeDefinition[]>;

export type CategorySchemaProfile = keyof typeof profiles;

const rootDefaults: Record<string, CategorySchemaProfile[]> = {
  transport: ["transportSimple"], parts: ["autoPart"], "real-estate": ["flatSale"], jobs: ["job"],
  services: ["serviceBase"], electronics: ["goodsBrand"], "home-garden": ["goods"], personal: ["clothing"],
  kids: ["kidsClothing"], hobby: ["sportsGoods"], animals: ["pet"], business: ["equipment"],
  free: ["free"], exchange: ["exchange"], "construction-repair": ["buildingMaterial"],
  "goods-rental": ["rentalGoods"],
};

const profileAssignments: Record<string, CategorySchemaProfile[]> = {
  transport: ["transportSimple"],
  cars: ["passengerCar"], "cars-sedan": ["passengerCar"], "cars-suv": ["passengerCar"], "cars-hatchback": ["passengerCar"], "cars-wagon": ["passengerCar"], "cars-minivan": ["passengerCar"], "cars-coupe": ["passengerCar"], "cars-cabriolet": ["passengerCar"], "cars-pickup": ["passengerCar"],
  motorcycles: ["motorcycle"], "road-motorcycles": ["motorcycle"], scooters: ["motorcycle"], atv: ["motorcycle"], snowmobiles: ["motorcycle"],
  "commercial-transport": ["commercialVehicle"], trucks: ["commercialVehicle"], buses: ["commercialVehicle", "passengerCommercial"], minibuses: ["commercialVehicle", "passengerCommercial"], trailers: ["trailer"],
  "special-transport": ["machinery"], "construction-machinery": ["machinery"], "road-machinery": ["machinery"], "warehouse-machinery": ["machinery"], "municipal-machinery": ["machinery"], "agricultural-transport": ["machinery"], tractors: ["machinery"], harvesters: ["machinery"], "agro-attachments": ["machinery"],
  "water-transport": ["transportSimple"], "air-transport": ["transportSimple"], "other-transport": ["transportSimple"],

  parts: ["autoPart"], "car-parts": ["autoPart"], "engine-parts": ["autoPart"], "transmission-parts": ["autoPart"], "suspension-parts": ["autoPart"], "body-parts": ["autoPart"], "auto-electrics": ["autoPart"], optics: ["autoPart"], "interior-parts": ["autoPart"], "tires-wheels": ["tires"], "car-accessories": ["goodsBrand"], "oils-fluids": ["fluids"], "moto-parts": ["autoPart"], "special-parts": ["autoPart"], "auto-dismantling": ["autoPart"],

  "real-estate": ["flatSale"], "property-sale": ["flatSale"], "flats-sale": ["flatSale"], "rooms-sale": ["room"], "houses-sale": ["house"], "land-sale": ["land"], "commercial-sale": ["commercialProperty"], "garages-sale": ["garage"],
  "property-rent": ["flatSale", "rentTerms"], "flats-rent": ["flatSale", "rentTerms"], "houses-rent": ["house", "rentTerms"], "rooms-rent": ["room", "rentTerms"], "commercial-rent": ["commercialProperty", "rentTerms"],
  "property-daily": ["flatSale", "dailyTerms"], "flats-daily": ["flatSale", "dailyTerms"], "houses-daily": ["house", "dailyTerms"], "rooms-daily": ["room", "dailyTerms"],

  jobs: ["job"], "jobs-logistics": ["job"], "jobs-sales": ["job"], "jobs-construction": ["job"], "jobs-production": ["job"], "jobs-it": ["job"], "jobs-finance": ["job"], "jobs-education": ["job"], "jobs-medicine": ["job"], "jobs-horeca": ["job"], "jobs-security": ["job"], "jobs-domestic": ["job"], "jobs-agriculture": ["job"], "jobs-office": ["job"], "jobs-marketing": ["job"], "jobs-temporary": ["job"], "jobs-remote": ["job"],

  services: ["serviceBase"], "repair-construction-services": ["serviceBase", "repairService"], "apartment-renovation": ["serviceBase", "repairService"], "plumbing-services": ["serviceBase", "repairService"], "electrical-services": ["serviceBase", "repairService"], "windows-doors-services": ["serviceBase", "repairService"], "finishing-services": ["serviceBase", "repairService"],
  "household-services": ["serviceBase"], "appliance-repair": ["serviceBase", "repairService"], "auto-services": ["serviceBase", "repairService"], "transport-services": ["serviceBase", "transportService"], "beauty-health-services": ["serviceBase", "beautyService"], "education-services": ["serviceBase", "educationService"], "it-services": ["serviceBase", "professionalService"], "photo-video-services": ["serviceBase", "professionalService"], "legal-services": ["serviceBase", "professionalService"], "accounting-services": ["serviceBase", "professionalService"], "event-services": ["serviceBase", "professionalService"], "cleaning-services": ["serviceBase", "cleaningService"], "pet-services": ["serviceBase", "professionalService"], "furniture-services": ["serviceBase", "repairService"], "agro-services": ["serviceBase", "professionalService"], "business-services": ["serviceBase", "professionalService"],

  electronics: ["goodsBrand"], "phones-accessories": ["goodsBrand"], smartphones: ["smartphone"], "mobile-phones": ["smartphone"], "phone-cases": ["goodsBrand"], "phone-chargers": ["goodsBrand"], "screen-protectors": ["goodsBrand"], "smart-watches": ["smartphone"],
  computers: ["computer"], laptops: ["laptop"], "desktop-computers": ["computer"], "all-in-one": ["computer", "display"], "computer-components": ["component"], monitors: ["display"], "computer-peripherals": ["goodsBrand"], "storage-devices": ["component"], "network-equipment": ["goodsBrand"],
  "photo-video": ["camera"], cameras: ["camera"], lenses: ["lens"], "video-cameras": ["camera"], "action-cameras": ["camera"], "photo-accessories": ["goodsBrand"],
  "tv-video": ["display"], televisions: ["display", "tv"], projectors: ["display"], "tv-boxes": ["goodsBrand"], "media-players": ["goodsBrand"], audio: ["audio"], headphones: ["audio"], "portable-speakers": ["audio"], "speaker-systems": ["audio"], amplifiers: ["audio"], gaming: ["gaming"], "game-consoles": ["gaming"], "video-games": ["gaming"], "gaming-accessories": ["gaming"], "tablets-ereaders": ["smartphone"], "home-appliances": ["appliance"], "kitchen-appliances": ["appliance"], "climate-equipment": ["appliance"], "personal-care-electronics": ["appliance"],

  "home-garden": ["goods"], furniture: ["furniture"], interior: ["goods"], lighting: ["lighting"], textiles: ["goods"], dishes: ["goods"], "household-goods": ["goods"], "household-chemicals": ["goods"], "indoor-plants": ["gardenGoods"], garden: ["gardenGoods"], "garden-tools": ["tool"], "office-supplies": ["goods"], "food-drinks": ["goods"],
  personal: ["clothing"], "women-clothing": ["clothing"], "men-clothing": ["clothing"], "underwear-swimwear": ["clothing"], workwear: ["clothing"], "women-shoes": ["shoes"], "men-shoes": ["shoes"], headwear: ["clothing"], bags: ["bags"], "fashion-accessories": ["bags"], "watches-jewelry": ["jewelry"], wedding: ["clothing"], "beauty-products": ["goodsBrand"],
  kids: ["kidsClothing"], "kids-clothing": ["kidsClothing"], "kids-shoes": ["kidsClothing"], strollers: ["stroller"], "car-seats": ["carSeat"], toys: ["toy"], feeding: ["goodsBrand"], "kids-furniture": ["furniture"], school: ["goods"], "baby-care": ["goodsBrand"], "kids-transport": ["bicycle"],
  hobby: ["sportsGoods"], sports: ["sportsGoods"], bicycles: ["bicycle"], tourism: ["sportsGoods"], fishing: ["sportsGoods"], hunting: ["sportsGoods"], "musical-instruments": ["instrument"], books: ["goods"], collecting: ["goods"], "board-games": ["goodsBrand"], tickets: ["ticket"], handmade: ["goods"],
  animals: ["pet"], cats: ["pet"], dogs: ["pet"], birds: ["smallAnimal"], "fish-aquariums": ["smallAnimal"], rodents: ["smallAnimal"], reptiles: ["smallAnimal"], "farm-animals": ["farmAnimal"], "pet-supplies": ["goodsBrand"], "lost-found-pets": ["lostPet"],
  business: ["equipment"], "retail-equipment": ["equipment"], "industrial-equipment": ["equipment"], "food-equipment": ["equipment"], "agro-equipment": ["equipment"], "medical-equipment": ["equipment"], "beauty-equipment": ["equipment"], "office-equipment": ["equipment"], "tools-materials": ["tool"], "raw-materials": ["goodsBrand"], containers: ["goods"], "ready-business": ["readyBusiness"],
  free: ["free"], "free-home": ["free", "furniture"], "free-clothes": ["free", "clothing"], "free-kids": ["free", "kidsClothing"], "free-electronics": ["free", "goodsBrand"], "free-other": ["free"],
  exchange: ["exchange"], "exchange-transport": ["exchange", "transportSimple"], "exchange-property": ["exchange", "flatSale"], "exchange-electronics": ["exchange", "goodsBrand"], "exchange-other": ["exchange", "goods"],
};

export function resolveCategoryAttributeSchema(slug: string, rootSlug: string): {
  profileNames: CategorySchemaProfile[];
  attributes: SeedAttributeDefinition[];
} {
  const requestedProfiles = masterCatalogProfileAssignments[slug] ?? profileAssignments[slug] ?? rootDefaults[rootSlug] ?? ["goods"];
  const unknownProfiles = requestedProfiles.filter((profileName) => !(profileName in profiles));
  if (unknownProfiles.length) throw new Error(`Unknown category profile for ${slug}: ${unknownProfiles.join(", ")}`);
  const profileNames = requestedProfiles as CategorySchemaProfile[];
  const effective = new Map<string, SeedAttributeDefinition>();
  for (const profileName of profileNames) {
    for (const attribute of profiles[profileName]) effective.set(attribute.key, attribute);
  }
  return { profileNames, attributes: [...effective.values()] };
}

export const categorySchemaProfiles = profiles;
export const categoryProfileAssignments = profileAssignments;
