import type { SeedAttributeDefinition, SeedAttributeOption } from "./category-attribute-schemas.ts";

const key = (name: string) => name.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const named = (names: readonly string[]): SeedAttributeOption[] => names.map(name => ({ value: key(name), label: { ru: name, kk: name } }));
// Domain lists are intentionally separate; a vehicle manufacturer is never a
// fallback manufacturer for electronics. Unknown makers retain an explicit name.
export const manufacturerGroups = {
  kart: ["Birel Art", "CRG", "Tony Kart", "Sodikart", "Kosmic", "Exprit", "Praga", "Formula K", "Evo Kart"],
  petAccessory: ["Trixie", "Ferplast", "Savic", "Flamingo", "Hagen", "Petkit"],
  aquarium: ["Fluval", "Tetra", "Sera", "JBL", "Aquael", "Eheim", "Juwel", "SunSun", "Barbus", "Hagen"],
  irrigation: ["Netafim", "Rain Bird", "Rivulis", "Jain Irrigation", "Galcon", "Gardena", "Hozelock", "Karcher"],
  livestockEquipment: ["DeLaval", "GEA", "Lely", "BouMatic", "Big Dutchman", "Roxell", "Fancom", "SKOV", "Petersime", "Pas Reform", "Pellon", "Riberi"],
  laptop: ["Acer", "Apple", "ASUS", "Dell", "HP", "Honor", "Huawei", "Lenovo", "MSI", "Samsung", "Microsoft", "Gigabyte", "Razer", "Framework", "Toshiba", "Dynabook", "Fujitsu", "LG", "Xiaomi", "Chuwi", "Haier", "DEXP", "Hasee", "Thunderobot", "Maibenben", "Irbis", "Prestigio"],
  desktop: ["Acer", "Apple", "ASUS", "Dell", "HP", "Lenovo", "MSI", "Gigabyte", "Intel", "ASRock", "Zotac", "Beelink", "Minisforum", "Fujitsu", "Huawei", "Xiaomi", "DEXP"],
  component: ["Intel", "AMD", "NVIDIA", "ASUS", "MSI", "Gigabyte", "ASRock", "Sapphire", "PowerColor", "Zotac", "Palit", "Inno3D", "Gainward", "PNY", "EVGA", "Kingston", "Corsair", "Crucial", "G.Skill", "Samsung", "SK hynix", "ADATA", "Patriot", "TeamGroup", "Western Digital", "Seagate", "Toshiba", "SanDisk", "Transcend", "KingSpec", "DeepCool", "be quiet", "Cooler Master", "Noctua", "Seasonic", "Thermaltake", "NZXT", "Fractal Design", "Lian Li"],
  monitor: ["Acer", "Apple", "ASUS", "Dell", "HP", "Lenovo", "MSI", "Gigabyte", "Samsung", "LG", "AOC", "BenQ", "Philips", "ViewSonic", "Eizo", "iiyama", "Huawei", "Xiaomi", "DEXP"],
  television: ["Samsung", "LG", "Sony", "Philips", "TCL", "Hisense", "Xiaomi", "Haier", "Panasonic", "Sharp", "Toshiba", "Skyworth", "Thomson", "JVC", "Hyundai", "Kivi", "DEXP", "Artel", "Sber"],
  projector: ["Epson", "BenQ", "ViewSonic", "Optoma", "Acer", "ASUS", "LG", "Samsung", "Sony", "Panasonic", "XGIMI", "JMGO", "Anker", "Xiaomi", "Wanbo"],
  camera: ["Canon", "Nikon", "Sony", "Fujifilm", "Panasonic", "Olympus", "OM System", "Pentax", "Ricoh", "Leica", "Hasselblad", "Sigma", "GoPro", "DJI", "Insta360", "Blackmagic Design"],
  lens: ["Canon", "Nikon", "Sony", "Fujifilm", "Panasonic", "Olympus", "OM System", "Pentax", "Leica", "Sigma", "Tamron", "Tokina", "Samyang", "Viltrox", "Zeiss", "TTArtisan", "7Artisans", "Laowa"],
  graphicsTablet: ["Wacom", "Huion", "XP-Pen", "Xencelabs", "Gaomon", "UGEE", "VEIKK", "Bosto"],
  audio: ["Apple", "Samsung", "Sony", "JBL", "Bose", "Sennheiser", "Beyerdynamic", "Audio-Technica", "AKG", "Shure", "Marshall", "Bowers and Wilkins", "Bang and Olufsen", "Yamaha", "Denon", "Marantz", "Onkyo", "Pioneer", "Edifier", "Anker", "Beats", "Philips", "Panasonic", "LG", "Xiaomi", "Huawei", "Nothing", "Jabra", "Logitech", "HyperX", "Razer", "SteelSeries"],
  gaming: ["Sony", "Microsoft", "Nintendo", "Valve", "ASUS", "Lenovo", "MSI", "Meta", "HTC", "Pico", "Logitech", "Thrustmaster", "Fanatec", "Razer", "8BitDo", "Hori", "Sega", "Atari"],
  appliance: ["Samsung", "LG", "Bosch", "Siemens", "Beko", "Haier", "Hisense", "Gorenje", "Electrolux", "AEG", "Whirlpool", "Indesit", "Hotpoint", "Candy", "Miele", "Liebherr", "Atlant", "Artel", "Midea", "Toshiba", "Panasonic", "Sharp", "Philips", "Tefal", "Moulinex", "Krups", "DeLonghi", "Saeco", "Nivona", "Jura", "Braun", "Kenwood", "KitchenAid", "Smeg", "Redmond", "Polaris", "Vitek", "Scarlett", "Kitfort", "Xiaomi", "Dreame", "Roborock", "Dyson", "Karcher", "Thomas", "iRobot", "Bissell", "Gree", "Ballu", "Timberk", "Ariston", "Thermex", "Zanussi", "Brother", "Singer", "Janome", "Juki", "Remington", "Rowenta", "Wahl", "Moser", "Babyliss", "Oral-B", "Omron", "Beurer", "B.Well", "Medela", "Pigeon", "Chicco", "Avent", "Motorola"],
  furniture: ["IKEA", "Hoff", "Askona", "Ormatek", "Shatura", "Lazurit", "Stolplit", "BTS", "Triya", "Dyatkovo", "BRW", "Signal", "Halmar", "Herman Miller", "Steelcase", "Secretlab", "DXRacer"],
  clothing: ["Adidas", "Nike", "Puma", "Reebok", "New Balance", "Under Armour", "ASICS", "Zara", "H and M", "Uniqlo", "Mango", "Massimo Dutti", "Bershka", "Pull and Bear", "LC Waikiki", "DeFacto", "Koton", "Gloria Jeans", "Ostin", "Sela", "Befree", "Levi's", "Wrangler", "Lee", "Tommy Hilfiger", "Calvin Klein", "Lacoste", "Columbia", "The North Face", "Patagonia", "Decathlon", "Gucci", "Prada", "Chanel", "Dior", "Louis Vuitton", "Burberry", "Moncler"],
  shoes: ["Adidas", "Nike", "Puma", "Reebok", "New Balance", "ASICS", "Skechers", "ECCO", "Geox", "Clarks", "Timberland", "Dr. Martens", "Converse", "Vans", "Crocs", "Birkenstock", "Salomon", "Merrell", "Columbia", "Zara", "H and M", "LC Waikiki", "Kari", "Tamaris", "Rieker", "Demar", "Kotofey", "Kapika", "Reima", "Superfit", "Geox", "Anta", "Li-Ning"],
  kids: ["Chicco", "Cybex", "Britax Romer", "Maxi-Cosi", "Joie", "Nuna", "Inglesina", "Peg Perego", "Stokke", "Bugaboo", "Anex", "Tutis", "Adamex", "Riko", "Carrello", "Happy Baby", "Babyton", "Indigo", "Pituso", "Kinderkraft", "Doona", "Thule", "Evenflo", "Graco"],
  toy: ["LEGO", "Mattel", "Fisher-Price", "Barbie", "Hot Wheels", "Hasbro", "Play-Doh", "Nerf", "Playmobil", "Brio", "Hape", "VTech", "Chicco", "Tiny Love", "MGA Entertainment", "Spin Master", "Ravensburger", "Djeco", "Disney", "Polesie", "Step2", "Little Tikes", "Smoby", "FurReal"],
  bicycle: ["Trek", "Giant", "Merida", "Specialized", "Scott", "Cube", "Cannondale", "GT", "Kross", "Stels", "Forward", "Stern", "Format", "Author", "Shulz", "Woom", "Puky", "RoyalBaby", "Decathlon", "Haro", "Fuji", "Bianchi", "Pinarello"],
  scooter: ["Micro", "Globber", "Razor", "Oxelo", "Decathlon", "Xiaomi", "Ninebot", "Segway", "Kugoo", "Halten", "Yedoo", "Tech Team", "Triumf Active", "Novatrack", "HUDORA", "Scoot and Ride", "Puky"],
  tool: ["Bosch", "Makita", "DeWalt", "Milwaukee", "Metabo", "Hilti", "Festool", "Ryobi", "AEG", "Black and Decker", "Dremel", "Einhell", "Worx", "Stanley", "Knipex", "Wera", "Wiha", "Bahco", "Sata", "Stayer", "Zubr", "Interskol", "Resanta", "Deko", "Hilda", "Patriot", "Huter", "Champion", "Stihl", "Husqvarna", "Gardena", "Fiskars", "Total", "Ingco"],
  tires: ["Michelin", "Continental", "Bridgestone", "Goodyear", "Pirelli", "Dunlop", "Nokian", "Hankook", "Kumho", "Yokohama", "Toyo", "Falken", "BFGoodrich", "Nitto", "Nexen", "Cooper", "Maxxis", "Triangle", "Linglong", "Sailun", "Giti", "Cordiant", "Viatti", "Kama", "Belshina"],
  wheels: ["BBS", "OZ Racing", "Enkei", "Rays", "Vossen", "Borbet", "Ronal", "Alutec", "Sparco", "MAK", "AEZ", "Dezent", "Dotz", "K and K", "Skad", "Replay", "LS Wheels"],
  fluids: ["Shell", "Mobil", "Castrol", "TotalEnergies", "Elf", "Liqui Moly", "Motul", "Ravenol", "ZIC", "Kixx", "Idemitsu", "ENEOS", "Petronas", "Valvoline", "Fuchs", "Mannol", "Lukoil", "Gazpromneft", "Rosneft", "Sintec", "Felix"],
  parts: ["Bosch", "Denso", "NGK", "NTK", "Aisin", "Brembo", "TRW", "ZF", "Sachs", "Lemforder", "Febi", "Meyle", "SWAG", "Mahle", "Mann-Filter", "Filtron", "Purflux", "Valeo", "Hella", "Gates", "Dayco", "Continental", "SKF", "FAG", "NSK", "NTN", "SNR", "KYB", "Monroe", "Bilstein", "CTR", "555", "GMB", "Luzar", "Patron", "Toyota", "Lexus", "BMW", "Mercedes-Benz", "Volkswagen", "Audi", "Hyundai", "Kia", "Nissan", "Renault", "Ford", "Chevrolet", "Lada"],
  petSupply: ["Royal Canin", "Purina", "Pro Plan", "Hill's", "Brit", "Acana", "Orijen", "Farmina", "Monge", "Grandorf", "Whiskas", "Kitekat", "Sheba", "Felix", "Pedigree", "Chappi", "Trixie", "Ferplast", "Savic", "Flamingo", "Hagen", "Fluval", "Tetra", "Sera", "JBL", "Aquael", "Eheim", "Juwel", "SunSun", "Barbus", "Petkit"],
  outdoor: ["Decathlon", "Quechua", "Forclaz", "Outventure", "Naturehike", "Tramp", "Alexika", "Bask", "Red Fox", "Deuter", "Osprey", "The North Face", "Coleman", "Marmot", "MSR", "Fjallraven", "Salewa", "Sea to Summit", "Tatonka", "Stanley", "Thermos"],
  fishing: ["Shimano", "Daiwa", "Okuma", "Abu Garcia", "Penn", "Mitchell", "Ryobi", "Salmo", "Lucky John", "Rapala", "Mikado", "Major Craft", "Kosadaka", "Flagman", "Drennan", "Preston", "Fox", "Carp Pro"],
  instrument: ["Yamaha", "Casio", "Roland", "Korg", "Kawai", "Fender", "Squier", "Gibson", "Epiphone", "Ibanez", "Cort", "Takamine", "Taylor", "Martin", "Jackson", "ESP", "Pearl", "Tama", "Mapex", "Ludwig", "DW", "Zildjian", "Sabian", "Meinl", "Selmer", "Buffet Crampon", "Hohner", "Suzuki"],
  commercial: ["Mercedes-Benz", "MAN", "Scania", "Volvo", "DAF", "Iveco", "Renault Trucks", "Ford", "Isuzu", "Hino", "Mitsubishi Fuso", "Hyundai", "FAW", "JAC", "Foton", "Sinotruk", "Shacman", "Dongfeng", "Sitrak", "Kamaz", "MAZ", "GAZ", "Ural", "PAZ", "LiAZ", "NEFAZ", "Yutong", "King Long", "Golden Dragon", "Higer"],
  machinery: ["Caterpillar", "Komatsu", "Hitachi", "Volvo", "JCB", "Liebherr", "Develon", "Doosan", "Hyundai", "Sany", "XCMG", "Zoomlion", "LiuGong", "SDLG", "Shantui", "Bobcat", "Kubota", "Case", "New Holland", "John Deere", "Claas", "Massey Ferguson", "Fendt", "MTZ", "Rostselmash", "Kirovets", "Buhler", "Lovol", "YTO", "Dongfeng", "Tadano", "Kato", "Manitou", "Haulotte", "Genie", "JLG", "Hamm", "Bomag", "Ammann", "Wirtgen", "Vogele", "Toyota", "Hangcha", "Heli", "Linde", "Jungheinrich", "Crown", "Still", "Karcher"],
  watercraft: ["Yamaha", "Honda", "Suzuki", "Mercury", "Tohatsu", "Sea-Doo", "Kawasaki", "BRP", "Quicksilver", "Bayliner", "Sea Ray", "Beneteau", "Jeanneau", "Bavaria", "Zodiac", "Yamaran", "Gladiator", "Admiral", "Solar", "Flinc", "Fregat", "Hunterboat", "Intex", "Bestway"],
  aircraft: ["Cessna", "Piper", "Beechcraft", "Cirrus", "Diamond", "Tecnam", "Pipistrel", "Robinson", "Bell", "Airbus", "Leonardo", "Sikorsky", "MD Helicopters", "Schleicher", "Schempp-Hirth", "DG Aviation", "Yak", "Antonov", "Mil", "Kamov"],
  stationery: ["ErichKrause", "Brauberg", "Deli", "Comix", "Faber-Castell", "Stabilo", "Staedtler", "BIC", "Pilot", "Pentel", "Uni", "Parker", "Lamy", "Maped", "Centrum", "ArtSpace", "Hatber", "Koh-i-Noor"],
  homewares: ["IKEA", "Tefal", "Rondell", "BergHOFF", "Fissler", "WMF", "Zwilling", "Victorinox", "Tescoma", "Luminarc", "Pasabahce", "Pyrex", "Duralex", "Villeroy and Boch", "Le Creuset", "Staub", "Lock and Lock", "Sistema", "Curver", "Brabantia", "Leifheit", "Vileda", "Joseph Joseph", "Fiskars", "Gipfel", "Kukmara", "Fissman", "Nadoba"],
  homeTextile: ["IKEA", "Togas", "TAC", "Karaca Home", "English Home", "Madame Coco", "Arya", "Mona Liza", "Verossa", "Askona", "Ormatek"],
  lighting: ["Philips", "Signify", "Osram", "Ledvance", "Gauss", "Navigator", "Camelion", "Feron", "Jazzway", "Era", "Eglo", "Maytoni", "Odeon Light", "Arlight", "IEK", "Schneider Electric", "ABB", "Legrand", "EKF", "TDM Electric"],
  network: ["TP-Link", "D-Link", "ASUS", "Keenetic", "MikroTik", "Ubiquiti", "Cisco", "HPE Aruba", "Huawei", "ZTE", "Zyxel", "Netgear", "Tenda", "Mercusys", "Xiaomi", "Ugreen", "Baseus"],
  peripheral: ["Logitech", "Razer", "SteelSeries", "HyperX", "Corsair", "ASUS", "MSI", "A4Tech", "Bloody", "Defender", "Genius", "Redragon", "Keychron", "Akko", "Varmilo", "Ducky", "Apple", "Microsoft", "Dell", "HP", "Lenovo", "Rapoo", "Trust"],
  mobileAccessory: ["Apple", "Samsung", "Huawei", "Xiaomi", "Honor", "OPPO", "Vivo", "realme", "Anker", "Baseus", "Ugreen", "Belkin", "Spigen", "Nillkin", "ESR", "OtterBox", "Ringke", "Hoco", "Borofone", "Mophie", "Satechi"],
  mediaPlayer: ["Apple", "Google", "Xiaomi", "NVIDIA", "Amazon", "Roku", "Dune HD", "Zidoo", "Ugoos", "Mecool", "Tanix", "Vontar", "Sony", "Panasonic", "Samsung", "LG", "Pioneer"],
  cosmetics: ["LOreal Paris", "Maybelline", "Garnier", "Nivea", "Dove", "Rexona", "Schwarzkopf", "Syoss", "Wella", "Estel", "Kapous", "Matrix", "Ollin", "TRESemme", "Pantene", "Head and Shoulders", "Elseve", "Kerastase", "La Roche-Posay", "Vichy", "CeraVe", "Bioderma", "Avene", "Uriage", "Eucerin", "Clinique", "Clarins", "Estee Lauder", "Lancome", "Chanel", "Dior", "Guerlain", "Yves Saint Laurent", "Shiseido", "MAC", "NYX", "Essence", "Catrice", "Bourjois", "Vivienne Sabo", "Art-Visage", "Belita", "Vitex", "The Ordinary", "COSRX", "Some By Mi", "Beauty of Joseon", "Skin1004", "Round Lab", "Anua", "Missha", "Mizon", "Etude", "Innisfree"],
  cleaning: ["Ariel", "Persil", "Tide", "Losk", "Dosia", "BiMax", "Sorti", "Fairy", "Finish", "Somat", "Pril", "AOS", "Frosch", "Synergetic", "Meine Liebe", "BioMio", "Laska", "Lenor", "Vernel", "Domestos", "Cif", "Cillit Bang", "Mr. Proper", "Mr. Muscle", "Bref", "Sanfor", "Grass", "Bagi", "HG", "Glade", "Air Wick", "Raid", "Raptor", "Mosquitall", "Gardex"],
  babyHygiene: ["Pampers", "Huggies", "Merries", "Moony", "Goon", "YokoSun", "Lovular", "Joonies", "Manu", "Momi", "Offspring", "Chicco", "Mustela", "Bubchen", "Weleda", "Johnson Baby", "Avent", "Pigeon", "Sanosan", "BabyLine"],
  food: ["Rahat", "Bayan Sulu", "RG Brands", "FoodMaster", "Lactel", "Adal", "Shin-Line", "Danone", "Nestle", "Nesquik", "Nescafe", "Jacobs", "Lavazza", "Illy", "Jardin", "Tchibo", "Ahmad Tea", "Greenfield", "Tess", "Lipton", "Piala", "Assam", "Coca-Cola", "Pepsi", "Fanta", "Sprite", "Borjomi", "Saryagash", "Tassay", "ASU", "Aksai Nan", "Makfa", "Barilla", "Heinz", "Bonduelle", "Kuhmaster"],
  garden: ["Gardena", "Fiskars", "Hozelock", "Karcher", "Palissad", "Raco", "Green Belt", "Fertika", "Fasco", "Buyskie Udobreniya", "August", "Bayer", "Syngenta", "BASF", "Seminis", "Rijk Zwaan", "Gavrish", "SeDeK", "Aelita", "Poisk", "Intex", "Bestway", "Gre", "Mountfield"],
  sports: ["Nike", "Adidas", "Puma", "Reebok", "Under Armour", "Demix", "Torneo", "Sole", "ProForm", "NordicTrack", "Life Fitness", "Matrix", "Technogym", "Horizon", "Oxygen", "Body Solid", "DFC", "Decathlon", "Domyos", "Kettler", "Wilson", "Head", "Babolat", "Yonex", "Dunlop", "Butterfly", "Donic", "Stiga", "Joola", "Spalding", "Molten", "Mikasa", "Select", "Wilson", "Everlast", "Venum", "Twins", "Fairtex", "Green Hill", "Salomon", "Atomic", "Fischer", "Rossignol", "Head", "Elan", "Blizzard", "Burton", "Jones", "K2", "Bauer", "CCM", "Rollerblade", "Powerslide", "Oxelo", "Speedo", "Arena", "TYR", "Aqua Sphere"],
  watch: ["Casio", "Seiko", "Citizen", "Orient", "Tissot", "Certina", "Hamilton", "Swatch", "Longines", "Rado", "Omega", "Rolex", "Tag Heuer", "Breitling", "Hublot", "Cartier", "Patek Philippe", "Audemars Piguet", "Breguet", "Ulysse Nardin", "Fossil", "Michael Kors", "Daniel Wellington", "Diesel", "Skagen"],
  jewelry: ["Pandora", "Swarovski", "Sokolov", "Sunlight", "Adamas", "Bronnitsky Yuvelir", "Kostroma", "Karas", "Damiani", "Chopard", "Bulgari", "Cartier", "Tiffany and Co", "Van Cleef and Arpels", "Tous", "Nomination"],
  printing: ["HP", "Canon", "Epson", "Brother", "Xerox", "Ricoh", "Kyocera", "Konica Minolta", "Sharp", "Toshiba", "Pantum", "OKI", "Lexmark", "Zebra", "Honeywell", "Dymo", "Deli", "Fujitsu"],
  industrial: ["Siemens", "ABB", "Schneider Electric", "Omron", "Mitsubishi Electric", "Fanuc", "Yaskawa", "Delta", "Festo", "SMC", "Bosch Rexroth", "Danfoss", "Grundfos", "Wilo", "KSB", "Pedrollo", "Ebara", "Calpeda", "Atlas Copco", "Kaeser", "Fubag", "Denzel", "Resanta", "Huter", "Patriot", "Champion", "Makita", "DeWalt", "Bosch", "Metabo", "Jet", "Stalex", "Metal Master", "Optimum", "Proma", "Holzmann", "Griggio", "SCM", "Homag", "Biesse", "Felder", "Juki", "Brother", "Jack", "Typical", "Siruba", "Zoje", "Aurora"],
  medical: ["GE HealthCare", "Philips", "Siemens Healthineers", "Canon Medical", "Mindray", "SonoScape", "Chison", "Edan", "Bionet", "Baxter", "Fresenius", "Drager", "B. Braun", "Omron", "Beurer", "B.Well", "A and D", "Nihon Kohden", "Olympus", "Karl Storz", "Pentax Medical", "Dentsply Sirona", "Kavo", "NSK", "W and H", "Planmeca", "Vatech", "Woodpecker", "Invacare", "Ortonica", "Armed", "Med-Mos"],
  foodEquipment: ["Abat", "Atesy", "Rational", "Unox", "Electrolux Professional", "Fagor", "Hendi", "Hurakan", "Gastrorag", "Robot Coupe", "Sammic", "Sirman", "Fimar", "Bartscher", "Convotherm", "Retigo", "Frymaster", "Pitco", "Scotsman", "Hoshizaki", "Polair", "Ariada", "Carboma", "Italfrost", "Biryusa", "Kifato", "Ugur", "La Marzocco", "Nuova Simonelli", "Victoria Arduino", "Rancilio", "Faema", "La Cimbali", "Astoria", "Sanremo", "Jura", "WMF", "Saeco"],
  retail: ["Atol", "Shtrih-M", "Evotor", "Mercury", "Posiflex", "Sunmi", "iiko", "R-Keeper", "CAS", "Mettler Toledo", "Massa-K", "Acom", "Dibal", "Bizerba", "Zebra", "Honeywell", "Datalogic", "Newland", "TSC", "Godex"],
  construction: ["Knauf", "Ceresit", "Weber", "Bergauf", "Volma", "Unis", "Starateli", "AlinEX", "Alina Paint", "Tikkurila", "Dulux", "Dufa", "Marshall", "Caparol", "Sniezka", "Eskaro", "Soudal", "Penosil", "Makroflex", "Tytan", "Moment", "Henkel", "Technonicol", "Rockwool", "Isover", "Ursa", "Penoplex", "Baswool", "Grand Line", "Metal Profil", "Onduline", "Docke", "Rehau", "Veka", "KBE", "Salamander", "Alutech", "DoorHan", "Hormann", "Grohe", "Hansgrohe", "Roca", "Cersanit", "IKEA", "Lemax", "Baxi", "Vaillant", "Protherm", "Navien", "Viessmann", "Buderus", "Ariston", "Thermex", "Grundfos", "Wilo"],
  trailer: ["Schmitz Cargobull", "Krone", "Kogel", "Wielton", "Schwarzmuller", "Fliegl", "Faymonville", "Goldhofer", "Nooteboom", "Tirsan", "Kassbohrer", "Tonar", "MAZ", "SZAP", "NEFAZ", "Grunwald", "MZSA", "Kurgan", "Krepysh", "Respo", "Tiki Treiler", "Brenderup", "Humbaur", "AL-KO"],
  kidsElectric: ["Peg Perego", "RiverToys", "Barty", "Wingo", "Toyland", "Rastar", "Chi Lok Bo", "Rollplay", "Injusa", "Feber", "Falk", "Polesie"],
  sled: ["Nika", "Demi", "Bars", "Small Rider", "Snowkat", "Stiga", "Hamax", "KHW", "Prosperplast", "Plastkon", "TiM-Sport"],
  bags: ["Samsonite", "American Tourister", "Wenger", "Victorinox", "Tumi", "Roncato", "Delsey", "Rimowa", "Xiaomi", "Ninetygo", "Mark Ryden", "Herschel", "Eastpak", "Fjallraven", "Deuter", "Osprey", "Thule", "Dakine", "Tigernu", "Caribee", "Roxy", "Michael Kors", "Coach", "Furla", "Guess", "DKNY", "Coccinelle", "Longchamp", "Louis Vuitton", "Prada", "Gucci", "Dior", "Chanel", "Zara", "Mango"],
  safes: ["Valberg", "Aiko", "Technomax", "Burg-Wachter", "Yale", "Chubbsafes", "SentrySafe", "Diplomat", "Onix", "Safetronics", "Juwel"],
  agriculture: ["DeLaval", "GEA", "Lely", "BouMatic", "Big Dutchman", "Roxell", "Fancom", "SKOV", "Petersime", "Pas Reform", "Pellon", "Riberi", "John Deere", "Claas", "Kuhn", "Krone", "Kverneland", "Amazone", "Horsch", "Lemken", "Pottinger", "Vaderstad", "Monosem", "Great Plains", "Buhler", "Netafim", "Rain Bird", "Rivulis", "Jain Irrigation", "Galcon", "Gardena"],
  salon: ["Wahl", "Moser", "Babyliss", "Andis", "Oster", "JRL", "Dewal", "Harizma", "Sibel", "Gamma Piu", "Takara Belmont", "Olymp", "Maletti", "Gamma and Bross", "Yamaguchi", "US Medica", "Gess", "Beurer", "Marathon", "Strong", "Saeshin", "Podomaster", "Gehwol", "Scholl", "SUNUV", "Irisk", "TNL", "Runail", "Emil", "Dikson", "Silver Fox", "Alvi Prague", "Mediostar", "Candela", "Lumenis", "Alma", "Cynosure", "Fotona", "Cheyenne", "Bishop", "FK Irons", "Dragonhawk", "Mast", "Ambition"],
  rawMetal: ["Qarmet", "Kazzinc", "Kazakhmys", "ERG", "Kazchrome", "TMK", "Severstal", "NLMK", "MMK", "Mechel", "EVRAZ", "ArcelorMittal", "Nucor", "Outokumpu", "Rusal"],
  rawWood: ["Kronospan", "Swiss Krono", "Kastamonu", "Egger", "Kronostar", "SVEZA", "UPM", "Metsä Wood", "Stora Enso"],
  rawPlastic: ["SIBUR", "KPI", "KazMunayGas", "BASF", "Dow", "SABIC", "LyondellBasell", "Borealis", "Ineos", "Formosa Plastics", "LG Chem"],
  rawTextile: ["DMC", "Anchor", "Alize", "YarnArt", "Nako", "Gazzal", "Himalaya", "Lanoso", "Pekhorka", "Kamteks", "Gamma", "Gutermann", "Madeira"],
} as const;
export type ManufacturerGroup = keyof typeof manufacturerGroups;

export function manufacturerOptions(group: ManufacturerGroup): SeedAttributeOption[] {
  return [...new Map(named(manufacturerGroups[group]).map(option => [option.value, option])).values(),
    { value: "unbranded", label: { ru: "Без бренда", kk: "Брендсіз" } },
    { value: "other", label: { ru: "Другой бренд", kk: "Басқа бренд" } },
  ];
}

export function manufacturerFields(group: ManufacturerGroup): SeedAttributeDefinition[] {
  const options = manufacturerOptions(group);
  return [
    { key: "brand", label: { ru: "Бренд", kk: "Бренд" }, dataType: "select", filterable: true,
      searchable: true, filterMode: "exact", options, optionsLoadMode: options.length > 60 ? "deferred" : "eager", validation: { dictionary: `manufacturer.${group}` } },
    { key: "brand_other", label: { ru: "Укажите бренд", kk: "Брендті көрсетіңіз" }, dataType: "text", searchable: true,
      validation: { maxLength: 80, placeholder: { ru: "Название производителя на товаре", kk: "Тауардағы өндіруші атауы" },
        visibleWhen: { key: "brand", values: ["other"] }, requiredWhen: { key: "brand", values: ["other"] } } },
  ];
}
