import type { SeedAttributeDefinition as Attribute, SeedAttributeOption as Option } from "./category-attribute-schemas.ts";
import { manufacturerFields } from "./manufacturer-options.ts";
const op = (value: string, ru: string, kk: string): Option => ({ value, label: { ru, kk } });
const select = (key: string, ru: string, kk: string, options: Option[]): Attribute => ({ key, label: { ru, kk }, dataType: "select", filterable: true, filterMode: "exact", options });
const number = (key: string, ru: string, kk: string, unit: string, max: number): Attribute => ({ key, label: { ru, kk }, dataType: "number", filterable: true, filterMode: "range", unit: { ru: unit, kk: unit }, validation: { min: 0, max } });
const model: Attribute = { key: "model", label: { ru: "Модель / артикул", kk: "Модель / артикул" }, dataType: "text", searchable: true, validation: { maxLength: 100, placeholder: { ru: "Маркировка производителя на изделии", kk: "Бұйымдағы өндірушінің таңбалауы" } } };
const condition = select("condition", "Состояние", "Күйі", [op("new", "Новое", "Жаңа"), op("like-new", "Как новое", "Жаңа сияқты"), op("used", "Б/у", "Қолданылған"), op("repair", "Требует ремонта", "Жөндеуді қажет етеді")]);
const base: Attribute[] = [...manufacturerFields("sports"), model, { ...condition, required: true }];
const type = (options: Option[]) => select("product_type", "Тип инвентаря", "Жабдық түрі", options);
const level = select("skill_level", "Уровень", "Деңгейі", [op("beginner", "Начальный", "Бастапқы"), op("intermediate", "Средний", "Орта"), op("advanced", "Продвинутый", "Жоғары"), op("professional", "Профессиональный", "Кәсіби")]);
export const sportsProfiles = {
  fitnessEquipment: [...base, type([op("treadmill","Беговая дорожка","Жүгіру жолы"), op("bike","Велотренажёр","Велотренажер"), op("elliptical","Эллиптический тренажёр","Эллипстік тренажер"), op("rowing","Гребной тренажёр","Ескек тренажері"), op("strength","Силовой тренажёр","Күш тренажері"), op("weights","Гантели / штанги / гири","Гантель / штанга / гір"), op("bench","Скамья / стойка","Орындық / тіреу"), op("bands","Эспандер / резинки","Эспандер / резеңке"), op("mat","Коврик","Кілемше"), op("other","Другое","Басқа")]), number("max_user_weight","Максимальный вес пользователя","Пайдаланушының ең жоғары салмағы","кг",500), number("equipment_weight","Вес инвентаря","Жабдық салмағы","кг",5000), { key:"foldable",label:{ru:"Складной",kk:"Жиналмалы"},dataType:"boolean",filterable:true }],
  winterSports: [...base, type([op("alpine-skis","Горные лыжи","Тау шаңғысы"),op("cross-country-skis","Беговые лыжи","Жүгіру шаңғысы"),op("snowboard","Сноуборд","Сноуборд"),op("boots","Ботинки","Бәтеңке"),op("bindings","Крепления","Бекіткіштер"),op("poles","Палки","Таяқтар"),op("skates","Коньки","Коньки"),op("sled","Санки / тюбинг","Шана / тюбинг"),op("other","Другое","Басқа")]), level,
    { ...number("length","Длина лыж / доски / палок","Шаңғы / тақта / таяқ ұзындығы","см",300), validation:{min:30,max:300,visibleWhen:{key:"product_type",values:["alpine-skis","cross-country-skis","snowboard","poles"]}} },
    { ...select("boot_size","Размер ботинка (Mondopoint, см)","Бәтеңке өлшемі (Mondopoint, см)",Array.from({length:43},(_,i)=>15+i/2).map(n=>op(String(n),String(n),String(n)))), validation:{visibleWhen:{key:"product_type",values:["boots","skates"]}} }],
  racketSports: [...base, select("sport","Вид спорта","Спорт түрі",[op("tennis","Теннис","Теннис"),op("table-tennis","Настольный теннис","Үстел теннисі"),op("badminton","Бадминтон","Бадминтон"),op("squash","Сквош","Сквош"),op("padel","Падел","Падел")]),type([op("racket","Ракетка","Ракетка"),op("balls","Мячи / воланы","Доп / волан"),op("net","Сетка","Тор"),op("table","Стол","Үстел"),op("accessory","Аксессуары","Аксессуарлар")]),level],
  teamSports: [...base, select("sport","Вид спорта","Спорт түрі",[op("football","Футбол","Футбол"),op("basketball","Баскетбол","Баскетбол"),op("volleyball","Волейбол","Волейбол"),op("hockey","Хоккей","Хоккей"),op("handball","Гандбол","Гандбол"),op("rugby","Регби","Регби"),op("baseball","Бейсбол","Бейсбол"),op("other","Другой","Басқа")]),type([op("ball","Мяч / шайба","Доп / шайба"),op("goal","Ворота / кольцо","Қақпа / сақина"),op("net","Сетка","Тор"),op("stick","Клюшка / бита","Таяқ / бита"),op("equipment","Экипировка","Жабдық"),op("other","Другое","Басқа")])],
  combatSports: [...base,select("sport","Вид спорта","Спорт түрі",[op("boxing","Бокс","Бокс"),op("mma","MMA","MMA"),op("wrestling","Борьба","Күрес"),op("judo","Дзюдо","Дзюдо"),op("karate","Карате","Карате"),op("taekwondo","Тхэквондо","Таэквондо"),op("other","Другой","Басқа")]),type([op("gloves","Перчатки","Қолғап"),op("bag","Мешок / груша","Қап / алмұрт"),op("pads","Лапы / макивара","Лапа / макивара"),op("uniform","Кимоно / форма","Кимоно / киім"),op("protection","Защита","Қорғаныс"),op("mat","Татами / маты","Татами / төсеніш"),op("other","Другое","Басқа")])],
  waterSports: [...base,type([op("swimming","Плавательный инвентарь","Жүзу жабдығы"),op("sup","SUP-доска","SUP тақтасы"),op("surf","Доска для сёрфинга","Серфинг тақтасы"),op("kayak","Каяк","Каяк"),op("diving","Дайвинг / снорклинг","Дайвинг / снорклинг"),op("wetsuit","Гидрокостюм","Гидрокостюм"),op("life-jacket","Спасательный жилет","Құтқару кеудешесі"),op("other","Другое","Басқа")]),level],
  skatingSports: [...base,type([op("inline-skates","Ролики","Ролик"),op("skateboard","Скейтборд","Скейтборд"),op("longboard","Лонгборд","Лонгборд"),op("cruiser","Круизер","Круизер"),op("parts","Запчасти","Қосалқы бөлшектер")]),level],
  sportProtection: [...base,type([op("helmet","Шлем","Дулыға"),op("knee","Наколенники","Тізеқап"),op("elbow","Налокотники","Шынтаққап"),op("wrist","Защита запястья","Білек қорғанысы"),op("body","Защита корпуса","Дене қорғанысы"),op("set","Комплект","Жинақ"),op("other","Другое","Басқа")]),select("size","Размер","Өлшем",["XS","S","M","L","XL","XXL"].map(n=>op(n.toLowerCase(),n,n)))],
} satisfies Record<string, Attribute[]>;
