import { familyModelFields } from "./computer-model-options.ts";
import { kartFamilies } from "./wearable-console-options.ts";
import type { SeedAttributeDefinition as Attribute, SeedAttributeOption as Option } from "./category-attribute-schemas.ts";
import { manufacturerFields, type ManufacturerGroup } from "./manufacturer-options.ts";
const op = (value: string, ru: string, kk: string): Option => ({ value, label: { ru, kk } });
const select = (key: string, ru: string, kk: string, options: Option[]): Attribute => ({ key, label: { ru, kk }, dataType: "select", filterable: true, filterMode: "exact", options });
const number = (key: string, ru: string, kk: string, unit: string, max: number): Attribute => ({ key, label: { ru, kk }, dataType: "number", filterable: true, filterMode: "range", unit: { ru: unit, kk: unit }, validation: { min: 0, max } });
const when = (attribute: Attribute, values: string[]): Attribute => ({ ...attribute, validation: { ...attribute.validation, visibleWhen: { key: "supply_type", values } } });
const condition = select("condition", "Состояние", "Күйі", [op("new", "Новое", "Жаңа"), op("like-new", "Как новое", "Жаңа сияқты"), op("used", "Б/у", "Қолданылған"), op("repair", "Требует ремонта", "Жөндеуді қажет етеді")]);
const model: Attribute = { key: "model", label: { ru: "Модель / артикул", kk: "Модель / артикул" }, dataType: "text", searchable: true, validation: { maxLength: 100, placeholder: { ru: "Маркировка модели на изделии", kk: "Бұйымдағы модель таңбалауы" } } };
const dimensions: Attribute[] = [number("width", "Ширина", "Ені", "см", 10000), number("height", "Высота", "Биіктігі", "см", 10000), number("depth", "Глубина / длина", "Тереңдігі / ұзындығы", "см", 10000)];
const base = (group: ManufacturerGroup): Attribute[] => [...manufacturerFields(group), model, { ...condition, required: true }, { key: "delivery", label: { ru: "Есть доставка", kk: "Жеткізу бар" }, dataType: "boolean", filterable: true }];
const types = (options: Option[]): Attribute[] => [
  { ...select("supply_type", "Тип товара / оборудования", "Тауар / жабдық түрі", [...options, op("other", "Другое", "Басқа")]), required: true },
  { key: "supply_type_other", label: { ru: "Укажите тип", kk: "Түрін көрсетіңіз" }, dataType: "text", searchable: true, validation: { maxLength: 100, placeholder: { ru: "Название типа изделия", kk: "Бұйым түрінің атауы" }, visibleWhen: { key: "supply_type", values: ["other"] }, requiredWhen: { key: "supply_type", values: ["other"] } } },
];
const animals = select("animal_type", "Для какого животного", "Қай жануарға", [op("cat", "Кошки", "Мысықтар"), op("dog", "Собаки", "Иттер"), op("bird", "Птицы", "Құстар"), op("fish", "Рыбы", "Балықтар"), op("rodent", "Грызуны", "Кеміргіштер"), op("reptile", "Рептилии", "Бауырымен жорғалаушылар"), op("farm", "Сельхозживотные", "Ауыл шаруашылық жануарлары"), op("universal", "Универсальный", "Әмбебап")]);
const material = select("material", "Материал", "Материалы", [op("plastic", "Пластик", "Пластик"), op("metal", "Металл", "Металл"), op("wood", "Дерево", "Ағаш"), op("glass", "Стекло", "Шыны"), op("textile", "Ткань", "Мата"), op("leather", "Кожа", "Былғары"), op("rubber", "Резина / силикон", "Резеңке / силикон"), op("mixed", "Комбинированный", "Аралас"), op("other", "Другой", "Басқа")]);
const petBase = [...base("petAccessory"), animals, material];
const waterBase = [...base("aquarium"), material];
const volume = number("capacity", "Объём", "Көлемі", "л", 1000000);
const power = number("power", "Мощность", "Қуаты", "Вт", 100000);

// Leaf profiles replace inappropriate inherited aquarium/tractor fields at the
// catalog layer. Old persisted values are preserved by release preflight guards.
export const subjectSpecificProfiles = {
  petCage: [...petBase, ...types([op("cage", "Клетка", "Тор"), op("aviary", "Вольер", "Қоршау"), op("feeder", "Кормушка / поилка", "Астау / суарғыш"), op("accessory", "Аксессуар для клетки", "Тор аксессуары")]), ...dimensions, when(number("bar_spacing", "Расстояние между прутьями", "Шыбықтар аралығы", "мм", 200), ["cage", "aviary"])],
  aquariumTank: [...waterBase, ...types([op("aquarium", "Аквариум", "Аквариум"), op("cabinet", "Тумба", "Тұғыр"), op("set", "Комплект с тумбой", "Тұғырмен жинақ")]), when(volume, ["aquarium", "set"]), ...dimensions],
  aquariumEquipment: [...waterBase, ...types([op("filter", "Фильтр", "Сүзгі"), op("pump", "Помпа", "Сорғы"), op("compressor", "Компрессор", "Компрессор"), op("heater", "Нагреватель", "Жылытқыш"), op("light", "Освещение", "Жарықтандыру"), op("co2", "Система CO₂", "CO₂ жүйесі"), op("feeder", "Автокормушка", "Автоматты жемдегіш")]), when(power, ["filter", "pump", "compressor", "heater", "light", "feeder"]), number("recommended_volume", "Рекомендуемый объём аквариума", "Ұсынылатын аквариум көлемі", "л", 1000000), when(number("flow_rate", "Производительность", "Өнімділігі", "л/ч", 100000), ["filter", "pump", "compressor"])],
  aquariumDecor: [...waterBase, ...types([op("substrate", "Грунт", "Топырақ"), op("plant", "Растения", "Өсімдіктер"), op("stone", "Камни", "Тастар"), op("wood", "Коряги", "Ағаш бұтақтары"), op("ornament", "Декорации", "Безендіру"), op("background", "Фон", "Фон")]), ...dimensions, number("net_weight", "Вес", "Салмағы", "кг", 10000)],
  terrariumEquipment: [...petBase, ...types([op("terrarium", "Террариум", "Террариум"), op("heater", "Обогреватель / коврик", "Жылытқыш / төсеніш"), op("light", "Лампа", "Шам"), op("humidifier", "Увлажнитель", "Ылғалдандырғыш"), op("decor", "Декор / укрытие", "Безендіру / баспана")]), ...dimensions, when(power, ["heater", "light", "humidifier"])],
  petBed: [...petBase, ...types([op("bed", "Лежанка", "Төсек"), op("house", "Домик", "Үйшік"), op("booth", "Будка", "Күрке"), op("scratching-post", "Когтеточка / комплекс", "Тырнағыш / кешен")]), ...dimensions],
  petCarrier: [...petBase, ...types([op("box", "Бокс / клетка", "Бокс / тор"), op("bag", "Сумка", "Сөмке"), op("backpack", "Рюкзак", "Арқасөмке")]), ...dimensions, number("max_pet_weight", "Максимальный вес животного", "Жануардың ең жоғары салмағы", "кг", 200)],
  petHarness: [...petBase, ...types([op("collar", "Ошейник", "Қарғыбау"), op("leash", "Поводок", "Жетек"), op("harness", "Шлейка", "Әбзел"), op("muzzle", "Намордник", "Тұмылдырық"), op("id-tag", "Адресник", "Мекенжай белгісі")]), when(number("length", "Длина", "Ұзындығы", "см", 10000), ["leash"]), when(number("circumference", "Обхват", "Орамы", "см", 200), ["collar", "harness", "muzzle"])],
  petToy: [...petBase, ...types([op("ball", "Мяч", "Доп"), op("chew", "Жевательная игрушка", "Шайнайтын ойыншық"), op("teaser", "Дразнилка", "Қызықтыратын ойыншық"), op("puzzle", "Интерактивная игрушка", "Интерактивті ойыншық"), op("training", "Инвентарь для дрессировки", "Үйрету жабдығы")]), ...dimensions],
  petGrooming: [...petBase, ...types([op("brush", "Щётка / расчёска", "Щетка / тарақ"), op("clipper", "Машинка", "Қырқу машинасы"), op("scissors", "Ножницы / когтерез", "Қайшы / тырнақ кескіш"), op("shampoo", "Шампунь / уход", "Сусабын / күтім"), op("hygiene", "Гигиенические товары", "Гигиеналық тауарлар")]), when(power, ["clipper"]), when(number("net_volume", "Объём средства", "Құрал көлемі", "мл", 100000), ["shampoo"])],
  petVeterinary: [...base("petAccessory"), animals, ...types([op("instrument", "Инструменты", "Құралдар"), op("dressing", "Перевязочные материалы", "Таңу материалдары"), op("protective", "Защитный воротник / попона", "Қорғаныс жағасы / жамылғы"), op("care", "Средства ухода", "Күтім құралдары")])],
  irrigationEquipment: [...base("irrigation"), ...types([op("drip", "Капельный полив", "Тамшылатып суару"), op("sprinkler", "Дождевальная установка", "Жаңбырлатқыш қондырғы"), op("pump", "Насосная станция", "Сорғы станциясы"), op("controller", "Контроллер", "Контроллер"), op("hose", "Трубы / шланги", "Құбырлар / шлангтер"), op("filter", "Фильтрация", "Сүзу")]), number("flow_rate", "Расход воды", "Су шығыны", "м³/ч", 100000), number("working_pressure", "Рабочее давление", "Жұмыс қысымы", "бар", 1000), number("coverage_area", "Площадь полива", "Суару ауданы", "га", 100000), when(power, ["pump"])],
  livestockEquipment: [...base("livestockEquipment"), ...types([op("milking", "Доильное оборудование", "Сауын жабдығы"), op("feeding", "Кормление / поение", "Азықтандыру / суару"), op("housing", "Стойловое оборудование", "Қора жабдығы"), op("incubator", "Инкубатор", "Инкубатор"), op("ventilation", "Вентиляция / климат", "Желдету / климат"), op("manure", "Навозоудаление", "Көң тазалау")]), animals, when(power, ["milking", "feeding", "incubator", "ventilation", "manure"]), ...dimensions],
  goKart: [...base("kart").filter(field => field.key !== "model"), ...familyModelFields(kartFamilies), { ...number("year", "Год выпуска", "Шығарылған жылы", "год", 2100), unit: { ru: "год", kk: "жыл" }, validation: { min: 1900, max: 2100 } }, select("engine_type", "Тип двигателя", "Қозғалтқыш түрі", [op("petrol", "Бензиновый", "Бензинді"), op("electric", "Электрический", "Электрлі"), op("none", "Шасси без двигателя", "Қозғалтқышсыз шасси")]), { ...number("engine_volume", "Объём двигателя", "Қозғалтқыш көлемі", "см³", 2000), validation: { min: 1, max: 2000, visibleWhen: { key: "engine_type", values: ["petrol"] } } }, select("kart_use", "Назначение", "Мақсаты", [op("rental", "Прокатный", "Жалға беру"), op("racing", "Спортивный", "Спорттық"), op("recreational", "Любительский", "Әуесқойлық")])],
} satisfies Record<string, Attribute[]>;
