export type VehicleBrandReference = {
  value: string;
  label: { ru: string; kk: string };
};

const brand = (value: string, name: string): VehicleBrandReference => ({
  value,
  label: { ru: name, kk: name },
});

// Curated passenger-vehicle reference source used by the deterministic seed.
// Runtime UI receives these options from Supabase, never from this module.
export const passengerVehicleBrands: VehicleBrandReference[] = [
  brand("acura", "Acura"),
  brand("alfa-romeo", "Alfa Romeo"),
  brand("alpina", "Alpina"),
  brand("aito", "AITO"),
  brand("arcfox", "ARCFOX"),
  brand("aston-martin", "Aston Martin"),
  brand("audi", "Audi"),
  brand("aurus", "Aurus"),
  brand("avatr", "Avatr"),
  brand("baic", "BAIC"),
  brand("bentley", "Bentley"),
  brand("bestune", "Bestune"),
  brand("bmw", "BMW"),
  brand("brilliance", "Brilliance"),
  brand("bugatti", "Bugatti"),
  brand("buick", "Buick"),
  brand("byd", "BYD"),
  brand("cadillac", "Cadillac"),
  brand("changan", "Changan"),
  brand("changhe", "Changhe"),
  brand("chery", "Chery"),
  brand("chevrolet", "Chevrolet"),
  brand("chrysler", "Chrysler"),
  brand("citroen", "Citroën"),
  brand("cupra", "CUPRA"),
  brand("dacia", "Dacia"),
  brand("daewoo", "Daewoo"),
  brand("daihatsu", "Daihatsu"),
  brand("datsun", "Datsun"),
  brand("deepal", "Deepal"),
  brand("denza", "Denza"),
  brand("dodge", "Dodge"),
  brand("dongfeng", "Dongfeng"),
  brand("ds", "DS Automobiles"),
  brand("exeed", "EXEED"),
  brand("faw", "FAW"),
  brand("ferrari", "Ferrari"),
  brand("fiat", "Fiat"),
  brand("fisker", "Fisker"),
  brand("ford", "Ford"),
  brand("foton", "Foton"),
  brand("gac", "GAC"),
  brand("gaz", "ГАЗ"),
  brand("geely", "Geely"),
  brand("genesis", "Genesis"),
  brand("gmc", "GMC"),
  brand("great-wall", "Great Wall"),
  brand("haima", "Haima"),
  brand("haval", "Haval"),
  brand("honda", "Honda"),
  brand("hongqi", "Hongqi"),
  brand("hummer", "Hummer"),
  brand("hyundai", "Hyundai"),
  brand("ineos", "INEOS"),
  brand("infiniti", "Infiniti"),
  brand("iran-khodro", "Iran Khodro"),
  brand("isuzu", "Isuzu"),
  brand("iveco", "Iveco"),
  brand("jac", "JAC"),
  brand("jaecoo", "JAECOO"),
  brand("jaguar", "Jaguar"),
  brand("jeep", "Jeep"),
  brand("jetour", "Jetour"),
  brand("jetta", "Jetta"),
  brand("kaiyi", "KAIYI"),
  brand("kgm", "KGM"),
  brand("kia", "Kia"),
  brand("lamborghini", "Lamborghini"),
  brand("lancia", "Lancia"),
  brand("lada", "Lada"),
  brand("land-rover", "Land Rover"),
  brand("leapmotor", "Leapmotor"),
  brand("lexus", "Lexus"),
  brand("li-auto", "Li Auto"),
  brand("lifan", "Lifan"),
  brand("lincoln", "Lincoln"),
  brand("lotus", "Lotus"),
  brand("lucid", "Lucid"),
  brand("luxeed", "Luxeed"),
  brand("lynk-co", "Lynk & Co"),
  brand("maserati", "Maserati"),
  brand("maxus", "Maxus"),
  brand("maybach", "Maybach"),
  brand("mazda", "Mazda"),
  brand("mclaren", "McLaren"),
  brand("mercedes-benz", "Mercedes-Benz"),
  brand("mercury", "Mercury"),
  brand("mg", "MG"),
  brand("mini", "MINI"),
  brand("mitsubishi", "Mitsubishi"),
  brand("moskvich", "Москвич"),
  brand("neta", "Neta"),
  brand("nio", "NIO"),
  brand("nissan", "Nissan"),
  brand("oldsmobile", "Oldsmobile"),
  brand("omoda", "OMODA"),
  brand("opel", "Opel"),
  brand("ora", "ORA"),
  brand("pagani", "Pagani"),
  brand("peugeot", "Peugeot"),
  brand("plymouth", "Plymouth"),
  brand("polestar", "Polestar"),
  brand("pontiac", "Pontiac"),
  brand("porsche", "Porsche"),
  brand("proton", "Proton"),
  brand("ram", "RAM"),
  brand("ravon", "Ravon"),
  brand("renault", "Renault"),
  brand("rising-auto", "Rising Auto"),
  brand("rivian", "Rivian"),
  brand("rolls-royce", "Rolls-Royce"),
  brand("rover", "Rover"),
  brand("saab", "Saab"),
  brand("saturn", "Saturn"),
  brand("scion", "Scion"),
  brand("seat", "SEAT"),
  brand("seres", "SERES"),
  brand("skoda", "Škoda"),
  brand("skywell", "Skywell"),
  brand("smart", "Smart"),
  brand("soueast", "Soueast"),
  brand("ssangyong", "SsangYong"),
  brand("subaru", "Subaru"),
  brand("suzuki", "Suzuki"),
  brand("tank", "TANK"),
  brand("tata", "Tata"),
  brand("tesla", "Tesla"),
  brand("toyota", "Toyota"),
  brand("uaz", "УАЗ"),
  brand("vauxhall", "Vauxhall"),
  brand("volkswagen", "Volkswagen"),
  brand("volvo", "Volvo"),
  brand("voyah", "VOYAH"),
  brand("wey", "WEY"),
  brand("wuling", "Wuling"),
  brand("xiaomi", "Xiaomi Auto"),
  brand("xpeng", "XPeng"),
  brand("zaz", "ЗАЗ"),
  brand("zeekr", "ZEEKR"),
  brand("zotye", "Zotye"),
  { value: "other", label: { ru: "Другая марка", kk: "Басқа марка" } },
];
