import { passengerVehicleModels, type DependentReferenceOption } from "./dependent-options.ts";

export type PassengerBody = "sedan" | "suv" | "hatchback" | "liftback" | "wagon" | "minivan" | "coupe" | "cabriolet" | "pickup" | "other";

type ScopeEntry = readonly [body: PassengerBody, brand: string, models: readonly string[]];

/**
 * Reviewed body/model source of truth. A model may occur in several real body
 * variants. Models not yet safely classifiable are exposed only in the explicit
 * "other body" leaf instead of being guessed into every passenger-car leaf.
 */
const scopeEntries: ScopeEntry[] = [
  ["sedan", "alfa-romeo", ["156", "159", "Giulia"]],
  ["sedan", "audi", ["80", "100", "A3", "A4", "A6", "A8", "S4", "S6"]],
  ["sedan", "avatr", ["12"]],
  ["sedan", "baic", ["EU5", "U5 Plus"]],
  ["sedan", "bentley", ["Flying Spur", "Mulsanne"]],
  ["sedan", "bestune", ["B70"]],
  ["sedan", "bmw", ["3 Series", "5 Series", "7 Series", "i5", "i7"]],
  ["sedan", "byd", ["Destroyer 05", "Han", "Qin Plus", "Seal"]],
  ["sedan", "cadillac", ["ATS", "CT4", "CT5", "CT6"]],
  ["sedan", "changan", ["Alsvin", "Eado Plus", "UNI-V"]],
  ["sedan", "chery", ["Arrizo 5", "Arrizo 6", "Arrizo 8"]],
  ["sedan", "chevrolet", ["Aveo", "Cobalt", "Cruze", "Epica", "Lacetti", "Malibu", "Nexia", "Onix"]],
  ["sedan", "chrysler", ["200", "300C", "Sebring"]],
  ["sedan", "citroen", ["C4", "C5", "C-Elysee"]],
  ["sedan", "daewoo", ["Espero", "Gentra", "Lanos", "Leganza", "Nexia", "Nubira"]],
  ["sedan", "dodge", ["Charger", "Neon", "Stratus"]],
  ["sedan", "dongfeng", ["Aeolus Shine", "Aeolus Yixuan", "Shine Max"]],
  ["sedan", "faw", ["Besturn B50", "Bestune B70"]],
  ["sedan", "fiat", ["Albea", "Linea", "Tipo"]],
  ["sedan", "ford", ["Escort", "Focus", "Fusion", "Mondeo"]],
  ["sedan", "gac", ["Empow"]],
  ["sedan", "gaz", ["21 Волга", "24 Волга", "3102 Волга", "3110 Волга"]],
  ["sedan", "geely", ["Emgrand", "Preface"]],
  ["sedan", "genesis", ["G70", "G80", "G90"]],
  ["sedan", "honda", ["Accord", "City", "Civic", "Insight", "Integra", "Legend"]],
  ["sedan", "hongqi", ["H5", "H6", "H9"]],
  ["sedan", "hyundai", ["Accent", "Avante", "Elantra", "Equus", "Genesis", "Grandeur", "Solaris", "Sonata", "Verna"]],
  ["sedan", "infiniti", ["G", "M", "Q50", "Q70"]],
  ["sedan", "jac", ["J7"]],
  ["sedan", "jaguar", ["S-Type", "XE", "XF", "XJ", "X-Type"]],
  ["sedan", "kia", ["Cerato", "K5", "K7", "K8", "K9", "Magentis", "Opirus", "Optima", "Rio", "Spectra", "Stinger"]],
  ["sedan", "lada", ["2101", "2105", "2106", "2107", "2108", "2109", "21099", "2110", "2112", "2113", "2114", "2115", "Granta", "Kalina", "Priora", "Vesta"]],
  ["sedan", "lexus", ["ES", "GS", "HS", "IS", "LS"]],
  ["sedan", "mazda", ["3", "6", "626"]],
  ["sedan", "mercedes-benz", ["A-Class", "C-Class", "CLA", "CLS", "E-Class", "S-Class"]],
  ["sedan", "mitsubishi", ["Carisma", "Diamante", "Galant", "Lancer"]],
  ["sedan", "nissan", ["Almera", "Altima", "Bluebird", "Maxima", "Primera", "Sentra", "Skyline", "Teana"]],
  ["sedan", "omoda", ["S5"]],
  ["sedan", "opel", ["Astra", "Insignia", "Kadett", "Omega", "Vectra"]],
  ["sedan", "peugeot", ["301", "406", "407", "408", "508"]],
  ["sedan", "porsche", ["Panamera", "Taycan"]],
  ["sedan", "ravon", ["Gentra", "Nexia R3", "R4"]],
  ["sedan", "renault", ["Fluence", "Logan", "Megane", "Symbol"]],
  ["sedan", "skoda", ["Octavia", "Rapid", "Superb"]],
  ["sedan", "subaru", ["Impreza", "Legacy", "WRX"]],
  ["sedan", "tesla", ["Model 3", "Model S"]],
  ["sedan", "toyota", ["Avalon", "Avensis", "Camry", "Carina", "Corolla", "Crown", "Mark II", "Prius", "Yaris"]],
  ["sedan", "volkswagen", ["Bora", "Jetta", "Passat", "Phaeton", "Polo"]],
  ["sedan", "volvo", ["S40", "S60", "S80", "S90"]],

  ["suv", "acura", ["MDX", "RDX", "ZDX"]],
  ["suv", "alfa-romeo", ["Stelvio", "Tonale"]],
  ["suv", "audi", ["Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "e-tron"]],
  ["suv", "avatr", ["07", "11"]],
  ["suv", "baic", ["BJ20", "BJ40", "BJ60", "X35", "X55", "X7"]],
  ["suv", "bentley", ["Bentayga"]],
  ["suv", "bestune", ["B70S", "T55", "T77", "T90"]],
  ["suv", "bmw", ["X1", "X2", "X3", "X4", "X5", "X6", "X7", "XM", "iX", "iX1", "iX3"]],
  ["suv", "byd", ["Atto 3", "Song L", "Song Plus", "Tang", "Yuan Plus"]],
  ["suv", "cadillac", ["Escalade", "SRX", "XT4", "XT5", "XT6"]],
  ["suv", "changan", ["CS35 Plus", "CS55 Plus", "CS75 Plus", "CS85 Coupe", "CS95", "UNI-K", "UNI-T"]],
  ["suv", "chery", ["Tiggo 2", "Tiggo 4", "Tiggo 7", "Tiggo 7 Pro", "Tiggo 8", "Tiggo 8 Pro", "Tiggo 9"]],
  ["suv", "chevrolet", ["Blazer", "Captiva", "Equinox", "Niva", "Tahoe", "Tracker", "TrailBlazer"]],
  ["suv", "citroen", ["C3 Aircross", "C5 Aircross"]],
  ["suv", "daihatsu", ["Rocky", "Terios"]],
  ["suv", "dodge", ["Durango", "Journey", "Nitro"]],
  ["suv", "dongfeng", ["580", "DFSK 500", "DFSK 600", "Huge"]],
  ["suv", "exeed", ["LX", "RX", "TXL", "VX"]],
  ["suv", "faw", ["Besturn X40", "Besturn X80", "Bestune T55", "Bestune T77", "Bestune T90"]],
  ["suv", "ford", ["Bronco", "EcoSport", "Edge", "Escape", "Everest", "Expedition", "Explorer", "Kuga"]],
  ["suv", "gac", ["GS3", "GS4", "GS5", "GS8"]],
  ["suv", "geely", ["Atlas", "Atlas Pro", "Coolray", "Emgrand X7", "Geometry C", "Monjaro", "Okavango", "Tugella"]],
  ["suv", "genesis", ["GV60", "GV70", "GV80"]],
  ["suv", "great-wall", ["Hover H3", "Hover H5", "Hover H6", "Safe"]],
  ["suv", "haval", ["Dargo", "F7", "F7x", "H2", "H5", "H6", "H9", "Jolion", "M6", "Raptor"]],
  ["suv", "honda", ["Avancier", "CR-V", "Crosstour", "HR-V", "Pilot", "Vezel"]],
  ["suv", "hongqi", ["E-HS9", "HS3", "HS5", "HS7"]],
  ["suv", "hyundai", ["Bayon", "Creta", "Kona", "Palisade", "Santa Fe", "Terracan", "Tucson", "Venue"]],
  ["suv", "infiniti", ["EX", "FX", "JX", "QX30", "QX50", "QX55", "QX56", "QX60", "QX70", "QX80"]],
  ["suv", "isuzu", ["MU-X", "Trooper", "VehiCross"]],
  ["suv", "jac", ["JS3", "JS4", "JS5", "JS6", "S3", "S5"]],
  ["suv", "jaecoo", ["J7", "J8"]],
  ["suv", "jaguar", ["E-Pace", "F-Pace", "I-Pace"]],
  ["suv", "jeep", ["Cherokee", "Commander", "Compass", "Grand Cherokee", "Liberty", "Patriot", "Renegade", "Wrangler"]],
  ["suv", "jetour", ["Dashing", "T1", "T2", "X70", "X70 Plus", "X90 Plus"]],
  ["suv", "kia", ["EV6", "EV9", "Mohave", "Niro", "Seltos", "Sorento", "Soul", "Sportage"]],
  ["suv", "lada", ["4x4", "Niva", "Niva Travel", "XRAY"]],
  ["suv", "land-rover", ["Defender", "Discovery", "Discovery Sport", "Freelander", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"]],
  ["suv", "lexus", ["GX", "LX", "NX", "RX", "RZ", "UX"]],
  ["suv", "li-auto", ["L6", "L7", "L8", "L9", "One"]],
  ["suv", "mazda", ["CX-3", "CX-30", "CX-5", "CX-7", "CX-8", "CX-9", "CX-50", "CX-60", "CX-90", "Tribute"]],
  ["suv", "mercedes-benz", ["EQA", "EQB", "EQC", "EQE", "EQS", "G-Class", "GL", "GLA", "GLB", "GLC", "GLE", "GLK", "GLS", "M-Class"]],
  ["suv", "mitsubishi", ["ASX", "Eclipse Cross", "Montero", "Outlander", "Pajero", "Pajero iO", "Pajero Sport", "RVR"]],
  ["suv", "nissan", ["Armada", "Juke", "Kicks", "Murano", "Pathfinder", "Patrol", "Qashqai", "Terrano", "X-Trail"]],
  ["suv", "omoda", ["C5", "C7"]],
  ["suv", "opel", ["Antara", "Crossland", "Frontera", "Grandland", "Mokka"]],
  ["suv", "peugeot", ["2008", "3008", "4007", "5008"]],
  ["suv", "porsche", ["Cayenne", "Macan"]],
  ["suv", "renault", ["Arkana", "Captur", "Duster", "Kaptur", "Koleos"]],
  ["suv", "skoda", ["Karoq", "Kodiaq", "Yeti"]],
  ["suv", "subaru", ["Ascent", "Forester", "Outback", "Tribeca", "XV"]],
  ["suv", "suzuki", ["Escudo", "Grand Vitara", "Ignis", "Jimny", "S-Cross", "Vitara"]],
  ["suv", "tesla", ["Model X", "Model Y"]],
  ["suv", "toyota", ["4Runner", "C-HR", "Fortuner", "Harrier", "Highlander", "Land Cruiser", "Land Cruiser Prado", "RAV4", "Sequoia", "Venza"]],
  ["suv", "uaz", ["3151", "469", "Hunter", "Patriot"]],
  ["suv", "volkswagen", ["ID.4", "ID.6", "Taos", "Teramont", "Tiguan", "Touareg"]],
  ["suv", "volvo", ["C40", "XC40", "XC60", "XC70", "XC90"]],
  ["suv", "zeekr", ["7X", "X"]],

  ["hatchback", "alfa-romeo", ["145", "146", "147", "Giulietta"]],
  ["hatchback", "audi", ["A1", "A3"]],
  ["hatchback", "bmw", ["1 Series", "i3"]],
  ["hatchback", "byd", ["Dolphin", "Seagull"]],
  ["hatchback", "chevrolet", ["Aveo", "Lacetti", "Matiz", "Spark"]],
  ["hatchback", "citroen", ["C3", "C4"]],
  ["hatchback", "daewoo", ["Matiz", "Tico"]],
  ["hatchback", "daihatsu", ["Boon", "Cast", "Cuore", "Mira", "Sirion", "Tanto"]],
  ["hatchback", "fiat", ["500", "Bravo", "Panda", "Punto", "Tipo"]],
  ["hatchback", "ford", ["Fiesta", "Focus"]],
  ["hatchback", "geely", ["Emgrand"]],
  ["hatchback", "honda", ["Civic", "Fit", "Jazz"]],
  ["hatchback", "hyundai", ["Atos", "Getz", "i10", "i20", "i30", "Ioniq", "Veloster"]],
  ["hatchback", "kia", ["Ceed", "Morning", "Picanto", "ProCeed", "Rio"]],
  ["hatchback", "lada", ["2108", "2109", "2112", "2113", "2114", "Granta", "Kalina", "Priora", "Vesta", "XRAY"]],
  ["hatchback", "lexus", ["CT"]],
  ["hatchback", "mazda", ["2", "3", "Demio"]],
  ["hatchback", "mercedes-benz", ["A-Class", "B-Class"]],
  ["hatchback", "mitsubishi", ["Colt", "Lancer", "Space Star"]],
  ["hatchback", "nissan", ["Cube", "Leaf", "Micra", "Note", "Tiida"]],
  ["hatchback", "opel", ["Astra", "Corsa", "Kadett"]],
  ["hatchback", "peugeot", ["206", "207", "208", "307", "308"]],
  ["hatchback", "ravon", ["Matiz", "R2"]],
  ["hatchback", "renault", ["Clio", "Megane", "Sandero"]],
  ["hatchback", "skoda", ["Fabia", "Scala"]],
  ["hatchback", "subaru", ["Impreza"]],
  ["hatchback", "suzuki", ["Alto", "Baleno", "Celerio", "Swift", "Wagon R"]],
  ["hatchback", "toyota", ["Auris", "Corolla", "Passo", "Prius", "Vitz", "Yaris"]],
  ["hatchback", "volkswagen", ["Beetle", "Golf", "ID.3", "Polo"]],
  ["hatchback", "volvo", ["C30", "V40"]],

  ["liftback", "audi", ["A5", "A7"]],
  ["liftback", "bmw", ["4 Series", "6 Series", "i4"]],
  ["liftback", "changan", ["UNI-V"]],
  ["liftback", "jac", ["J7"]],
  ["liftback", "kia", ["Stinger"]],
  ["liftback", "porsche", ["Panamera", "Taycan"]],
  ["liftback", "skoda", ["Octavia", "Rapid", "Superb"]],
  ["liftback", "tesla", ["Model S"]],
  ["liftback", "volkswagen", ["Arteon"]],
  ["liftback", "zeekr", ["001", "007"]],

  ["wagon", "audi", ["A4", "A6"]],
  ["wagon", "bmw", ["3 Series", "5 Series"]],
  ["wagon", "ford", ["Focus", "Mondeo"]],
  ["wagon", "lada", ["2104", "2111", "Largus", "Vesta"]],
  ["wagon", "mercedes-benz", ["C-Class", "E-Class"]],
  ["wagon", "opel", ["Astra", "Insignia", "Vectra"]],
  ["wagon", "skoda", ["Fabia", "Octavia", "Superb"]],
  ["wagon", "subaru", ["Legacy", "Levorg", "Outback"]],
  ["wagon", "toyota", ["Avensis", "Corolla"]],
  ["wagon", "volkswagen", ["Golf", "Passat"]],
  ["wagon", "volvo", ["V40", "V60", "V70", "V90", "XC70"]],

  ["minivan", "chrysler", ["Grand Voyager", "Pacifica", "Town & Country", "Voyager"]],
  ["minivan", "chevrolet", ["Damas", "Orlando"]],
  ["minivan", "citroen", ["Berlingo", "C4 Picasso", "Jumpy", "Xsara Picasso"]],
  ["minivan", "daihatsu", ["Atrai", "Hijet"]],
  ["minivan", "fiat", ["Doblo", "Ducato"]],
  ["minivan", "ford", ["C-Max", "Galaxy", "S-Max", "Tourneo", "Transit"]],
  ["minivan", "gac", ["M8"]],
  ["minivan", "gaz", ["Газель", "Газель NEXT", "Соболь", "Соболь NN"]],
  ["minivan", "honda", ["Elysion", "Freed", "Odyssey", "Stepwgn", "Stream"]],
  ["minivan", "hyundai", ["H-1", "Matrix", "Staria"]],
  ["minivan", "kia", ["Carens", "Carnival"]],
  ["minivan", "lada", ["Largus"]],
  ["minivan", "lexus", ["LM"]],
  ["minivan", "li-auto", ["Mega"]],
  ["minivan", "mazda", ["5", "MPV", "Premacy"]],
  ["minivan", "mercedes-benz", ["R-Class", "Sprinter", "V-Class", "Viano", "Vito"]],
  ["minivan", "mitsubishi", ["Delica", "Grandis"]],
  ["minivan", "nissan", ["Elgrand", "Serena"]],
  ["minivan", "opel", ["Meriva", "Sintra", "Vivaro", "Zafira"]],
  ["minivan", "peugeot", ["Partner", "Traveller"]],
  ["minivan", "renault", ["Espace", "Kangoo", "Master", "Scenic", "Trafic"]],
  ["minivan", "suzuki", ["Solio"]],
  ["minivan", "toyota", ["Alphard", "Ipsum", "Noah", "Sienna"]],
  ["minivan", "uaz", ["2206", "3303", "452", "Profi"]],
  ["minivan", "volkswagen", ["Caddy", "Caravelle", "Crafter", "Multivan", "Sharan", "Touran", "Transporter"]],
  ["minivan", "zeekr", ["009", "Mix"]],

  ["coupe", "acura", ["CL", "Integra"]],
  ["coupe", "audi", ["A5", "TT"]],
  ["coupe", "bentley", ["Continental GT"]],
  ["coupe", "bmw", ["2 Series", "4 Series", "6 Series", "8 Series"]],
  ["coupe", "chevrolet", ["Camaro"]],
  ["coupe", "dodge", ["Challenger"]],
  ["coupe", "honda", ["Civic", "Integra", "Prelude"]],
  ["coupe", "infiniti", ["G", "Q60"]],
  ["coupe", "jaguar", ["F-Type"]],
  ["coupe", "lexus", ["LC", "RC"]],
  ["coupe", "mazda", ["MX-5"]],
  ["coupe", "mercedes-benz", ["C-Class", "CLA", "CLC", "CLK", "CLS", "E-Class", "S-Class"]],
  ["coupe", "mitsubishi", ["Eclipse"]],
  ["coupe", "nissan", ["350Z", "370Z", "GT-R", "Skyline"]],
  ["coupe", "opel", ["Calibra"]],
  ["coupe", "porsche", ["718", "911", "Cayman"]],
  ["coupe", "subaru", ["BRZ"]],
  ["coupe", "toyota", ["Celica", "Supra"]],
  ["coupe", "volkswagen", ["Beetle"]],

  ["cabriolet", "audi", ["A5", "TT"]],
  ["cabriolet", "bentley", ["Continental GT"]],
  ["cabriolet", "bmw", ["2 Series", "4 Series", "8 Series", "Z4"]],
  ["cabriolet", "chevrolet", ["Camaro"]],
  ["cabriolet", "daihatsu", ["Copen"]],
  ["cabriolet", "fiat", ["500"]],
  ["cabriolet", "jaguar", ["F-Type"]],
  ["cabriolet", "mazda", ["MX-5"]],
  ["cabriolet", "mercedes-benz", ["CLK", "SL", "SLC", "SLK"]],
  ["cabriolet", "porsche", ["718", "911", "Boxster"]],
  ["cabriolet", "volkswagen", ["Beetle"]],

  ["pickup", "dodge", ["Dakota", "RAM"]],
  ["pickup", "dongfeng", ["DF6", "Rich"]],
  ["pickup", "ford", ["F-150", "Ranger"]],
  ["pickup", "great-wall", ["Deer", "Poer", "Wingle 5", "Wingle 7"]],
  ["pickup", "honda", ["Ridgeline"]],
  ["pickup", "isuzu", ["D-Max"]],
  ["pickup", "jac", ["T6", "T8", "T9"]],
  ["pickup", "mitsubishi", ["L200"]],
  ["pickup", "nissan", ["Frontier", "Navara"]],
  ["pickup", "tesla", ["Cybertruck"]],
  ["pickup", "toyota", ["Hilux", "Tacoma", "Tundra"]],
  ["pickup", "uaz", ["Pickup", "Profi"]],
  ["pickup", "volkswagen", ["Amarok"]],
];

const scopes = new Map<string, Set<PassengerBody>>();
for (const [body, brand, labels] of scopeEntries) {
  for (const label of labels) {
    const key = `${brand}\u0000${label}`;
    const existing = scopes.get(key) ?? new Set<PassengerBody>();
    existing.add(body);
    scopes.set(key, existing);
  }
}

export const passengerVehicleBodyScopes = new Map<string, readonly PassengerBody[]>();
for (const option of passengerVehicleModels) {
  if (!option.parentValue) continue;
  const key = `${option.parentValue}\u0000${option.label.ru}`;
  passengerVehicleBodyScopes.set(option.value, [...(scopes.get(key) ?? new Set<PassengerBody>(["other"]))]);
}

export const passengerVehicleModelsByBody = Object.fromEntries(
  (["sedan", "suv", "hatchback", "liftback", "wagon", "minivan", "coupe", "cabriolet", "pickup", "other"] as const)
    .map((body) => [body, passengerVehicleModels.filter((option) =>
      option.value === "other-model" || passengerVehicleBodyScopes.get(option.value)?.includes(body))]),
) as Record<PassengerBody, DependentReferenceOption[]>;

export const vehicleBodyReference = {
  checkedAt: "2026-08-28",
  strategy: "reviewed-explicit-multi-body",
  fallbackBody: "other",
} as const;
