import {env} from 'cloudflare:workers';
import {createSupabaseServerClient} from '@/lib/supabase/server';
import type {Locale} from '@/lib/i18n/messages';
const labels:Record<string,[string,string]>={runs_total:['Проверок за 30 дней','30 күндегі тексерулер'],approved:['Автоматически опубликовано','Автоматты жарияланған'],rejected:['Автоматически отклонено','Автоматты қабылданбаған'],needs_fix:['Нужно исправить','Түзету қажет'],human_review:['Неопределённые','Қосымша тексеру'],deterministic_rejects:['Отклонено локальными правилами','Жергілікті ережемен қабылданбаған'],ai_assisted_rejects:['Отклонено с AI-наблюдением','AI дерегімен қабылданбаған'],provider_error:['Ошибки проверки','Тексеру қателері'],average_processing_ms:['Среднее время, мс','Орташа уақыт, мс'],admin_overrides:['Ручных решений','Қолмен қабылданған шешімдер'],auto_approve_manual_reject:['Автоодобрение → ручной отказ','Автоматты мақұлдау → қолмен бас тарту'],auto_reject_manual_approve:['Автоотказ → ручное одобрение','Автоматты бас тарту → қолмен мақұлдау'],input_tokens:['Входные токены','Кіріс токендері'],output_tokens:['Выходные токены','Шығыс токендері']};
export async function ModerationMetrics({locale}:{locale:Locale}){
 const {data,error}=await(await createSupabaseServerClient()).rpc('moderation_admin',{operation:'queue'});
 if(error)return <p>{locale==='kk'?'Көрсеткіштер қолжетімсіз':'Метрики недоступны'}</p>;
 const q=data as unknown as {metrics:Record<string,number|null>;switches:Record<string,boolean|string|number>};
 return <details className="dashboard-card"><summary>{locale==='kk'?'Көрсеткіштер және басқару күйі':'Метрики и состояние переключателей'}</summary><dl>{Object.entries(labels).map(([key,label])=><div key={key}><dt>{label[locale==='kk'?1:0]}</dt><dd>{q.metrics[key]===null||q.metrics[key]===undefined?'—':Math.round(q.metrics[key]!)}</dd></div>)}</dl><p>{locale==='kk'?'Дерекқордағы басқару':'Управление в БД'}: {JSON.stringify(q.switches)}</p><p>Worker: AUTOMATIC={env.MODERATION_AUTOMATIC_ENABLED==='true'?'ON':'OFF'} · APPROVAL={env.MODERATION_AUTOMATIC_APPROVAL_ENABLED==='true'?'ON':'OFF'} · REJECTION={env.MODERATION_AUTOMATIC_REJECTION_ENABLED==='true'?'ON':'OFF'} · EXTERNAL_AI={env.MODERATION_EXTERNAL_AI_ENABLED==='true'?'ON':'OFF'} · SHADOW={env.MODERATION_AI_SHADOW_MODE==='false'?'OFF':'ON'}</p></details>;
}
