import { branch, leaf, leaves, overlay, type CatalogEntry, type MasterCatalogNode } from "./types.ts";

const jobLeaves = (entries: readonly CatalogEntry[]) => leaves(entries, ["job"]);

export const jobsCatalogOverlays: MasterCatalogNode[] = [
  overlay("jobs", [
    overlay("jobs-logistics", jobLeaves([
      ["jobs-driver", "Водитель", "Жүргізуші"],
      ["jobs-courier", "Курьер", "Курьер"],
      ["jobs-loader", "Грузчик", "Жүк тиеуші"],
      ["jobs-warehouse-worker", "Кладовщик и комплектовщик", "Қоймашы және жинақтаушы"],
      ["jobs-dispatcher", "Диспетчер", "Диспетчер"],
      ["jobs-logistics-manager", "Логист", "Логист"],
      ["jobs-freight-forwarder", "Экспедитор", "Экспедитор"],
    ]), ["job"]),
    overlay("jobs-sales", jobLeaves([
      ["jobs-salesperson", "Продавец-консультант", "Сатушы-кеңесші"],
      ["jobs-cashier", "Кассир", "Кассир"],
      ["jobs-sales-manager", "Менеджер по продажам", "Сату менеджері"],
      ["jobs-procurement", "Специалист по закупкам", "Сатып алу маманы"],
      ["jobs-merchandiser", "Мерчендайзер", "Мерчендайзер"],
      ["jobs-real-estate-agent", "Риелтор", "Риелтор"],
      ["jobs-call-center", "Оператор call-центра", "Call-орталық операторы"],
    ]), ["job"]),
    overlay("jobs-construction", jobLeaves([
      ["jobs-general-builder", "Строитель", "Құрылысшы"],
      ["jobs-finisher", "Отделочник", "Әрлеуші"],
      ["jobs-electrician", "Электрик", "Электрик"],
      ["jobs-plumber", "Сантехник", "Сантехник"],
      ["jobs-welder", "Сварщик", "Дәнекерлеуші"],
      ["jobs-mason", "Каменщик", "Тас қалаушы"],
      ["jobs-roofer", "Кровельщик", "Шатыр маманы"],
      ["jobs-hvac-technician", "Монтажник вентиляции и кондиционеров", "Желдету және кондиционер монтажшысы"],
      ["jobs-construction-engineer", "Инженер и прораб", "Инженер және прораб"],
    ]), ["job"]),
    overlay("jobs-production", jobLeaves([
      ["jobs-machine-operator", "Оператор станка", "Станок операторы"],
      ["jobs-production-operator", "Оператор производства", "Өндіріс операторы"],
      ["jobs-fitter", "Слесарь", "Слесарь"],
      ["jobs-mechanic", "Механик", "Механик"],
      ["jobs-packer", "Упаковщик", "Ораушы"],
      ["jobs-technologist", "Технолог", "Технолог"],
      ["jobs-quality-controller", "Контролёр качества", "Сапа бақылаушысы"],
      ["jobs-laborer", "Разнорабочий", "Әртүрлі жұмысшы"],
    ]), ["job"]),
    overlay("jobs-it", jobLeaves([
      ["jobs-software-developer", "Разработчик", "Бағдарламашы"],
      ["jobs-system-administrator", "Системный администратор", "Жүйелік әкімші"],
      ["jobs-it-support", "Техническая поддержка", "Техникалық қолдау"],
      ["jobs-qa", "Тестировщик", "Тестілеуші"],
      ["jobs-ui-ux", "UI/UX-дизайнер", "UI/UX дизайнері"],
      ["jobs-data-analyst", "Аналитик данных", "Деректер талдаушысы"],
      ["jobs-project-manager-it", "IT project manager", "IT жоба менеджері"],
      ["jobs-telecom", "Связь и телеком", "Байланыс және телеком"],
    ]), ["job"]),
    overlay("jobs-finance", jobLeaves([
      ["jobs-accountant", "Бухгалтер", "Бухгалтер"],
      ["jobs-financial-analyst", "Финансовый аналитик", "Қаржы талдаушысы"],
      ["jobs-economist", "Экономист", "Экономист"],
      ["jobs-auditor", "Аудитор", "Аудитор"],
      ["jobs-bank-specialist", "Банковский специалист", "Банк маманы"],
      ["jobs-insurance", "Страхование", "Сақтандыру"],
    ]), ["job"]),
    overlay("jobs-education", jobLeaves([
      ["jobs-teacher", "Учитель", "Мұғалім"],
      ["jobs-kindergarten-teacher", "Воспитатель", "Тәрбиеші"],
      ["jobs-tutor", "Преподаватель и репетитор", "Оқытушы және репетитор"],
      ["jobs-methodologist", "Методист", "Әдіскер"],
      ["jobs-researcher", "Научный сотрудник", "Ғылыми қызметкер"],
      ["jobs-education-administrator", "Администратор учебного центра", "Оқу орталығының әкімшісі"],
    ]), ["job"]),
    overlay("jobs-medicine", jobLeaves([
      ["jobs-doctor", "Врач", "Дәрігер"],
      ["jobs-nurse", "Медсестра и медбрат", "Мейіргер"],
      ["jobs-pharmacist", "Фармацевт", "Фармацевт"],
      ["jobs-dentistry", "Стоматология", "Стоматология"],
      ["jobs-lab-technician", "Лаборант", "Зертхана маманы"],
      ["jobs-medical-administrator", "Администратор клиники", "Клиника әкімшісі"],
      ["jobs-veterinary", "Ветеринария", "Ветеринария"],
    ]), ["job"]),
    overlay("jobs-horeca", jobLeaves([
      ["jobs-cook", "Повар", "Аспаз"],
      ["jobs-waiter", "Официант", "Даяшы"],
      ["jobs-barista", "Бариста и бармен", "Бариста және бармен"],
      ["jobs-kitchen-worker", "Работник кухни", "Ас үй қызметкері"],
      ["jobs-hotel-administrator", "Администратор гостиницы", "Қонақүй әкімшісі"],
      ["jobs-housekeeper", "Горничная", "Бөлме жинаушы"],
      ["jobs-restaurant-manager", "Менеджер ресторана", "Мейрамхана менеджері"],
    ]), ["job"]),
    overlay("jobs-security", jobLeaves([
      ["jobs-security-guard", "Охранник", "Күзетші"],
      ["jobs-cctv-operator", "Оператор видеонаблюдения", "Бейнебақылау операторы"],
      ["jobs-safety-engineer", "Инженер по охране труда", "Еңбекті қорғау инженері"],
      ["jobs-fire-safety", "Пожарная безопасность", "Өрт қауіпсіздігі"],
      ["jobs-bodyguard", "Личная охрана", "Жеке күзет"],
    ]), ["job"]),
    overlay("jobs-domestic", jobLeaves([
      ["jobs-nanny", "Няня", "Бала күтуші"],
      ["jobs-caregiver", "Сиделка", "Күтуші"],
      ["jobs-house-cleaner", "Домработница", "Үй қызметшісі"],
      ["jobs-private-driver", "Личный водитель", "Жеке жүргізуші"],
      ["jobs-cook-home", "Домашний повар", "Үй аспазы"],
      ["jobs-gardener", "Садовник", "Бағбан"],
    ]), ["job"]),
    overlay("jobs-agriculture", jobLeaves([
      ["jobs-agronomist", "Агроном", "Агроном"],
      ["jobs-tractor-driver", "Тракторист-машинист", "Тракторшы-машинист"],
      ["jobs-farm-worker", "Работник фермы", "Ферма жұмысшысы"],
      ["jobs-livestock-specialist", "Животновод", "Мал шаруашылығы маманы"],
      ["jobs-greenhouse", "Работник теплицы", "Жылыжай жұмысшысы"],
      ["jobs-seasonal-agro", "Сезонные сельхозработы", "Маусымдық ауыл шаруашылық жұмыстары"],
    ]), ["job"]),
    overlay("jobs-office", jobLeaves([
      ["jobs-office-administrator", "Администратор офиса", "Кеңсе әкімшісі"],
      ["jobs-secretary", "Секретарь и ассистент", "Хатшы және ассистент"],
      ["jobs-hr", "HR и кадры", "HR және кадрлар"],
      ["jobs-document-specialist", "Делопроизводитель", "Іс жүргізуші"],
      ["jobs-receptionist", "Ресепшионист", "Ресепшионист"],
      ["jobs-manager", "Руководитель", "Басшы"],
    ]), ["job"]),
    overlay("jobs-marketing", jobLeaves([
      ["jobs-marketer", "Маркетолог", "Маркетолог"],
      ["jobs-smm", "SMM-специалист", "SMM маманы"],
      ["jobs-content-manager", "Контент-менеджер", "Контент менеджері"],
      ["jobs-designer", "Графический дизайнер", "Графикалық дизайнер"],
      ["jobs-copywriter", "Копирайтер", "Копирайтер"],
      ["jobs-pr", "PR и коммуникации", "PR және коммуникациялар"],
      ["jobs-advertising-manager", "Менеджер по рекламе", "Жарнама менеджері"],
    ]), ["job"]),
    overlay("jobs-temporary", jobLeaves([
      ["jobs-promoter", "Промоутер", "Промоутер"],
      ["jobs-event-staff", "Персонал на мероприятия", "Іс-шара қызметкерлері"],
      ["jobs-day-labor", "Ежедневная подработка", "Күнделікті қосымша жұмыс"],
      ["jobs-seasonal", "Сезонная работа", "Маусымдық жұмыс"],
      ["jobs-student", "Работа для студентов", "Студенттерге арналған жұмыс"],
    ]), ["job"]),
    overlay("jobs-remote", jobLeaves([
      ["jobs-remote-support", "Удалённая поддержка", "Қашықтан қолдау"],
      ["jobs-remote-sales", "Удалённые продажи", "Қашықтан сату"],
      ["jobs-remote-it", "Удалённая IT-работа", "Қашықтан IT жұмысы"],
      ["jobs-remote-content", "Удалённый контент и дизайн", "Қашықтан контент және дизайн"],
      ["jobs-remote-teaching", "Онлайн-преподавание", "Онлайн оқыту"],
    ]), ["job"]),
    branch("jobs-law", "Юриспруденция", "Құқық", jobLeaves([
      ["jobs-lawyer", "Юрист", "Заңгер"],
      ["jobs-legal-assistant", "Помощник юриста", "Заңгер көмекшісі"],
      ["jobs-compliance", "Комплаенс", "Комплаенс"],
      ["jobs-contract-specialist", "Договорная работа", "Шарттық жұмыс"],
    ]), ["job"]),
    branch("jobs-beauty", "Красота и фитнес", "Сұлулық және фитнес", jobLeaves([
      ["jobs-hairdresser", "Парикмахер", "Шаштараз"],
      ["jobs-nail-master", "Мастер маникюра", "Маникюр шебері"],
      ["jobs-beautician", "Косметолог", "Косметолог"],
      ["jobs-massage-therapist", "Массажист", "Массажшы"],
      ["jobs-fitness-trainer", "Фитнес-тренер", "Фитнес жаттықтырушысы"],
    ]), ["job"]),
  ], ["job"]),
];

export const realEstateCatalogOverlays: MasterCatalogNode[] = [
  overlay("real-estate", [
    overlay("property-sale", [
      leaf("flats-sale", "Квартиры", "Пәтерлер", ["flatSale"]),
      leaf("houses-sale", "Дома и коттеджи", "Үйлер мен коттедждер", ["house"]),
      leaf("rooms-sale", "Комнаты и доли", "Бөлмелер мен үлестер", ["room"]),
      leaf("land-sale", "Земельные участки", "Жер телімдері", ["land"]),
      leaf("commercial-sale", "Коммерческая недвижимость", "Коммерциялық жылжымайтын мүлік", ["commercialProperty"]),
      leaf("garages-sale", "Гаражи и парковочные места", "Гараждар мен автотұрақ орындары", ["garage"]),
      leaf("dachas-sale", "Дачи", "Саяжайлар", ["house"]),
      leaf("townhouses-sale", "Таунхаусы", "Таунхаустар", ["house"]),
      leaf("unfinished-property-sale", "Недостроенные объекты", "Аяқталмаған нысандар", ["house"]),
    ]),
    overlay("property-rent", [
      leaf("flats-rent", "Квартиры", "Пәтерлер", ["flatSale", "rentTerms"]),
      leaf("houses-rent", "Дома и коттеджи", "Үйлер мен коттедждер", ["house", "rentTerms"]),
      leaf("rooms-rent", "Комнаты", "Бөлмелер", ["room", "rentTerms"]),
      leaf("commercial-rent", "Коммерческие помещения", "Коммерциялық орындар", ["commercialProperty", "rentTerms"]),
      leaf("garages-rent", "Гаражи и парковки", "Гараждар мен тұрақтар", ["garage", "rentTerms"]),
      leaf("land-rent", "Земельные участки", "Жер телімдері", ["land", "rentTerms"]),
    ]),
    overlay("property-daily", [
      leaf("flats-daily", "Квартиры", "Пәтерлер", ["flatSale", "dailyTerms"]),
      leaf("houses-daily", "Дома и коттеджи", "Үйлер мен коттедждер", ["house", "dailyTerms"]),
      leaf("rooms-daily", "Комнаты", "Бөлмелер", ["room", "dailyTerms"]),
      leaf("guest-houses-daily", "Гостевые дома", "Қонақ үйлер", ["house", "dailyTerms"]),
      leaf("hostels-daily", "Хостелы и койко-места", "Хостелдер мен төсек-орындар", ["room", "dailyTerms"]),
    ]),
    branch("property-new-buildings", "Новостройки от застройщиков", "Құрылыс салушылардан жаңа үйлер", [
      leaf("new-build-flats", "Квартиры в новостройках", "Жаңа үйлердегі пәтерлер", ["flatSale"]),
      leaf("new-build-commercial", "Коммерческие помещения", "Коммерциялық орындар", ["commercialProperty"]),
    ]),
  ]),
];
