import { branch, fallbackLeaf, leaves, overlay, type CatalogEntry, type MasterCatalogNode } from "./types.ts";

const serviceLeaves = (entries: readonly CatalogEntry[], profiles: readonly string[] = ["serviceBase"]) =>
  leaves(entries, profiles.includes("serviceProfessional") ? profiles : [...profiles, "serviceProfessional"]);

export const servicesCatalogOverlays: MasterCatalogNode[] = [
  overlay("services", [
    overlay("repair-construction-services", [
      overlay("apartment-renovation", serviceLeaves([
        ["renovation-turnkey", "Ремонт под ключ", "Толық жөндеу"],
        ["renovation-cosmetic", "Косметический ремонт", "Косметикалық жөндеу"],
        ["renovation-capital", "Капитальный ремонт", "Күрделі жөндеу"],
        ["renovation-designer", "Дизайнерский ремонт", "Дизайнерлік жөндеу"],
        ["renovation-bathroom", "Ремонт ванной и санузла", "Жуынатын бөлме мен санитарлық торапты жөндеу"],
        ["renovation-kitchen", "Ремонт кухни", "Асүйді жөндеу"],
        ["renovation-commercial", "Ремонт офисов и коммерческих помещений", "Кеңселер мен коммерциялық орындарды жөндеу"],
      ], ["serviceBase", "propertyService"]), ["serviceBase", "propertyService"]),
      overlay("plumbing-services", serviceLeaves([
        ["plumber-emergency", "Аварийный сантехник", "Апаттық сантехник"],
        ["plumbing-fixtures-install", "Установка сантехники", "Сантехниканы орнату"],
        ["plumbing-pipe-install", "Монтаж и замена труб", "Құбырларды монтаждау және ауыстыру"],
        ["plumbing-leak-repair", "Устранение протечек", "Ағып кетуді жою"],
        ["plumbing-drain-cleaning", "Прочистка канализации", "Кәрізді тазалау"],
        ["plumbing-water-heater", "Установка и ремонт водонагревателей", "Су жылытқыштарды орнату және жөндеу"],
        ["plumbing-meters", "Установка счётчиков воды", "Су есептегіштерін орнату"],
        ["plumbing-heating", "Монтаж радиаторов и отопления", "Радиаторлар мен жылыту жүйесін монтаждау"],
      ], ["serviceBase", "plumbingService"]), ["serviceBase", "plumbingService"]),
      overlay("electrical-services", serviceLeaves([
        ["electrician-emergency", "Аварийный электрик", "Апаттық электрик"],
        ["electrical-wiring", "Монтаж и замена проводки", "Электр сымдарын монтаждау және ауыстыру"],
        ["electrical-panel", "Сборка и ремонт электрощитов", "Электр қалқандарын жинау және жөндеу"],
        ["electrical-outlets", "Розетки и выключатели", "Розеткалар мен ажыратқыштар"],
        ["electrical-lighting", "Монтаж освещения", "Жарықтандыруды монтаждау"],
        ["electrical-grounding", "Заземление и молниезащита", "Жерге қосу және найзағайдан қорғау"],
        ["electrical-smart-home", "Умный дом и автоматика", "Ақылды үй және автоматика"],
        ["electrical-measurements", "Электроизмерения и диагностика", "Электр өлшеу және диагностика"],
      ], ["serviceBase", "electricalService"]), ["serviceBase", "electricalService"]),
      overlay("windows-doors-services", serviceLeaves([
        ["windows-installation", "Установка окон", "Терезелерді орнату"],
        ["windows-repair", "Ремонт и регулировка окон", "Терезелерді жөндеу және реттеу"],
        ["balcony-glazing", "Остекление балконов", "Балкондарды әйнектеу"],
        ["doors-installation", "Установка дверей", "Есіктерді орнату"],
        ["doors-repair", "Ремонт дверей", "Есіктерді жөндеу"],
        ["locks-installation", "Установка и замена замков", "Құлыптарды орнату және ауыстыру"],
        ["locks-opening", "Вскрытие замков", "Құлыптарды ашу"],
        ["glass-mirror-installation", "Стекло и зеркала на заказ", "Тапсырыспен әйнек және айна"],
      ], ["serviceBase", "propertyService"]), ["serviceBase", "propertyService"]),
      overlay("finishing-services", serviceLeaves([
        ["plastering", "Штукатурные работы", "Сылақ жұмыстары"],
        ["painting", "Малярные работы", "Сырлау жұмыстары"],
        ["wallpapering", "Поклейка обоев", "Тұсқағаз жапсыру"],
        ["tiling", "Укладка плитки", "Плитка төсеу"],
        ["flooring-installation", "Укладка напольных покрытий", "Еден жабындарын төсеу"],
        ["stretch-ceilings", "Натяжные потолки", "Керме төбелер"],
        ["drywall-installation", "Гипсокартонные работы", "Гипсокартон жұмыстары"],
        ["decorative-finishes", "Декоративная отделка", "Сәндік әрлеу"],
      ], ["serviceBase", "propertyService"]), ["serviceBase", "propertyService"]),
      branch("ventilation-conditioning-services", "Вентиляция и кондиционирование", "Желдету және кондиционерлеу", [
        branch("air-conditioning-services", "Кондиционеры", "Кондиционерлер", serviceLeaves([
          ["air-conditioner-installation", "Установка кондиционеров", "Кондиционерлерді орнату"],
          ["air-conditioner-repair", "Ремонт кондиционеров", "Кондиционерлерді жөндеу"],
          ["air-conditioner-cleaning", "Чистка кондиционеров", "Кондиционерлерді тазалау"],
          ["air-conditioner-refill", "Заправка кондиционеров", "Кондиционерлерге фреон құю"],
          ["air-conditioner-maintenance", "Обслуживание кондиционеров", "Кондиционерлерге техникалық қызмет көрсету"],
          ["air-conditioner-dismantling", "Демонтаж и перенос кондиционеров", "Кондиционерлерді бөлшектеу және көшіру"],
        ], ["serviceBase", "hvacService"]), ["serviceBase", "hvacService"]),
        branch("ventilation-services", "Вентиляция", "Желдету", serviceLeaves([
          ["ventilation-design", "Проектирование вентиляции", "Желдетуді жобалау"],
          ["ventilation-installation", "Монтаж вентиляции", "Желдетуді монтаждау"],
          ["ventilation-repair", "Ремонт вентиляции", "Желдетуді жөндеу"],
          ["ventilation-cleaning", "Чистка вентиляции", "Желдетуді тазалау"],
          ["industrial-ventilation", "Промышленная вентиляция", "Өнеркәсіптік желдету"],
        ], ["serviceBase", "hvacService"]), ["serviceBase", "hvacService"]),
        branch("refrigeration-services", "Холодильное оборудование", "Тоңазытқыш жабдығы", serviceLeaves([
          ["refrigeration-installation", "Монтаж холодильного оборудования", "Тоңазытқыш жабдығын монтаждау"],
          ["refrigeration-repair", "Ремонт холодильного оборудования", "Тоңазытқыш жабдығын жөндеу"],
          ["refrigeration-maintenance", "Обслуживание холодильных систем", "Тоңазытқыш жүйелеріне қызмет көрсету"],
        ], ["serviceBase", "hvacService"]), ["serviceBase", "hvacService"]),
      ], ["serviceBase", "hvacService"]),
      branch("structural-construction-services", "Строительные работы", "Құрылыс жұмыстары", serviceLeaves([
        ["foundation-work", "Фундаментные работы", "Іргетас жұмыстары"],
        ["masonry-work", "Кладка кирпича и блоков", "Кірпіш және блок қалау"],
        ["concrete-work", "Бетонные работы", "Бетон жұмыстары"],
        ["roofing-work", "Кровельные работы", "Шатыр жұмыстары"],
        ["facade-work", "Фасадные работы", "Қасбет жұмыстары"],
        ["metal-welding-work", "Сварочные и металлоконструкции", "Дәнекерлеу және металл конструкциялар"],
        ["demolition-work", "Демонтаж и снос", "Бөлшектеу және бұзу"],
        ["insulation-work", "Утепление и гидроизоляция", "Жылу және су оқшаулау"],
        ["fence-gate-work", "Заборы и ворота", "Қоршаулар мен қақпалар"],
      ], ["serviceBase", "propertyService"]), ["serviceBase", "propertyService"]),
      branch("construction-design-supervision", "Проектирование и надзор", "Жобалау және қадағалау", serviceLeaves([
        ["architectural-design", "Архитектурное проектирование", "Сәулеттік жобалау"],
        ["interior-design-service", "Дизайн интерьера", "Интерьер дизайны"],
        ["engineering-design", "Инженерные проекты", "Инженерлік жобалар"],
        ["construction-estimates", "Сметы и расчёты", "Сметалар мен есептеулер"],
        ["technical-supervision", "Технический надзор", "Техникалық қадағалау"],
        ["land-surveying", "Геодезия и изыскания", "Геодезия және іздестіру"],
      ], ["serviceBase", "professionalService"]), ["serviceBase", "professionalService"]),
      branch("outdoor-improvement-services", "Благоустройство территории", "Аумақты абаттандыру", serviceLeaves([
        ["paving-services", "Укладка брусчатки", "Тротуар тасын төсеу"],
        ["landscaping-services", "Ландшафтные работы", "Ландшафт жұмыстары"],
        ["drainage-services", "Дренаж и ливневая канализация", "Дренаж және жауын кәрізі"],
        ["pool-construction", "Строительство и ремонт бассейнов", "Бассейн салу және жөндеу"],
      ], ["serviceBase", "propertyService"]), ["serviceBase", "propertyService"]),
      branch("handyman-services", "Мастер на час", "Сағаттық шебер", serviceLeaves([
        ["furniture-assembly-handyman", "Сборка и навеска мебели", "Жиһаз жинау және ілу"],
        ["minor-home-repair", "Мелкий бытовой ремонт", "Ұсақ тұрмыстық жөндеу"],
        ["curtain-tv-installation", "Установка карнизов, ТВ и полок", "Карниз, теледидар және сөрелерді орнату"],
      ], ["serviceBase", "householdService"]), ["serviceBase", "householdService"]),
    ], ["serviceBase", "propertyService"]),

    overlay("household-services", [
      ...serviceLeaves([
        ["tailoring-service", "Пошив и ремонт одежды", "Киім тігу және жөндеу"],
        ["shoe-repair-service", "Ремонт обуви", "Аяқ киім жөндеу"],
        ["watch-jewelry-repair", "Ремонт часов и украшений", "Сағаттар мен әшекейлерді жөндеу"],
        ["key-making-service", "Изготовление ключей", "Кілт жасау"],
        ["laundry-service", "Прачечная и глажка", "Кір жуу және үтіктеу"],
        ["dry-cleaning-service", "Химчистка одежды", "Киімді химиялық тазалау"],
        ["household-item-repair", "Ремонт чемоданов, сумок и зонтов", "Чемодан, сөмке және қолшатыр жөндеу"],
      ], ["serviceBase", "householdService"]),
    ], ["serviceBase", "householdService"]),

    overlay("appliance-repair", [
      branch("large-appliance-repair", "Крупная бытовая техника", "Ірі тұрмыстық техника", serviceLeaves([
        ["refrigerator-repair", "Ремонт холодильников", "Тоңазытқыштарды жөндеу"],
        ["washing-machine-repair", "Ремонт стиральных машин", "Кір жуғыш машиналарды жөндеу"],
        ["dishwasher-repair", "Ремонт посудомоечных машин", "Ыдыс жуғыш машиналарды жөндеу"],
        ["stove-oven-repair", "Ремонт плит и духовых шкафов", "Плиталар мен пештерді жөндеу"],
        ["water-heater-appliance-repair", "Ремонт водонагревателей", "Су жылытқыштарды жөндеу"],
        ["dryer-repair", "Ремонт сушильных машин", "Кептіргіш машиналарды жөндеу"],
      ], ["serviceBase", "applianceRepairService"]), ["serviceBase", "applianceRepairService"]),
      branch("digital-device-repair", "Цифровая техника", "Цифрлық техника", serviceLeaves([
        ["smartphone-repair", "Ремонт смартфонов", "Смартфондарды жөндеу"],
        ["tablet-repair", "Ремонт планшетов", "Планшеттерді жөндеу"],
        ["computer-laptop-repair", "Ремонт компьютеров и ноутбуков", "Компьютерлер мен ноутбуктерді жөндеу"],
        ["tv-repair", "Ремонт телевизоров", "Теледидарларды жөндеу"],
        ["game-console-repair", "Ремонт игровых приставок", "Ойын консольдерін жөндеу"],
        ["printer-repair", "Ремонт принтеров и оргтехники", "Принтерлер мен кеңсе техникасын жөндеу"],
        ["data-recovery-service", "Восстановление данных", "Деректерді қалпына келтіру"],
      ], ["serviceBase", "deviceRepairService"]), ["serviceBase", "deviceRepairService"]),
      branch("small-appliance-repair", "Мелкая бытовая техника", "Шағын тұрмыстық техника", serviceLeaves([
        ["vacuum-repair", "Ремонт пылесосов", "Шаңсорғыштарды жөндеу"],
        ["coffee-machine-repair", "Ремонт кофемашин", "Кофе машиналарын жөндеу"],
        ["microwave-repair", "Ремонт микроволновок", "Микротолқынды пештерді жөндеу"],
        ["small-kitchen-appliance-repair", "Ремонт кухонной техники", "Ас үй техникасын жөндеу"],
        ["sewing-machine-repair", "Ремонт швейных машин", "Тігін машиналарын жөндеу"],
      ], ["serviceBase", "applianceRepairService"]), ["serviceBase", "applianceRepairService"]),
    ], ["serviceBase", "applianceRepairService"]),

    overlay("auto-services", [
      ...serviceLeaves([
        ["auto-diagnostics", "Диагностика автомобиля", "Автокөлікті диагностикалау"],
        ["auto-maintenance", "Техническое обслуживание", "Техникалық қызмет көрсету"],
        ["engine-repair-service", "Ремонт двигателя", "Қозғалтқышты жөндеу"],
        ["transmission-repair-service", "Ремонт АКПП и трансмиссии", "АБҚ және трансмиссияны жөндеу"],
        ["suspension-repair-service", "Ремонт ходовой", "Жүріс бөлігін жөндеу"],
        ["auto-electrician-service", "Автоэлектрик", "Автоэлектрик"],
        ["body-repair-service", "Кузовной ремонт", "Шанақты жөндеу"],
        ["auto-painting-service", "Покраска автомобиля", "Автокөлікті бояу"],
        ["windshield-repair-service", "Ремонт и замена автостёкол", "Автоәйнектерді жөндеу және ауыстыру"],
        ["tire-service", "Шиномонтаж", "Шина монтажы"],
        ["wheel-alignment-service", "Развал-схождение", "Дөңгелек бұрыштарын реттеу"],
        ["car-wash-service", "Автомойка", "Автожуу"],
        ["car-detailing-service", "Детейлинг и химчистка салона", "Детейлинг және салонды химиялық тазалау"],
        ["car-air-conditioning-service", "Автокондиционеры", "Автокондиционерлер"],
        ["car-alarm-installation", "Автосигнализации и дополнительное оборудование", "Автодабыл және қосымша жабдық"],
        ["car-key-service", "Автоключи и вскрытие автомобилей", "Автокілттер және автокөлікті ашу"],
        ["prepurchase-car-inspection", "Выездная проверка перед покупкой", "Сатып алу алдындағы көшпелі тексеру"],
        ["motorcycle-service", "Ремонт мототехники", "Мототехниканы жөндеу"],
        ["truck-service", "Ремонт грузовиков и спецтехники", "Жүк көліктері мен арнайы техниканы жөндеу"],
      ], ["serviceBase", "autoService"]),
    ], ["serviceBase", "autoService"]),

    overlay("transport-services", [
      ...serviceLeaves([
        ["cargo-transport-city", "Грузоперевозки по городу", "Қала ішіндегі жүк тасымалы"],
        ["cargo-transport-intercity", "Междугородние грузоперевозки", "Қалааралық жүк тасымалы"],
        ["international-cargo-transport", "Международные грузоперевозки", "Халықаралық жүк тасымалы"],
        ["moving-services", "Квартирные и офисные переезды", "Пәтер және кеңсе көшіру"],
        ["loaders-service", "Грузчики", "Жүк тиеушілер"],
        ["passenger-transport", "Пассажирские перевозки", "Жолаушылар тасымалы"],
        ["chauffeur-service", "Авто с водителем", "Жүргізушісі бар көлік"],
        ["courier-delivery-service", "Курьерская доставка", "Курьерлік жеткізу"],
        ["vehicle-transportation", "Перевозка автомобилей", "Автокөліктерді тасымалдау"],
        ["towing-service", "Эвакуатор", "Эвакуатор"],
        ["manipulator-service", "Манипулятор", "Манипулятор"],
        ["crane-service", "Автокран и автовышка", "Автокран және автомұнара"],
        ["special-machinery-service", "Услуги спецтехники", "Арнайы техника қызметтері"],
        ["warehouse-service", "Складские услуги", "Қойма қызметтері"],
        ["freight-forwarding-service", "Экспедирование и логистика", "Экспедиция және логистика"],
      ], ["serviceBase", "transportService"]),
    ], ["serviceBase", "transportService"]),

    overlay("beauty-health-services", [
      branch("hair-beauty-services", "Волосы", "Шаш күтімі", serviceLeaves([
        ["haircut-service", "Стрижки", "Шаш қию"],
        ["hair-coloring-service", "Окрашивание волос", "Шаш бояу"],
        ["hair-styling-service", "Укладки и причёски", "Шаш сәндеу"],
        ["hair-extension-service", "Наращивание волос", "Шаш ұзарту"],
        ["barber-service", "Барбер", "Барбер"],
      ], ["serviceBase", "beautyService"]), ["serviceBase", "beautyService"]),
      branch("nails-brows-services", "Ногти, брови и ресницы", "Тырнақ, қас және кірпік", serviceLeaves([
        ["manicure-service", "Маникюр", "Маникюр"],
        ["pedicure-service", "Педикюр", "Педикюр"],
        ["brow-service", "Брови", "Қас күтімі"],
        ["lash-service", "Ресницы", "Кірпік күтімі"],
      ], ["serviceBase", "beautyService"]), ["serviceBase", "beautyService"]),
      branch("cosmetology-makeup-services", "Косметология и макияж", "Косметология және макияж", serviceLeaves([
        ["makeup-service", "Макияж", "Макияж"],
        ["cosmetology-service", "Косметология", "Косметология"],
        ["depilation-service", "Депиляция и шугаринг", "Депиляция және шугаринг"],
        ["tattoo-service", "Тату и пирсинг", "Тату және пирсинг"],
      ], ["serviceBase", "beautyService"]), ["serviceBase", "beautyService"]),
      branch("wellness-services", "Оздоровление и фитнес", "Сауықтыру және фитнес", serviceLeaves([
        ["massage-service", "Массаж", "Массаж"],
        ["personal-trainer-service", "Персональный тренер", "Жеке жаттықтырушы"],
        ["yoga-service", "Йога и растяжка", "Йога және созылу"],
        ["nutritionist-service", "Консультации по питанию", "Тамақтану бойынша кеңес"],
        ["psychologist-service", "Психолог", "Психолог"],
        ["home-nursing-service", "Медсестра на дом", "Үйге келетін мейіргер"],
      ], ["serviceBase", "wellnessService"]), ["serviceBase", "wellnessService"]),
    ], ["serviceBase", "beautyService"]),

    overlay("education-services", [
      branch("school-tutoring", "Школьные предметы", "Мектеп пәндері", serviceLeaves([
        ["math-tutor", "Математика", "Математика"],
        ["physics-tutor", "Физика", "Физика"],
        ["chemistry-tutor", "Химия", "Химия"],
        ["biology-tutor", "Биология", "Биология"],
        ["russian-tutor", "Русский язык и литература", "Орыс тілі мен әдебиеті"],
        ["kazakh-tutor", "Казахский язык и литература", "Қазақ тілі мен әдебиеті"],
        ["primary-school-tutor", "Начальная школа", "Бастауыш мектеп"],
      ], ["serviceBase", "educationService"]), ["serviceBase", "educationService"]),
      branch("language-learning", "Иностранные языки", "Шет тілдері", serviceLeaves([
        ["english-lessons", "Английский язык", "Ағылшын тілі"],
        ["chinese-lessons", "Китайский язык", "Қытай тілі"],
        ["german-lessons", "Немецкий язык", "Неміс тілі"],
        ["turkish-lessons", "Турецкий язык", "Түрік тілі"],
        ["other-language-lessons", "Другие языки", "Басқа тілдер"],
      ], ["serviceBase", "educationService"]), ["serviceBase", "educationService"]),
      ...serviceLeaves([
        ["exam-preparation", "Подготовка к ЕНТ и экзаменам", "ҰБТ және емтихандарға дайындық"],
        ["preschool-development", "Дошкольное развитие", "Мектепке дейінгі дамыту"],
        ["music-lessons", "Музыка и вокал", "Музыка және вокал"],
        ["driving-lessons", "Автошкола и вождение", "Автомектеп және жүргізу"],
        ["computer-courses", "Компьютерные и IT-курсы", "Компьютерлік және IT курстары"],
        ["professional-courses", "Профессиональные курсы", "Кәсіби курстар"],
        ["business-training", "Бизнес-обучение", "Бизнес оқыту"],
        ["sports-coaching", "Спортивные секции и тренеры", "Спорт секциялары мен жаттықтырушылар"],
        ["speech-therapist-service", "Логопед и коррекционные занятия", "Логопед және түзету сабақтары"],
      ], ["serviceBase", "educationService"]),
    ], ["serviceBase", "educationService"]),

    overlay("it-services", serviceLeaves([
      ["website-development", "Разработка сайтов", "Сайттар әзірлеу"],
      ["mobile-app-development", "Разработка мобильных приложений", "Мобильді қосымшалар әзірлеу"],
      ["software-development", "Разработка программ и интеграций", "Бағдарламалар мен интеграциялар әзірлеу"],
      ["ui-ux-design-service", "UI/UX и веб-дизайн", "UI/UX және веб-дизайн"],
      ["system-administration-service", "Системное администрирование", "Жүйелік әкімшілендіру"],
      ["network-setup-service", "Настройка сетей и Wi-Fi", "Желілер мен Wi-Fi баптау"],
      ["cybersecurity-service", "Информационная безопасность", "Ақпараттық қауіпсіздік"],
      ["one-c-service", "1С: настройка и сопровождение", "1С: баптау және сүйемелдеу"],
      ["business-automation-service", "Автоматизация бизнеса", "Бизнесті автоматтандыру"],
      ["seo-service", "SEO-продвижение", "SEO ілгерілету"],
      ["smm-service", "SMM и ведение соцсетей", "SMM және әлеуметтік желілерді жүргізу"],
      ["context-advertising-service", "Контекстная и таргетированная реклама", "Контекстік және нысаналы жарнама"],
      ["marketplace-management-service", "Ведение маркетплейсов", "Маркетплейстерді жүргізу"],
    ], ["serviceBase", "itService"]), ["serviceBase", "itService"]),

    overlay("photo-video-services", serviceLeaves([
      ["portrait-photography", "Портретная и семейная фотосъёмка", "Портрет және отбасылық фотосессия"],
      ["wedding-photography", "Свадебная фотосъёмка", "Үйлену тойын фотосуретке түсіру"],
      ["commercial-photography", "Предметная и рекламная съёмка", "Заттық және жарнамалық түсірілім"],
      ["event-video", "Видеосъёмка мероприятий", "Іс-шараларды бейнетүсірілім"],
      ["commercial-video", "Рекламные ролики", "Жарнамалық бейнероликтер"],
      ["drone-shooting", "Аэросъёмка", "Әуеден түсіру"],
      ["video-editing", "Монтаж и обработка видео", "Бейнені монтаждау және өңдеу"],
      ["photo-retouching", "Ретушь и обработка фото", "Фотосуретті ретушь және өңдеу"],
      ["digitization-service", "Оцифровка фото и видео", "Фото және бейнені цифрлау"],
      ["photo-printing-service", "Фотопечать", "Фотобаспа"],
      ["recording-studio-service", "Студия звукозаписи", "Дыбыс жазу студиясы"],
    ], ["serviceBase", "photoVideoService"]), ["serviceBase", "photoVideoService"]),

    overlay("legal-services", serviceLeaves([
      ["legal-consultation", "Юридическая консультация", "Заңгерлік кеңес"],
      ["legal-documents", "Составление договоров и документов", "Шарттар мен құжаттар дайындау"],
      ["court-representation", "Представительство в суде", "Сотта өкілдік ету"],
      ["family-law-service", "Семейное право", "Отбасы құқығы"],
      ["labor-law-service", "Трудовое право", "Еңбек құқығы"],
      ["real-estate-law-service", "Сделки с недвижимостью", "Жылжымайтын мүлік мәмілелері"],
      ["migration-law-service", "Миграционные вопросы", "Көші-қон мәселелері"],
      ["business-law-service", "Юридическое сопровождение бизнеса", "Бизнесті заңгерлік сүйемелдеу"],
      ["debt-bankruptcy-law", "Долги и банкротство", "Қарыздар және банкроттық"],
      ["intellectual-property-law", "Товарные знаки и авторское право", "Тауар белгілері және авторлық құқық"],
    ], ["serviceBase", "legalService"]), ["serviceBase", "legalService"]),

    overlay("accounting-services", serviceLeaves([
      ["bookkeeping-service", "Ведение бухгалтерии", "Бухгалтерия жүргізу"],
      ["tax-reporting-service", "Налоговая отчётность", "Салық есептілігі"],
      ["payroll-service", "Расчёт зарплаты и кадровый учёт", "Жалақы есептеу және кадрлық есеп"],
      ["accounting-restoration", "Восстановление учёта", "Есепті қалпына келтіру"],
      ["audit-service", "Аудит", "Аудит"],
      ["business-registration-service", "Регистрация ИП и ТОО", "ЖК және ЖШС тіркеу"],
      ["accounting-consultation", "Бухгалтерская консультация", "Бухгалтерлік кеңес"],
    ], ["serviceBase", "accountingService"]), ["serviceBase", "accountingService"]),

    overlay("event-services", serviceLeaves([
      ["event-planning", "Организация мероприятий под ключ", "Іс-шараларды толық ұйымдастыру"],
      ["event-host", "Ведущий и тамада", "Жүргізуші және асаба"],
      ["dj-service", "DJ", "DJ"],
      ["live-music-service", "Музыканты и вокалисты", "Музыканттар мен әншілер"],
      ["animator-service", "Аниматоры", "Аниматорлар"],
      ["event-decoration", "Оформление и декор", "Безендіру және декор"],
      ["floristry-service", "Флористика", "Флористика"],
      ["catering-service", "Кейтеринг", "Кейтеринг"],
      ["sound-light-service", "Звук, свет и сцена", "Дыбыс, жарық және сахна"],
      ["event-security-service", "Безопасность мероприятия", "Іс-шара қауіпсіздігі"],
    ], ["serviceBase", "eventService"]), ["serviceBase", "eventService"]),

    overlay("cleaning-services", serviceLeaves([
      ["apartment-cleaning", "Уборка квартир и домов", "Пәтерлер мен үйлерді тазалау"],
      ["office-cleaning", "Уборка офисов", "Кеңселерді тазалау"],
      ["post-renovation-cleaning", "Уборка после ремонта", "Жөндеуден кейін тазалау"],
      ["window-cleaning", "Мытьё окон", "Терезе жуу"],
      ["carpet-cleaning", "Химчистка ковров", "Кілемдерді химиялық тазалау"],
      ["furniture-dry-cleaning", "Химчистка мебели", "Жиһазды химиялық тазалау"],
      ["facade-cleaning", "Мойка фасадов и витрин", "Қасбеттер мен витриналарды жуу"],
      ["pest-control", "Дезинфекция и дезинсекция", "Дезинфекция және жәндіктерді жою"],
      ["waste-removal-service", "Вывоз мусора и хлама", "Қоқыс пен ескі заттарды шығару"],
    ], ["serviceBase", "cleaningService"]), ["serviceBase", "cleaningService"]),

    branch("security-services", "Охрана и безопасность", "Күзет және қауіпсіздік", serviceLeaves([
      ["physical-security-service", "Физическая охрана", "Физикалық күзет"],
      ["alarm-service", "Охранная сигнализация", "Күзет дабылы"],
      ["cctv-service", "Видеонаблюдение", "Бейнебақылау"],
      ["access-control-service", "Контроль доступа и домофоны", "Кіруді бақылау және домофондар"],
      ["fire-safety-service", "Пожарная сигнализация и безопасность", "Өрт дабылы және қауіпсіздігі"],
      ["security-audit-service", "Аудит безопасности", "Қауіпсіздік аудиті"],
    ], ["serviceBase", "securityService"]), ["serviceBase", "securityService"]),

    overlay("pet-services", serviceLeaves([
      ["veterinary-service", "Ветеринарные услуги", "Ветеринарлық қызметтер"],
      ["pet-grooming-service", "Груминг", "Груминг"],
      ["dog-walking-service", "Выгул животных", "Жануарларды серуендету"],
      ["pet-training-service", "Дрессировка и кинология", "Үйрету және кинология"],
      ["pet-sitting-service", "Передержка и зооняня", "Уақытша ұстау және зоокүтуші"],
      ["pet-hotel-service", "Гостиница для животных", "Жануарларға арналған қонақүй"],
      ["pet-transport-service", "Перевозка животных", "Жануарларды тасымалдау"],
    ], ["serviceBase", "petService"]), ["serviceBase", "petService"]),

    overlay("furniture-services", serviceLeaves([
      ["custom-kitchen-service", "Кухни на заказ", "Тапсырыспен асүй жиһазы"],
      ["custom-wardrobe-service", "Шкафы и гардеробные на заказ", "Тапсырыспен шкафтар мен гардеробтар"],
      ["custom-upholstered-furniture", "Мягкая мебель на заказ", "Тапсырыспен жұмсақ жиһаз"],
      ["custom-office-furniture", "Офисная и торговая мебель", "Кеңсе және сауда жиһазы"],
      ["furniture-assembly-service", "Сборка мебели", "Жиһаз жинау"],
      ["furniture-repair-service", "Ремонт мебели", "Жиһаз жөндеу"],
      ["furniture-upholstery-service", "Перетяжка мягкой мебели", "Жұмсақ жиһазды қайта қаптау"],
      ["furniture-restoration-service", "Реставрация мебели", "Жиһазды қалпына келтіру"],
    ], ["serviceBase", "furnitureService"]), ["serviceBase", "furnitureService"]),

    overlay("agro-services", serviceLeaves([
      ["soil-tillage-service", "Вспашка и обработка земли", "Жер жырту және өңдеу"],
      ["seeding-service", "Посевные работы", "Егіс жұмыстары"],
      ["harvesting-service", "Уборка урожая", "Егін жинау"],
      ["crop-spraying-service", "Опрыскивание и защита растений", "Өсімдіктерді бүрку және қорғау"],
      ["irrigation-agro-service", "Полив и мелиорация", "Суару және мелиорация"],
      ["haymaking-service", "Заготовка сена и кормов", "Шөп және жем дайындау"],
      ["agro-machinery-service", "Ремонт сельхозтехники", "Ауыл шаруашылық техникасын жөндеу"],
      ["livestock-service", "Услуги для животноводства", "Мал шаруашылығы қызметтері"],
      ["agro-consulting-service", "Агрономические консультации", "Агрономиялық кеңес"],
    ], ["serviceBase", "agroService"]), ["serviceBase", "agroService"]),

    overlay("business-services", serviceLeaves([
      ["business-consulting-service", "Бизнес-консалтинг", "Бизнес-консалтинг"],
      ["recruitment-service", "Подбор персонала", "Қызметкерлерді іріктеу"],
      ["translation-service", "Переводы", "Аударма"],
      ["printing-service", "Полиграфия и печать", "Полиграфия және баспа"],
      ["branding-service", "Брендинг и фирменный стиль", "Брендинг және фирмалық стиль"],
      ["certification-service", "Сертификация и разрешительные документы", "Сертификаттау және рұқсат құжаттары"],
      ["customs-broker-service", "Таможенное оформление", "Кедендік ресімдеу"],
      ["tender-support-service", "Тендерное сопровождение", "Тендерді сүйемелдеу"],
      ["procurement-service", "Закупки и снабжение", "Сатып алу және жабдықтау"],
      ["call-center-service", "Call-центр и обработка заявок", "Call-орталық және өтінімдерді өңдеу"],
      ["business-plan-service", "Бизнес-планы и финансовые модели", "Бизнес-жоспарлар және қаржылық модельдер"],
      ["office-relocation-service", "Офисный сервис и аутсорсинг", "Кеңсе сервисі және аутсорсинг"],
    ], ["serviceBase", "businessService"]), ["serviceBase", "businessService"]),

    branch("entertainment-services", "Развлечения", "Ойын-сауық", serviceLeaves([
      ["children-entertainment", "Детские развлечения", "Балалар ойын-сауығы"],
      ["quests-entertainment", "Квесты и игровые программы", "Квесттер мен ойын бағдарламалары"],
      ["performer-service", "Артисты и шоу-программы", "Әртістер мен шоу-бағдарламалар"],
      ["tour-guide-service", "Экскурсии и гиды", "Экскурсиялар мен гидтер"],
      ["recreation-instructor", "Инструкторы активного отдыха", "Белсенді демалыс нұсқаушылары"],
    ], ["serviceBase", "eventService"]), ["serviceBase", "eventService"]),

    branch("travel-immigration-services", "Туризм и иммиграция", "Туризм және иммиграция", serviceLeaves([
      ["travel-planning-service", "Подбор туров", "Турларды таңдау"],
      ["visa-service", "Визовая поддержка", "Визалық қолдау"],
      ["immigration-consulting-service", "Иммиграционные консультации", "Иммиграциялық кеңес"],
      ["document-translation-legalization", "Перевод и легализация документов", "Құжаттарды аудару және заңдастыру"],
    ], ["serviceBase", "travelService"]), ["serviceBase", "travelService"]),

    fallbackLeaf("other-services", "Другие услуги", "Басқа қызметтер", ["serviceBase"]),
  ], ["serviceBase"]),
];
