import { branch, fallbackLeaf, leaf, leaves, overlay, type MasterCatalogNode } from "./types.ts";

const vehicle = (entries: Parameters<typeof leaves>[0], profiles: readonly string[]) => leaves(entries, profiles);

export const transportCatalogOverlays: MasterCatalogNode[] = [
  overlay("transport", [
    overlay("cars", [
      leaf("cars-sedan", "Седаны", "Седандар", ["passengerCarSedan", "vehicleCompliance"]),
      leaf("cars-suv", "Кроссоверы и внедорожники", "Кроссоверлер мен жол талғамайтын көліктер", ["passengerCarSuv", "vehicleCompliance"]),
      leaf("cars-hatchback", "Хэтчбеки", "Хэтчбектер", ["passengerCarHatchback", "vehicleCompliance"]),
      leaf("cars-liftback", "Лифтбеки", "Лифтбектер", ["passengerCarLiftback", "vehicleCompliance"]),
      leaf("cars-wagon", "Универсалы", "Универсалдар", ["passengerCarWagon", "vehicleCompliance"]),
      leaf("cars-minivan", "Минивэны", "Минивэндер", ["passengerCarMinivan", "vehicleCompliance"]),
      leaf("cars-coupe", "Купе", "Купелер", ["passengerCarCoupe", "vehicleCompliance"]),
      leaf("cars-cabriolet", "Кабриолеты и родстеры", "Кабриолеттер мен родстерлер", ["passengerCarCabriolet", "vehicleCompliance"]),
      leaf("cars-pickup", "Пикапы", "Пикаптар", ["passengerCarPickup", "vehicleCompliance"]),
      fallbackLeaf("cars-other-body", "Другой кузов", "Басқа шанақ", ["passengerCarOther", "vehicleCompliance"]),
    ], ["passengerCar", "vehicleCompliance"]),
    overlay("motorcycles", [
      overlay("road-motorcycles", vehicle([
        ["motorcycles-sport", "Спортивные мотоциклы", "Спорттық мотоциклдер"],
        ["motorcycles-naked", "Дорожные и naked", "Жол және naked мотоциклдері"],
        ["motorcycles-touring", "Туристические", "Туристік мотоциклдер"],
        ["motorcycles-cruiser", "Круизеры и чопперы", "Круизерлер мен чопперлер"],
        ["motorcycles-enduro", "Эндуро и dual-sport", "Эндуро және dual-sport"],
        ["motorcycles-motocross", "Кроссовые и питбайки", "Кросс және питбайктар"],
        ["motorcycles-classic", "Классические и ретро", "Классикалық және ретро"],
      ], ["motorcycle"]), ["motorcycle"]),
      overlay("scooters", vehicle([
        ["scooters-standard", "Скутеры", "Скутерлер"],
        ["scooters-maxi", "Максискутеры", "Максискутерлер"],
        ["mopeds", "Мопеды", "Мопедтер"],
        ["electric-scooters-seated", "Электроскутеры", "Электр скутерлер"],
      ], ["motorcycle"]), ["motorcycle"]),
      overlay("atv", vehicle([
        ["quad-bikes", "Квадроциклы", "Квадроциклдер"],
        ["utv-side-by-side", "UTV и side-by-side", "UTV және side-by-side"],
        ["buggies", "Багги", "Баггилер"],
      ], ["motorcycle"]), ["motorcycle"]),
      leaf("snowmobiles", "Снегоходы", "Қар көліктері", ["motorcycle"]),
    ], ["motorcycle"]),
    overlay("commercial-transport", [
      overlay("trucks", vehicle([
        ["truck-tractor-units", "Седельные тягачи", "Ершікті тартқыштар"],
        ["truck-flatbeds", "Бортовые грузовики", "Бортты жүк көліктері"],
        ["truck-dumpers", "Самосвалы", "Өзі түсіретін жүк көліктері"],
        ["truck-vans", "Фургоны", "Фургондар"],
        ["truck-refrigerators", "Рефрижераторы", "Рефрижераторлар"],
        ["truck-tankers", "Цистерны", "Цистерналар"],
        ["truck-chassis", "Шасси", "Шассилер"],
      ], ["commercialVehicle"]), ["commercialVehicle"]),
      overlay("buses", vehicle([
        ["buses-city", "Городские автобусы", "Қалалық автобустар"],
        ["buses-intercity", "Междугородние и туристические", "Қалааралық және туристік"],
        ["buses-school", "Школьные и вахтовые", "Мектеп және вахталық"],
      ], ["commercialVehicle", "passengerCommercial"]), ["commercialVehicle", "passengerCommercial"]),
      overlay("minibuses", vehicle([
        ["minibuses-passenger", "Пассажирские микроавтобусы", "Жолаушылар шағын автобустары"],
        ["minibuses-cargo", "Грузовые микроавтобусы", "Жүк шағын автобустары"],
        ["minibuses-combi", "Грузопассажирские", "Жүк-жолаушылар"],
      ], ["commercialVehicle", "passengerCommercial"]), ["commercialVehicle", "passengerCommercial"]),
      overlay("trailers", vehicle([
        ["trailers-light", "Легковые прицепы", "Жеңіл көлік тіркемелері"],
        ["trailers-semitrailers", "Полуприцепы", "Жартылай тіркемелер"],
        ["trailers-truck", "Грузовые прицепы", "Жүк тіркемелері"],
        ["trailers-caravan", "Прицепы-дачи", "Тұрғын тіркемелер"],
        ["trailers-special", "Специальные прицепы", "Арнайы тіркемелер"],
      ], ["trailer"]), ["trailer"]),
    ], ["commercialVehicle"]),
    overlay("special-transport", [
      overlay("construction-machinery", vehicle([
        ["excavators", "Экскаваторы", "Экскаваторлар"],
        ["backhoe-loaders", "Экскаваторы-погрузчики", "Экскаватор-тиегіштер"],
        ["wheel-loaders", "Фронтальные погрузчики", "Фронталды тиегіштер"],
        ["bulldozers", "Бульдозеры", "Бульдозерлер"],
        ["mobile-cranes", "Автокраны", "Автокрандар"],
        ["tower-cranes", "Башенные краны", "Мұнара крандары"],
        ["concrete-machinery", "Бетонная техника", "Бетон техникасы"],
      ], ["machinery"]), ["machinery"]),
      overlay("road-machinery", vehicle([
        ["road-graders", "Автогрейдеры", "Автогрейдерлер"],
        ["road-rollers", "Катки", "Жол таптағыштар"],
        ["asphalt-pavers", "Асфальтоукладчики", "Асфальт төсегіштер"],
        ["road-milling-machines", "Дорожные фрезы", "Жол фрезалары"],
        ["road-sweepers", "Подметально-уборочная техника", "Жол сыпыру техникасы"],
      ], ["machinery"]), ["machinery"]),
      overlay("warehouse-machinery", vehicle([
        ["forklifts", "Вилочные погрузчики", "Айырлы тиегіштер"],
        ["telehandlers", "Телескопические погрузчики", "Телескопиялық тиегіштер"],
        ["stackers", "Штабелёры", "Штабелерлер"],
        ["pallet-trucks", "Гидравлические тележки", "Гидравликалық арбалар"],
      ], ["machinery"]), ["machinery"]),
      overlay("municipal-machinery", vehicle([
        ["garbage-trucks", "Мусоровозы", "Қоқыс таситын көліктер"],
        ["sewer-trucks", "Ассенизаторские машины", "Ассенизатор машиналары"],
        ["aerial-platforms", "Автовышки", "Автомұнаралар"],
        ["fire-trucks", "Пожарная техника", "Өрт сөндіру техникасы"],
        ["snow-removal-machinery", "Снегоуборочная техника", "Қар тазалау техникасы"],
      ], ["machinery"]), ["machinery"]),
      branch("drilling-machinery", "Буровая техника", "Бұрғылау техникасы", vehicle([
        ["drilling-rigs", "Буровые установки", "Бұрғылау қондырғылары"],
        ["pile-driving-machines", "Сваебойная техника", "Қада қағу техникасы"],
        ["compressor-stations", "Передвижные компрессоры", "Жылжымалы компрессорлар"],
      ], ["machinery"]), ["machinery"]),
      branch("mining-machinery", "Горнодобывающая техника", "Тау-кен техникасы", vehicle([
        ["mining-loaders", "Шахтные погрузчики", "Шахталық тиегіштер"],
        ["crushing-machinery", "Дробильная техника", "Ұсақтау техникасы"],
        ["quarry-dump-trucks", "Карьерные самосвалы", "Карьер самосвалдары"],
      ], ["machinery"]), ["machinery"]),
    ], ["machinery"]),
    overlay("agricultural-transport", [
      overlay("tractors", vehicle([
        ["tractors-wheeled", "Колёсные тракторы", "Дөңгелекті тракторлар"],
        ["tractors-mini", "Минитракторы", "Шағын тракторлар"],
        ["tractors-crawler", "Гусеничные тракторы", "Шынжыр табанды тракторлар"],
      ], ["machinery"]), ["machinery"]),
      overlay("harvesters", vehicle([
        ["combine-grain", "Зерноуборочные комбайны", "Астық жинайтын комбайндар"],
        ["combine-forage", "Кормоуборочные комбайны", "Мал азығын жинайтын комбайндар"],
        ["combine-special", "Картофеле- и свеклоуборочные", "Картоп және қызылша жинайтын"],
      ], ["machinery"]), ["machinery"]),
      overlay("agro-attachments", vehicle([
        ["agro-tillage", "Почвообрабатывающее оборудование", "Топырақ өңдеу жабдығы"],
        ["agro-seeding", "Посевная техника", "Егіс техникасы"],
        ["agro-hay", "Сенокосная техника", "Шөп шабу техникасы"],
        ["agro-sprayers", "Опрыскиватели", "Бүріккіштер"],
        ["agro-irrigation", "Поливная техника", "Суару техникасы"],
        ["agro-livestock", "Оборудование для животноводства", "Мал шаруашылығы жабдығы"],
      ], ["machinery"]), ["machinery"]),
      leaf("agricultural-utility-vehicles", "Сельскохозяйственные транспортёры", "Ауыл шаруашылық тасымалдағыштары", ["machinery"]),
    ], ["machinery"]),
    overlay("water-transport", vehicle([
      ["water-inflatable-boats", "Надувные лодки", "Үрлемелі қайықтар"],
      ["water-motorboats", "Моторные лодки и катера", "Моторлы қайықтар мен катерлер"],
      ["water-rowboats", "Вёсельные лодки", "Ескекті қайықтар"],
      ["water-yachts", "Яхты", "Яхталар"],
      ["water-jet-skis", "Гидроциклы", "Гидроциклдер"],
      ["water-outboard-engines", "Лодочные моторы", "Қайық қозғалтқыштары"],
      ["water-trailers", "Прицепы для водной техники", "Су техникасына арналған тіркемелер"],
    ], ["watercraft"]), ["watercraft"]),
    overlay("air-transport", vehicle([
      ["air-airplanes", "Самолёты", "Ұшақтар"],
      ["air-helicopters", "Вертолёты", "Тікұшақтар"],
      ["air-ultralight", "Сверхлёгкая авиация", "Аса жеңіл авиация"],
      ["air-gliders", "Парапланы и дельтапланы", "Парапландар мен дельтапландар"],
      ["air-parts", "Авиационные запчасти", "Авиациялық қосалқы бөлшектер"],
    ], ["aircraft"]), ["aircraft"]),
    branch("personal-electric-transport", "Персональный электротранспорт", "Жеке электр көлігі", vehicle([
      ["electric-kick-scooters", "Электросамокаты", "Электр самокаттар"],
      ["electric-unicycles", "Моноколёса", "Монодөңгелектер"],
      ["segways-hoverboards", "Сегвеи и гироскутеры", "Сегвейлер мен гироскутерлер"],
      ["golf-carts", "Гольф-кары и электрокары", "Гольф-карлар және электрокарлар"],
    ], ["electricPersonalTransport"]), ["electricPersonalTransport"]),
    overlay("other-transport", [
      leaf("motorhomes", "Автодома", "Автоүйлер", ["commercialVehicle"]),
      leaf("go-karts", "Карты и картинги", "Карттар мен картингтер", ["transportSimple"]),
      fallbackLeaf("other-transport-unlisted", "Другой транспорт", "Басқа көлік", ["transportSimple"]),
    ], ["transportSimple"]),
  ]),
];

export const partsCatalogOverlays: MasterCatalogNode[] = [
  overlay("parts", [
    overlay("car-parts", [
      overlay("engine-parts", leaves([
        ["engines-complete", "Двигатели в сборе", "Жинақталған қозғалтқыштар"],
        ["engine-block-head", "Блоки и головки цилиндров", "Цилиндр блоктары мен бастиектері"],
        ["engine-pistons-crank", "Поршневая и кривошипная группа", "Поршень және иінді механизм"],
        ["engine-timing", "ГРМ", "Газ тарату механизмі"],
        ["engine-fuel-system", "Топливная система", "Отын жүйесі"],
        ["engine-cooling", "Система охлаждения", "Салқындату жүйесі"],
        ["engine-intake-turbo", "Впуск и турбонаддув", "Ауа кіргізу және турбо"],
        ["engine-exhaust", "Выхлопная система", "Шығару жүйесі"],
        ["engine-mounts", "Опоры двигателя", "Қозғалтқыш тіректері"],
      ], ["autoPart"]), ["autoPart"]),
      overlay("transmission-parts", leaves([
        ["gearboxes", "Коробки передач", "Беріліс қораптары"],
        ["clutch-parts", "Сцепление", "Ілініс"],
        ["transfer-cases", "Раздаточные коробки", "Тарату қораптары"],
        ["driveshafts", "Карданные валы", "Кардан біліктері"],
        ["differentials", "Редукторы и дифференциалы", "Редукторлар мен дифференциалдар"],
        ["cv-joints-axles", "ШРУСы и приводы", "ШРУС және жетек біліктері"],
      ], ["autoPart"]), ["autoPart"]),
      overlay("suspension-parts", leaves([
        ["shock-absorbers", "Амортизаторы и стойки", "Амортизаторлар мен тіректер"],
        ["suspension-springs", "Пружины и рессоры", "Серіппелер мен рессорлар"],
        ["suspension-arms", "Рычаги и сайлентблоки", "Иінтіректер мен сайлентблоктар"],
        ["wheel-bearings-hubs", "Ступицы и подшипники", "Күпшектер мен мойынтіректер"],
        ["steering-parts", "Рулевое управление", "Руль жүйесі"],
        ["brake-parts", "Тормозная система", "Тежегіш жүйесі"],
      ], ["autoPart"]), ["autoPart"]),
      overlay("body-parts", leaves([
        ["body-bumpers", "Бамперы", "Бамперлер"],
        ["body-doors", "Двери", "Есіктер"],
        ["body-fenders", "Крылья", "Қанаттар"],
        ["body-hoods-trunks", "Капоты и крышки багажника", "Капоттар мен жүксалғыш қақпақтары"],
        ["body-glass", "Автостёкла", "Автоәйнектер"],
        ["body-mirrors", "Зеркала", "Айналар"],
        ["body-frames", "Рамы и кузова", "Рамалар мен шанақтар"],
      ], ["autoPart"]), ["autoPart"]),
      overlay("auto-electrics", leaves([
        ["electrics-starters", "Стартеры", "Стартерлер"],
        ["electrics-alternators", "Генераторы", "Генераторлар"],
        ["car-batteries", "Аккумуляторы", "Аккумуляторлар"],
        ["electrics-sensors", "Датчики", "Датчиктер"],
        ["electrics-ecu", "ЭБУ и блоки управления", "ЭББ және басқару блоктары"],
        ["electrics-wiring", "Проводка и разъёмы", "Сымдар мен жалғағыштар"],
        ["electrics-ignition", "Система зажигания", "Оталдыру жүйесі"],
      ], ["autoPart"]), ["autoPart"]),
      overlay("optics", leaves([
        ["headlights", "Передние фары", "Алдыңғы шамдар"],
        ["rear-lights", "Задние фонари", "Артқы шамдар"],
        ["fog-lights", "Противотуманные фары", "Тұманға қарсы шамдар"],
        ["car-bulbs-led", "Автолампы и LED", "Автошамдар және LED"],
      ], ["autoPart"]), ["autoPart"]),
      overlay("interior-parts", leaves([
        ["interior-seats", "Сиденья", "Орындықтар"],
        ["interior-trim", "Обшивка и элементы салона", "Салон қаптамасы мен бөлшектері"],
        ["interior-dashboard", "Панели приборов", "Аспап панельдері"],
        ["interior-climate", "Отопители и кондиционирование", "Жылыту және кондиционер жүйесі"],
        ["interior-airbags", "Подушки безопасности", "Қауіпсіздік жастықтары"],
      ], ["autoPart"]), ["autoPart"]),
    ], ["autoPart"]),
    overlay("tires-wheels", leaves([
      ["car-tires", "Шины", "Шиналар", ["tires"]],
      ["wheel-rims", "Диски", "Дискілер", ["wheels"]],
      ["complete-wheels", "Колёса в сборе", "Жинақталған дөңгелектер", ["tires"]],
      ["wheel-caps-spacers", "Колпаки, проставки и крепёж", "Қалпақтар, аралықтар және бекіткіштер", ["autoPart"]],
    ]), ["tires"]),
    overlay("car-accessories", leaves([
      ["car-electronics-accessories", "Автоэлектроника", "Автоэлектроника"],
      ["car-mats-covers", "Коврики и чехлы", "Кілемшелер мен қаптар"],
      ["car-roof-racks", "Багажники и боксы", "Жүксалғыштар мен бокстар"],
      ["car-tools-emergency", "Инструменты и аварийные принадлежности", "Құралдар мен апаттық жабдықтар"],
      ["car-tuning", "Тюнинг", "Тюнинг"],
      ["car-care-products", "Уход за автомобилем", "Автокөлік күтімі"],
    ], ["goodsBrand"]), ["goodsBrand"]),
    overlay("oils-fluids", leaves([
      ["engine-oils", "Моторные масла", "Мотор майлары"],
      ["transmission-oils", "Трансмиссионные масла", "Трансмиссия майлары"],
      ["coolants", "Антифризы и охлаждающие жидкости", "Антифриздер мен салқындатқыштар"],
      ["brake-fluids", "Тормозные жидкости", "Тежегіш сұйықтықтары"],
      ["fuel-additives", "Присадки", "Қоспалар"],
      ["auto-chemicals", "Автохимия", "Автохимия"],
    ], ["fluids"]), ["fluids"]),
    overlay("moto-parts", leaves([
      ["moto-engine-parts", "Двигатель и трансмиссия", "Қозғалтқыш және трансмиссия"],
      ["moto-frame-suspension", "Рама и подвеска", "Рама және аспа"],
      ["moto-brakes-wheels", "Тормоза и колёса", "Тежегіштер мен дөңгелектер"],
      ["moto-electrics", "Мотоэлектрика", "Мотоэлектрика"],
      ["moto-accessories", "Мотоаксессуары и экипировка", "Мотоаксессуарлар мен жабдық"],
    ], ["motoPart"]), ["motoPart"]),
    overlay("special-parts", leaves([
      ["truck-parts", "Запчасти для грузовиков", "Жүк көліктерінің бөлшектері"],
      ["bus-parts", "Запчасти для автобусов", "Автобус бөлшектері"],
      ["construction-machinery-parts", "Запчасти для спецтехники", "Арнайы техника бөлшектері"],
      ["agricultural-machinery-parts", "Запчасти для сельхозтехники", "Ауыл шаруашылық техника бөлшектері"],
      ["trailer-parts", "Запчасти для прицепов", "Тіркеме бөлшектері"],
    ], ["commercialPart"]), ["commercialPart"]),
    leaf("auto-dismantling", "Авторазборы", "Автобөлшектеу", ["dismantling"]),
  ], ["autoPart"]),
];
